import { GravityPathLevel } from './gravity-path.types';

export const GRAVITY_PATH_LEVELS: GravityPathLevel[] = [
  {
    id: 'grav-01',
    name: 'Level 1: Downward Pull',
    gridSize: { rows: 4, cols: 4 },
    start: { row: 0, col: 0 },
    target: { row: 3, col: 3 },
    maxMoves: 6,
    description: {
      en: 'Shift gravity Right then Down to slide into the collection flask.',
      ta: 'வலது மற்றும் கீழ்நோக்கி ஈர்ப்பு விசையை மாற்றி இலக்கை அடையவும்.',
    },
    grid: [
      ['start', 'empty', 'empty', 'empty'],
      ['empty', 'wall', 'empty', 'empty'],
      ['empty', 'empty', 'wall', 'empty'],
      ['empty', 'empty', 'empty', 'target'],
    ],
  },
  {
    id: 'grav-02',
    name: 'Level 2: Wall Deflection',
    gridSize: { rows: 4, cols: 4 },
    start: { row: 0, col: 0 },
    target: { row: 2, col: 1 },
    maxMoves: 8,
    description: {
      en: 'Use the stopper block to arrest particle momentum.',
      ta: 'தடைக்கற்களை பயன்படுத்தி துகளின் வேகத்தைக் கட்டுப்படுத்தவும்.',
    },
    grid: [
      ['start', 'empty', 'empty', 'empty'],
      ['empty', 'empty', 'wall', 'empty'],
      ['empty', 'target', 'empty', 'empty'],
      ['empty', 'wall', 'empty', 'empty'],
    ],
  },
  {
    id: 'grav-03',
    name: 'Level 3: Laser Hazard',
    gridSize: { rows: 5, cols: 5 },
    start: { row: 0, col: 0 },
    target: { row: 4, col: 4 },
    maxMoves: 10,
    description: {
      en: 'Avoid sliding into the central high-voltage hazard zone.',
      ta: 'மையத்தில் உள்ள அபாய பகுதியை தவிர்த்து பாதுகாப்பாக நகரவும்.',
    },
    grid: [
      ['start', 'empty', 'empty', 'empty', 'empty'],
      ['empty', 'wall', 'hazard', 'empty', 'empty'],
      ['empty', 'hazard', 'wall', 'hazard', 'empty'],
      ['empty', 'empty', 'hazard', 'wall', 'empty'],
      ['empty', 'empty', 'empty', 'empty', 'target'],
    ],
  },
  {
    id: 'grav-04',
    name: 'Level 4: Portal Leap',
    gridSize: { rows: 5, cols: 5 },
    start: { row: 0, col: 0 },
    target: { row: 4, col: 0 },
    portalA: { row: 0, col: 4 },
    portalB: { row: 4, col: 4 },
    maxMoves: 8,
    description: {
      en: 'Slide into Portal Alpha to teleport across to Portal Beta.',
      ta: 'போர்டல் ஆல்பா வழியே நுழைந்து போர்டல் பீட்டாவில் வெளிவரவும்.',
    },
    grid: [
      ['start', 'empty', 'empty', 'empty', 'portal-a'],
      ['wall', 'wall', 'empty', 'wall', 'wall'],
      ['empty', 'empty', 'empty', 'empty', 'empty'],
      ['wall', 'wall', 'empty', 'wall', 'wall'],
      ['target', 'empty', 'empty', 'empty', 'portal-b'],
    ],
  },
  {
    id: 'grav-05',
    name: 'Level 5: Four-Way Cornering',
    gridSize: { rows: 5, cols: 5 },
    start: { row: 2, col: 2 },
    target: { row: 0, col: 4 },
    maxMoves: 10,
    description: {
      en: 'Navigate from center outward through sequential gravity pulses.',
      ta: 'மையத்திலிருந்து நான்கு திசை ஈர்ப்பு விசைகள் மூலம் வெளியேறவும்.',
    },
    grid: [
      ['empty', 'empty', 'empty', 'empty', 'target'],
      ['empty', 'wall', 'empty', 'wall', 'empty'],
      ['empty', 'empty', 'start', 'empty', 'empty'],
      ['empty', 'wall', 'empty', 'wall', 'empty'],
      ['empty', 'empty', 'empty', 'empty', 'empty'],
    ],
  },
  {
    id: 'grav-06',
    name: 'Level 6: Dual Portal Loop',
    gridSize: { rows: 5, cols: 5 },
    start: { row: 2, col: 0 },
    target: { row: 2, col: 4 },
    portalA: { row: 0, col: 2 },
    portalB: { row: 4, col: 2 },
    maxMoves: 10,
    description: {
      en: 'Loop vertically through portals to access the right chamber.',
      ta: 'செங்குத்து போர்ட்டல்கள் மூலம் வலது அறைக்குள் செல்லவும்.',
    },
    grid: [
      ['wall', 'empty', 'portal-a', 'empty', 'wall'],
      ['wall', 'wall', 'empty', 'wall', 'wall'],
      ['start', 'empty', 'empty', 'empty', 'target'],
      ['wall', 'wall', 'empty', 'wall', 'wall'],
      ['wall', 'empty', 'portal-b', 'empty', 'wall'],
    ],
  },
  {
    id: 'grav-07',
    name: 'Level 7: Precision Pinball',
    gridSize: { rows: 5, cols: 5 },
    start: { row: 0, col: 0 },
    target: { row: 4, col: 2 },
    maxMoves: 12,
    description: {
      en: 'Bounce between perimeter blocks without falling into traps.',
      ta: 'சுவர்களில் பட்டு துள்ளி இலக்கு புனலில் விழ வைக்கவும்.',
    },
    grid: [
      ['start', 'empty', 'wall', 'empty', 'empty'],
      ['empty', 'empty', 'empty', 'wall', 'empty'],
      ['wall', 'empty', 'empty', 'empty', 'wall'],
      ['empty', 'wall', 'empty', 'empty', 'empty'],
      ['empty', 'empty', 'target', 'wall', 'empty'],
    ],
  },
  {
    id: 'grav-08',
    name: 'Level 8: Quantum Slalom',
    gridSize: { rows: 5, cols: 5 },
    start: { row: 4, col: 0 },
    target: { row: 0, col: 4 },
    maxMoves: 12,
    description: {
      en: 'Navigate a staggered obstacle maze using 45-degree corner stops.',
      ta: 'திசைமாறும் சுவர்கள் வழியே குறுக்காக முன்னேறவும்.',
    },
    grid: [
      ['empty', 'empty', 'wall', 'empty', 'target'],
      ['wall', 'empty', 'empty', 'empty', 'wall'],
      ['empty', 'wall', 'hazard', 'wall', 'empty'],
      ['empty', 'empty', 'empty', 'empty', 'empty'],
      ['start', 'empty', 'wall', 'empty', 'empty'],
    ],
  },
  {
    id: 'grav-09',
    name: 'Level 9: Magnetic Trap Escape',
    gridSize: { rows: 5, cols: 5 },
    start: { row: 0, col: 2 },
    target: { row: 4, col: 2 },
    portalA: { row: 2, col: 0 },
    portalB: { row: 2, col: 4 },
    maxMoves: 14,
    description: {
      en: 'Cross the central vacuum barrier via quantum tunnel.',
      ta: 'குவாண்டம் சுரங்கப்பாதை வழியாக வெற்றிட தடுப்பை கடக்கவும்.',
    },
    grid: [
      ['empty', 'empty', 'start', 'empty', 'empty'],
      ['wall', 'wall', 'empty', 'wall', 'wall'],
      ['portal-a', 'empty', 'hazard', 'empty', 'portal-b'],
      ['wall', 'wall', 'empty', 'wall', 'wall'],
      ['empty', 'empty', 'target', 'empty', 'empty'],
    ],
  },
  {
    id: 'grav-10',
    name: 'Level 10: Zero-G Master Lab',
    gridSize: { rows: 5, cols: 5 },
    start: { row: 0, col: 0 },
    target: { row: 2, col: 2 },
    portalA: { row: 0, col: 4 },
    portalB: { row: 4, col: 0 },
    maxMoves: 16,
    description: {
      en: 'Solve the ultimate multi-step gravity funnel into center core.',
      ta: 'மைய பகுதிக்குள் சென்று சேரும் முதன்மை ஈர்ப்பு விசை புதிர்.',
    },
    grid: [
      ['start', 'empty', 'wall', 'empty', 'portal-a'],
      ['empty', 'hazard', 'empty', 'hazard', 'empty'],
      ['wall', 'empty', 'target', 'empty', 'wall'],
      ['empty', 'hazard', 'empty', 'hazard', 'empty'],
      ['portal-b', 'empty', 'wall', 'empty', 'empty'],
    ],
  },
];
