import { LabEscapeLevel } from './lab-escape.types';

export const LAB_ESCAPE_LEVELS: LabEscapeLevel[] = [
  {
    id: 'esc-01',
    name: 'Level 1: Chemistry Containment',
    theme: { en: 'Chemical Spill Chamber', ta: 'வேதியியல் கசிவு அறை' },
    description: {
      en: 'Neutralize the acid spill, power the ventilation fan, and unlock the safety airlock.',
      ta: 'அமிலக் கசிவை சமன்செய்து காற்று விசிறியை இயக்கி கதவைத் திறக்கவும்.',
    },
    stages: [
      {
        id: 's1',
        stageNumber: 1,
        title: { en: '1. Neutralize Acid', ta: '1. அமிலத்தை நடுநிலையாக்கு' },
        prompt: { en: 'Which basic compound neutralizes the spilled Hydrochloric Acid (HCl)?', ta: 'ஹைட்ரோகுளோரிக் அமிலத்தை நடுநிலையாக்க எந்த காரப் பொருள் தேவை?' },
        hint: { en: 'Look for a mild household alkali base (Sodium Bicarbonate).', ta: 'சமையல் சோடா (சோடியம் பைகார்பனேட்) காரத்தன்மை கொண்டது.' },
        options: [
          { id: 'opt-water', label: { en: 'Distilled Water', ta: 'வடிகட்டிய நீர்' }, icon: '💧' },
          { id: 'opt-baking-soda', label: { en: 'Sodium Bicarbonate (Baking Soda)', ta: 'சோடியம் பைகார்பனேட்' }, icon: '🧂' },
          { id: 'opt-sulfuric', label: { en: 'Sulfuric Acid', ta: 'கந்தக அமிலம்' }, icon: '🧪' },
          { id: 'opt-oil', label: { en: 'Mineral Oil', ta: 'கனிம எண்ணெய்' }, icon: '🛢️' },
        ],
        correctOptionId: 'opt-baking-soda',
      },
      {
        id: 's2',
        stageNumber: 2,
        title: { en: '2. Power Exhaust Fan', ta: '2. வெளியேற்று விசிறியை இயக்கு' },
        prompt: { en: 'Connect the power switch to restore 240V auxiliary circuit:', ta: 'துணை மின்சுற்றை இயக்க சரியான இணைப்பைத் தேர்வுசெய்க:' },
        hint: { en: 'A closed series circuit is required.', ta: 'மின்சுற்று முழுமையாக மூடப்பட்டிருக்க வேண்டும்.' },
        options: [
          { id: 'opt-switch-closed', label: { en: 'Close Auxiliary Breaker (ON)', ta: 'மின் இணைப்பை இயக்கு (ON)' }, icon: '⚡' },
          { id: 'opt-disconnect', label: { en: 'Cut Ground Cable', ta: 'தரை இணைப்பை துண்டி' }, icon: '✂️' },
          { id: 'opt-fuse-remove', label: { en: 'Remove Main Fuse', ta: 'பியூஸ் கம்பியை அகற்று' }, icon: '🔌' },
        ],
        correctOptionId: 'opt-switch-closed',
      },
      {
        id: 's3',
        stageNumber: 3,
        title: { en: '3. Enter Airlock Keycode', ta: '3. பாதுகாப்பு குறியீட்டை உள்ளிடு' },
        prompt: { en: 'The airlock code is the atomic number of Oxygen (O) times Carbon (C): 8 × 6 = ?', ta: 'ஆக்சிஜன் (8) × கார்பன் (6) அணு எண்களின் பெருக்கற்பலன் என்ன?' },
        hint: { en: '8 multiplied by 6.', ta: '8 ஐ 6 ஆல் பெருக்கவும்.' },
        options: [
          { id: 'opt-42', label: { en: 'Code 42', ta: 'குறியீடு 42' }, icon: '🔢' },
          { id: 'opt-48', label: { en: 'Code 48', ta: 'குறியீடு 48' }, icon: '🔢' },
          { id: 'opt-54', label: { en: 'Code 54', ta: 'குறியீடு 54' }, icon: '🔢' },
          { id: 'opt-64', label: { en: 'Code 64', ta: 'குறியீடு 64' }, icon: '🔢' },
        ],
        correctOptionId: 'opt-48',
      },
    ],
  },
  {
    id: 'esc-02',
    name: 'Level 2: Cryogenics Lab',
    theme: { en: 'Sub-Zero Cryo Chamber', ta: 'உறைபனி ஆய்வகம்' },
    description: {
      en: 'Warm the thermal coils, decode the freezing point, and disengage magnetic seal.',
      ta: 'வெப்ப சுருளை இயக்கி காந்த பூட்டை விடுவித்து வெளியேறவும்.',
    },
    stages: [
      {
        id: 's1',
        stageNumber: 1,
        title: { en: '1. Select Heating Element', ta: '1. வெப்பமூட்டும் தனிமத்தை தேர்வு செய்' },
        prompt: { en: 'Which high-resistance metal alloy is used in heating coils?', ta: 'மின்சார வெப்பமூட்டும் சாதனங்களில் பயன்படும் கலப்புலோகம் எது?' },
        hint: { en: 'Nichrome has extremely high electrical resistivity.', ta: 'நிக்ரோம் அதிக மின்தடை கொண்டது.' },
        options: [
          { id: 'opt-nichrome', label: { en: 'Nichrome (Ni-Cr)', ta: 'நிக்ரோம்' }, icon: '🔥' },
          { id: 'opt-lead', label: { en: 'Lead (Pb)', ta: 'ஈயம்' }, icon: '⚪' },
          { id: 'opt-mercury', label: { en: 'Mercury (Hg)', ta: 'பாதரசம்' }, icon: '💧' },
        ],
        correctOptionId: 'opt-nichrome',
      },
      {
        id: 's2',
        stageNumber: 2,
        title: { en: '2. Absolute Zero Target', ta: '2. தனிச்சுழி வெப்பநிலை இலக்கு' },
        prompt: { en: 'Set temperature gauge to the value of Absolute Zero:', ta: 'தனிச்சுழி வெப்பநிலையின் மதிப்பைத் தேர்ந்தெடுக்கவும்:' },
        hint: { en: '-273.15 °C (0 Kelvin).', ta: '-273.15 °C அல்லது 0 கெல்வின்.' },
        options: [
          { id: 'opt-0c', label: { en: '0 °C', ta: '0 °C' }, icon: '❄️' },
          { id: 'opt-minus273', label: { en: '-273.15 °C (0 K)', ta: '-273.15 °C (0 K)' }, icon: '🧊' },
          { id: 'opt-minus100', label: { en: '-100 °C', ta: '-100 °C' }, icon: '🌡️' },
        ],
        correctOptionId: 'opt-minus273',
      },
      {
        id: 's3',
        stageNumber: 3,
        title: { en: '3. Demagnetize Hatch', ta: '3. காந்தப் பூட்டை செயலிழக்கச் செய்' },
        prompt: { en: 'To neutralize magnetic hold, apply reverse electromagnetic pulse at frequency:', ta: 'காந்தப்புலத்தை ரத்து செய்ய தேவையான அலைவரிசை:' },
        hint: { en: 'Atomic number of Iron (Fe = 26) in kHz.', ta: 'இரும்பின் அணு எண் (Fe = 26).' },
        options: [
          { id: 'opt-26', label: { en: '26 kHz Pulse', ta: '26 kHz துடிப்பு' }, icon: '🧲' },
          { id: 'opt-30', label: { en: '30 kHz Pulse', ta: '30 kHz துடிப்பு' }, icon: '🧲' },
          { id: 'opt-52', label: { en: '52 kHz Pulse', ta: '52 kHz துடிப்பு' }, icon: '🧲' },
        ],
        correctOptionId: 'opt-26',
      },
    ],
  },
  {
    id: 'esc-03',
    name: 'Level 3: Optics Laser Maze',
    theme: { en: 'Laser Alignment Vault', ta: 'லேசர் ஒளியியல் அறை' },
    description: {
      en: 'Refract laser with prism, align mirrors, and trigger optical sensor.',
      ta: 'முப்பட்டகம் வழியே லேசரை வளைத்து சென்சாரை இயக்கி தப்பிக்கவும்.',
    },
    stages: [
      {
        id: 's1',
        stageNumber: 1,
        title: { en: '1. Refraction Prism', ta: '1. ஒளிவிலகல் முப்பட்டகம்' },
        prompt: { en: 'Which optical element splits white light into 7 constituent spectral colors?', ta: 'வெள்ளை ஒளியை 7 வண்ணங்களாக பிரிக்கும் ஒளியியல் சாதனம் எது?' },
        hint: { en: 'A triangular glass prism.', ta: 'முக்கோண கண்ணாடி முப்பட்டகம்.' },
        options: [
          { id: 'opt-prism', label: { en: 'Triangular Prism', ta: 'முப்பட்டகம்' }, icon: '🌈' },
          { id: 'opt-mirror', label: { en: 'Flat Mirror', ta: 'சமதள கண்ணாடி' }, icon: '🪞' },
          { id: 'opt-lens-concave', label: { en: 'Concave Lens', ta: 'குழி லென்ஸ்' }, icon: '🔍' },
        ],
        correctOptionId: 'opt-prism',
      },
      {
        id: 's2',
        stageNumber: 2,
        title: { en: '2. Law of Reflection', ta: '2. எதிரொளிப்பு விதி' },
        prompt: { en: 'If incoming laser angle of incidence is 45°, what is angle of reflection?', ta: 'படுகோணம் 45° எனில் எதிரொளிப்புக் கோணம் என்ன?' },
        hint: { en: 'Angle of Incidence (i) = Angle of Reflection (r).', ta: 'படுகோணம் = எதிரொளிப்புக் கோணம்.' },
        options: [
          { id: 'opt-45', label: { en: '45°', ta: '45°' }, icon: '📐' },
          { id: 'opt-90', label: { en: '90°', ta: '90°' }, icon: '📐' },
          { id: 'opt-30', label: { en: '30°', ta: '30°' }, icon: '📐' },
        ],
        correctOptionId: 'opt-45',
      },
      {
        id: 's3',
        stageNumber: 3,
        title: { en: '3. Speed of Light Code', ta: '3. ஒளியின் திசைவேக குறியீடு' },
        prompt: { en: 'Speed of light in vacuum is approx: 3 × 10⁸ m/s. Select code prefix:', ta: 'வெற்றிடத்தில் ஒளியின் திசைவேகம்: 3 × 10⁸ மீ/வி. குறியீடு:' },
        hint: { en: '300,000 km/s.', ta: 'வினாடிக்கு 3 லட்சம் கி.மீ.' },
        options: [
          { id: 'opt-300', label: { en: '300', ta: '300' }, icon: '⚡' },
          { id: 'opt-150', label: { en: '150', ta: '150' }, icon: '⚡' },
          { id: 'opt-450', label: { en: '450', ta: '450' }, icon: '⚡' },
        ],
        correctOptionId: 'opt-300',
      },
    ],
  },
  {
    id: 'esc-04',
    name: 'Level 4: Biohazard Quarantine',
    theme: { en: 'Microbiology Quarantine', ta: 'உயிரியல் தனிமைப்படுத்தல் அறை' },
    description: {
      en: 'Autoclave decontamination, UV sterilization, and genetic passcode entry.',
      ta: 'புற ஊதா கிருமிநாசினி இயக்கி மரபணு குறியீடு மூலம் தப்பிக்கவும்.',
    },
    stages: [
      {
        id: 's1',
        stageNumber: 1,
        title: { en: '1. Sterilization Wave', ta: '1. கிருமிநாசினி கதிர்வீச்சு' },
        prompt: { en: 'Which electromagnetic radiation sterilizes bacterial DNA effectively?', ta: 'பாக்டீரியாக்களை அழிக்க பயன்படும் கதிர்வீச்சு எது?' },
        hint: { en: 'UV-C ultraviolet radiation destroys pathogen RNA/DNA.', ta: 'UV-C புற ஊதாக் கதிர்வீச்சு.' },
        options: [
          { id: 'opt-uv', label: { en: 'UV-C Ultraviolet Radiation', ta: 'UV-C புற ஊதாக் கதிர்' }, icon: '☀️' },
          { id: 'opt-radio', label: { en: 'Radio Waves', ta: 'ரேடியோ அலைகள்' }, icon: '📻' },
          { id: 'opt-infra', label: { en: 'Infrared Heat', ta: 'அகச்சிவப்புக் கதிர்' }, icon: '🌡️' },
        ],
        correctOptionId: 'opt-uv',
      },
      {
        id: 's2',
        stageNumber: 2,
        title: { en: '2. DNA Base Pair Pairing', ta: '2. மரபணு கார இணை' },
        prompt: { en: 'Adenine (A) pairs with Thymine (T). Cytosine (C) pairs with:', ta: 'அடினைன் தயமினுடன் இணைகிறது. சைட்டோசின் எதனோடு இணையும்?' },
        hint: { en: 'C always pairs with Guanine (G).', ta: 'சைட்டோசின் எப்போதும் குவானைனுடன் இணையும்.' },
        options: [
          { id: 'opt-g', label: { en: 'Guanine (G)', ta: 'குவானைன் (G)' }, icon: '🧬' },
          { id: 'opt-u', label: { en: 'Uracil (U)', ta: 'யுராசில் (U)' }, icon: '🧬' },
          { id: 'opt-t', label: { en: 'Thymine (T)', ta: 'தயமின் (T)' }, icon: '🧬' },
        ],
        correctOptionId: 'opt-g',
      },
      {
        id: 's3',
        stageNumber: 3,
        title: { en: '3. Autoclave Pressure', ta: '3. ஆட்டோகிளேவ் அழுத்தம்' },
        prompt: { en: 'Standard medical autoclave operating pressure in PSI:', ta: 'நிலையான மருத்துவ ஆட்டோகிளேவ் இயக்க அழுத்தம்:' },
        hint: { en: '15 psi at 121 °C.', ta: '15 psi அழுத்தம் மற்றும் 121 °C.' },
        options: [
          { id: 'opt-15', label: { en: '15 PSI (121 °C)', ta: '15 PSI (121 °C)' }, icon: '⏲️' },
          { id: 'opt-5', label: { en: '5 PSI', ta: '5 PSI' }, icon: '⏲️' },
          { id: 'opt-50', label: { en: '50 PSI', ta: '50 PSI' }, icon: '⏲️' },
        ],
        correctOptionId: 'opt-15',
      },
    ],
  },
  {
    id: 'esc-05',
    name: 'Level 5: Space Station Reactor',
    theme: { en: 'Orbital Fusion Reactor', ta: 'விண்வெளி இணைவு உலை' },
    description: {
      en: 'Stabilize magnetic tokamak confinement, initiate Deuterium fuel injection, and unlock pod.',
      ta: 'காந்த வளையத்தை நிலைநிறுத்தி தப்பிக்கும் விண்கலத்திற்கு செல்லவும்.',
    },
    stages: [
      {
        id: 's1',
        stageNumber: 1,
        title: { en: '1. Fusion Fuel Isotope', ta: '1. இணைவு உலை எரிபொருள்' },
        prompt: { en: 'Which heavy hydrogen isotope with 1 proton and 1 neutron powers fusion?', ta: '1 புரோட்டான் மற்றும் 1 நியூட்ரான் கொண்ட கன ஹைட்ரஜன் ஐசோடோப் எது?' },
        hint: { en: 'Deuterium (²H).', ta: 'டியூட்டீரியம் (²H).' },
        options: [
          { id: 'opt-deut', label: { en: 'Deuterium (²H)', ta: 'டியூட்டீரியம் (²H)' }, icon: '⚛️' },
          { id: 'opt-prot', label: { en: 'Protium (¹H)', ta: 'புரோட்டியம் (¹H)' }, icon: '⚛️' },
          { id: 'opt-carb', label: { en: 'Carbon-12', ta: 'கார்பன்-12' }, icon: '⚛️' },
        ],
        correctOptionId: 'opt-deut',
      },
      {
        id: 's2',
        stageNumber: 2,
        title: { en: '2. Tokamak Confinement', ta: '2. டோகாமாக் காந்தப் புலம்' },
        prompt: { en: 'What state of matter is superheated inside the fusion tokamak?', ta: 'அணுக்கரு இணைவு உலையில் உள்ள நான்காம் நிலை பருப்பொருள் எது?' },
        hint: { en: 'Plasma (ionized gas).', ta: 'பிளாஸ்மா (அயனியாக்கப்பட்ட வாயு).' },
        options: [
          { id: 'opt-plasma', label: { en: 'Plasma', ta: 'பிளாஸ்மா' }, icon: '⚡' },
          { id: 'opt-liquid', label: { en: 'Liquid', ta: 'திரவம்' }, icon: '💧' },
          { id: 'opt-solid', label: { en: 'Solid', ta: 'திண்மம்' }, icon: '🧊' },
        ],
        correctOptionId: 'opt-plasma',
      },
      {
        id: 's3',
        stageNumber: 3,
        title: { en: '3. Escape Pod Ejection Vector', ta: '3. வெளியேற்று விசை திசைவேகம்' },
        prompt: { en: 'Earth escape velocity required to break free from orbit:', ta: 'பூமியின் ஈர்ப்பு விடுபடு வேகம்:' },
        hint: { en: 'Approximately 11.2 km/s.', ta: 'சுமார் 11.2 கி.மீ/விநாடி.' },
        options: [
          { id: 'opt-11k', label: { en: '11.2 km/s', ta: '11.2 கி.மீ/வி' }, icon: '🚀' },
          { id: 'opt-5k', label: { en: '5.0 km/s', ta: '5.0 கி.மீ/வி' }, icon: '🚀' },
          { id: 'opt-25k', label: { en: '25.0 km/s', ta: '25.0 கி.மீ/வி' }, icon: '🚀' },
        ],
        correctOptionId: 'opt-11k',
      },
    ],
  },
  {
    id: 'esc-06',
    name: 'Level 6: Quantum Computer Core',
    theme: { en: 'Quantum Supercomputer', ta: 'குவாண்டம் கணினி மையம்' },
    description: {
      en: 'Calibrate qubits, resolve superposition, and exit sub-basement.',
      ta: 'குவிட்களை சீரமைத்து குவாண்டம் கணினியிலிருந்து வெளியேறவும்.',
    },
    stages: [
      {
        id: 's1',
        stageNumber: 1,
        title: { en: '1. Basic Quantum Unit', ta: '1. குவாண்டம் அடிப்படை அலகு' },
        prompt: { en: 'What is the fundamental unit of quantum information called?', ta: 'குவாண்டம் தகவலின் அடிப்படை அலகு என்ன?' },
        hint: { en: 'Quantum bit -> Qubit.', ta: 'குவிட் (Qubit).' },
        options: [
          { id: 'opt-qubit', label: { en: 'Qubit', ta: 'குவிட் (Qubit)' }, icon: '💻' },
          { id: 'opt-byte', label: { en: 'Kilobyte', ta: 'கிலோபைட்' }, icon: '💾' },
          { id: 'opt-pixel', label: { en: 'Pixel', ta: 'பிக்சல்' }, icon: '🖼️' },
        ],
        correctOptionId: 'opt-qubit',
      },
      {
        id: 's2',
        stageNumber: 2,
        title: { en: '2. Superposition Principle', ta: '2. மேற்பொருந்துதல் தத்துவம்' },
        prompt: { en: 'In superposition, a qubit can exist as:', ta: 'மேற்பொருந்துதல் நிலையில் ஒரு குவிட் எவ்வாறு இருக்கும்?' },
        hint: { en: 'Both 0 and 1 simultaneously.', ta: '0 மற்றும் 1 ஆகிய இரண்டிலும் ஒரே நேரத்தில்.' },
        options: [
          { id: 'opt-both', label: { en: 'Both 0 and 1 Simultaneously', ta: '0 மற்றும் 1 ஒரே நேரத்தில்' }, icon: '✨' },
          { id: 'opt-only0', label: { en: 'Only 0 Forever', ta: '0 மட்டுமே' }, icon: '0️⃣' },
          { id: 'opt-only1', label: { en: 'Only 1 Forever', ta: '1 மட்டுமே' }, icon: '1️⃣' },
        ],
        correctOptionId: 'opt-both',
      },
      {
        id: 's3',
        stageNumber: 3,
        title: { en: '3. Planck Constant Power', ta: '3. பிளாங்க் மாறிலி குறியீடு' },
        prompt: { en: 'Select Planck constant h approximation power (10⁻³⁴ J·s):', ta: 'பிளாங்க் மாறிலி h-ன் அடுக்கு எண் (10⁻³⁴ J·s):' },
        hint: { en: 'Exponent is -34.', ta: 'அடுக்கு -34.' },
        options: [
          { id: 'opt-34', label: { en: '-34', ta: '-34' }, icon: '🔢' },
          { id: 'opt-23', label: { en: '-23', ta: '-23' }, icon: '🔢' },
          { id: 'opt-19', label: { en: '-19', ta: '-19' }, icon: '🔢' },
        ],
        correctOptionId: 'opt-34',
      },
    ],
  },
  {
    id: 'esc-07',
    name: 'Level 7: Hydroelectric Turbine Room',
    theme: { en: 'Hydraulic Powerhouse', ta: 'நீர் மின் உற்பத்தி நிலையம்' },
    description: {
      en: 'Open penstock valve, spin generator rotor, and synchronize power grid.',
      ta: 'வால்வை திறந்து மின்னாக்கியை இயக்கி கதவை திறக்கவும்.',
    },
    stages: [
      {
        id: 's1',
        stageNumber: 1,
        title: { en: '1. Energy Transformation', ta: '1. ஆற்றல் மாற்றம்' },
        prompt: { en: 'Hydroelectric dams convert gravitational potential energy into:', ta: 'அணைக்கட்டுகளில் நிலை ஆற்றல் எவ்வாறு மாற்றப்படுகிறது?' },
        hint: { en: 'Flowing water turns into kinetic energy.', ta: 'பாயும் நீரின் இயக்க ஆற்றலாக மாறுகிறது.' },
        options: [
          { id: 'opt-kinetic', label: { en: 'Kinetic Energy → Electrical Energy', ta: 'இயக்க ஆற்றல் → மின் ஆற்றல்' }, icon: '🌊' },
          { id: 'opt-nuclear', label: { en: 'Nuclear Energy', ta: 'அணுக்கரு ஆற்றல்' }, icon: '☢️' },
          { id: 'opt-chemical', label: { en: 'Chemical Energy', ta: 'வேதி ஆற்றல்' }, icon: '🧪' },
        ],
        correctOptionId: 'opt-kinetic',
      },
      {
        id: 's2',
        stageNumber: 2,
        title: { en: '2. Electromagnetic Induction Law', ta: '2. மின்காந்த தூண்டல் விதி' },
        prompt: { en: 'Whose law describes electromotive force induced by changing magnetic flux?', ta: 'மின்காந்த தூண்டல் விதியை கண்டறிந்த விஞ்ஞானி யார்?' },
        hint: { en: 'Michael Faraday.', ta: 'மைக்கேல் பாரடே.' },
        options: [
          { id: 'opt-faraday', label: { en: 'Faraday Law', ta: 'பாரடே விதி' }, icon: '🧲' },
          { id: 'opt-newton', label: { en: 'Newton Law', ta: 'நியூட்டன் விதி' }, icon: '🍎' },
          { id: 'opt-hooke', label: { en: 'Hooke Law', ta: 'ஹூக் விதி' }, icon: '➰' },
        ],
        correctOptionId: 'opt-faraday',
      },
      {
        id: 's3',
        stageNumber: 3,
        title: { en: '3. AC Grid Frequency', ta: '3. இந்திய மின் கட்டமைப்பு அதிர்வெண்' },
        prompt: { en: 'Standard AC power frequency in India (in Hertz):', ta: 'இந்தியாவின் நிலையான மின் கட்டமைப்பு அதிர்வெண்:' },
        hint: { en: '50 Hz.', ta: '50 ஹெர்ட்ஸ்.' },
        options: [
          { id: 'opt-50hz', label: { en: '50 Hz', ta: '50 Hz' }, icon: '⚡' },
          { id: 'opt-60hz', label: { en: '60 Hz', ta: '60 Hz' }, icon: '⚡' },
          { id: 'opt-100hz', label: { en: '100 Hz', ta: '100 Hz' }, icon: '⚡' },
        ],
        correctOptionId: 'opt-50hz',
      },
    ],
  },
  {
    id: 'esc-08',
    name: 'Level 8: Deep Space Telescope',
    theme: { en: 'Space Observatory Array', ta: 'விண்வெளி தொலைநோக்கி தளம்' },
    description: {
      en: 'Unfold solar array, orient sunshield, and transmit discovery data.',
      ta: 'சூரிய மின்தகட்டை விரித்து தரவுகளை பூமிக்கு அனுப்பி வெளியேறவும்.',
    },
    stages: [
      {
        id: 's1',
        stageNumber: 1,
        title: { en: '1. Primary Mirror Material', ta: '1. முதன்மை கண்ணாடி தனிமம்' },
        prompt: { en: 'The James Webb Space Telescope mirrors are coated with a micro-layer of:', ta: 'ஜேம்ஸ் வெப் தொலைநோக்கியின் கண்ணாடிகள் எதனால் பூசப்பட்டுள்ளன?' },
        hint: { en: 'Pure Gold (Au) for infrared reflection.', ta: 'அகச்சிவப்பு ஒளியை பிரதிபலிக்க தங்கம் (Au) பூசப்பட்டுள்ளது.' },
        options: [
          { id: 'opt-gold', label: { en: 'Gold (Au)', ta: 'தங்கம் (Au)' }, icon: '👑' },
          { id: 'opt-iron', label: { en: 'Iron (Fe)', ta: 'இரும்பு (Fe)' }, icon: '⚙️' },
          { id: 'opt-lead', label: { en: 'Lead (Pb)', ta: 'ஈயம் (Pb)' }, icon: '⚪' },
        ],
        correctOptionId: 'opt-gold',
      },
      {
        id: 's2',
        stageNumber: 2,
        title: { en: '2. Lagrange Point Orbit', ta: '2. லாக்ராஞ்சியன் புள்ளி' },
        prompt: { en: 'Which stable gravitational Lagrange point does JWST orbit (1.5M km from Earth)?', ta: 'பூமியிலிருந்து 15 லட்சம் கி.மீ தொலைவில் உள்ள லாக்ராஞ்சியன் புள்ளி எது?' },
        hint: { en: 'L2 (Lagrange Point 2).', ta: 'L2 (இரண்டாம் லாக்ராஞ்சியன் புள்ளி).' },
        options: [
          { id: 'opt-l2', label: { en: 'L2 (Lagrange Point 2)', ta: 'L2 புள்ளி' }, icon: '🛰️' },
          { id: 'opt-l1', label: { en: 'L1', ta: 'L1 புள்ளி' }, icon: '🛰️' },
          { id: 'opt-l4', label: { en: 'L4', ta: 'L4 புள்ளி' }, icon: '🛰️' },
        ],
        correctOptionId: 'opt-l2',
      },
      {
        id: 's3',
        stageNumber: 3,
        title: { en: '3. Redshift Doppler Code', ta: '3. சிவப்பு இடப்பெயர்ச்சி குறியீடு' },
        prompt: { en: 'Light from receding galaxies shifts toward longer wavelengths called:', ta: 'விலகிச் செல்லும் விண்மீன் திரள்களின் ஒளி நீள அலைவரிசையை நோக்கி நகர்வது:' },
        hint: { en: 'Redshift.', ta: 'சிவப்பு இடப்பெயர்ச்சி (Redshift).' },
        options: [
          { id: 'opt-redshift', label: { en: 'Redshift', ta: 'சிவப்பு இடப்பெயர்ச்சி' }, icon: '🔴' },
          { id: 'opt-blueshift', label: { en: 'Blueshift', ta: 'நீல இடப்பெயர்ச்சி' }, icon: '🔵' },
          { id: 'opt-greenshift', label: { en: 'Greenshift', ta: 'பச்சை இடப்பெயர்ச்சி' }, icon: '🟢' },
        ],
        correctOptionId: 'opt-redshift',
      },
    ],
  },
  {
    id: 'esc-09',
    name: 'Level 9: Volcano Geothermal Station',
    theme: { en: 'Magma Geothermal Lab', ta: 'எரிமலை புவிவெப்ப ஆய்வகம்' },
    description: {
      en: 'Monitor seismic activity, vent superheated steam, and escape magma chamber.',
      ta: 'நில அதிர்வை கண்காணித்து நீராவியை வெளியேற்றி தப்பிக்கவும்.',
    },
    stages: [
      {
        id: 's1',
        stageNumber: 1,
        title: { en: '1. Seismic Wave Velocity', ta: '1. நில அதிர்வு அலை' },
        prompt: { en: 'Which seismic waves travel fastest and arrive first at seismographs?', ta: 'நில அதிர்வின் போது மிக வேகமாக பயணிக்கும் முதன்மை அலைகள் எவை?' },
        hint: { en: 'Primary (P) compressional waves.', ta: 'முதன்மை (P) அலைகள்.' },
        options: [
          { id: 'opt-pwave', label: { en: 'P-Waves (Primary)', ta: 'P-அலைகள் (முதன்மை)' }, icon: '〰️' },
          { id: 'opt-swave', label: { en: 'S-Waves (Secondary)', ta: 'S-அலைகள்' }, icon: '〰️' },
          { id: 'opt-lwave', label: { en: 'Surface Waves', ta: 'மேற்பரப்பு அலைகள்' }, icon: '🌊' },
        ],
        correctOptionId: 'opt-pwave',
      },
      {
        id: 's2',
        stageNumber: 2,
        title: { en: '2. Volcanic Rock Type', ta: '2. எரிமலை பாறை வகை' },
        prompt: { en: 'Extrusive igneous rock formed from rapid lava cooling with dark glassy texture:', ta: 'எரிமலை குழம்பு விரைவாக குளிர்ந்து உருவாகும் அடர் நிற பாறை:' },
        hint: { en: 'Basalt or Obsidian.', ta: 'பசால்ட் அல்லது அப்சிடியன்.' },
        options: [
          { id: 'opt-obsidian', label: { en: 'Obsidian / Basalt', ta: 'அப்சிடியன் / பசால்ட்' }, icon: '🪨' },
          { id: 'opt-marble', label: { en: 'Marble', ta: 'பளிங்குக்கல்' }, icon: '⚪' },
          { id: 'opt-sandstone', label: { en: 'Sandstone', ta: 'மணற்கல்' }, icon: '🏜️' },
        ],
        correctOptionId: 'opt-obsidian',
      },
      {
        id: 's3',
        stageNumber: 3,
        title: { en: '3. Richter Scale Magnitude', ta: '3. ரிக்டர் அளவுகோல்' },
        prompt: { en: 'Each whole number increase on the Richter scale represents a 10-fold increase in:', ta: 'ரிக்டர் அளவில் 1 அலகு அதிகரிப்பது நில அதிர்வின் வீச்சில் எத்தனை மடங்கு பெருக்கம்?' },
        hint: { en: 'Wave Amplitude (10x).', ta: 'அலைவீச்சில் 10 மடங்கு பெருக்கம்.' },
        options: [
          { id: 'opt-10x', label: { en: '10× Amplitude', ta: '10 மடங்கு அலைவீச்சு' }, icon: '📈' },
          { id: 'opt-2x', label: { en: '2× Amplitude', ta: '2 மடங்கு' }, icon: '📈' },
          { id: 'opt-100x', label: { en: '100× Amplitude', ta: '100 மடங்கு' }, icon: '📈' },
        ],
        correctOptionId: 'opt-10x',
      },
    ],
  },
  {
    id: 'esc-10',
    name: 'Level 10: Master Escape Room',
    theme: { en: 'Grand Science Archive Vault', ta: 'முதன்மை அறிவியல் பெட்டகம்' },
    description: {
      en: 'Synthesize all science knowledge to solve the final 3-stage escape sequence.',
      ta: 'முழு அறிவியல் அறிவையும் பயன்படுத்தி இறுதி கதவைத் திறந்து தப்பிக்கவும்.',
    },
    stages: [
      {
        id: 's1',
        stageNumber: 1,
        title: { en: '1. DNA Blueprint Code', ta: '1. மரபணு குறியீடு' },
        prompt: { en: 'The double-helix molecular structure of DNA was discovered by:', ta: 'டி.என்.ஏ மூலக்கூறின் இரட்டை சுருள் அமைப்பைக் கண்டறிந்தவர்கள்:' },
        hint: { en: 'Watson and Crick (with Franklin).', ta: 'வாட்சன் மற்றும் கிரிக்.' },
        options: [
          { id: 'opt-watson', label: { en: 'Watson & Crick', ta: 'வாட்சன் & கிரிக்' }, icon: '🧬' },
          { id: 'opt-darwin', label: { en: 'Darwin & Wallace', ta: 'டார்வின் & வாலஸ்' }, icon: '🌴' },
          { id: 'opt-mendel', label: { en: 'Gregor Mendel', ta: 'கிரிகோர் மெண்டல்' }, icon: '🌱' },
        ],
        correctOptionId: 'opt-watson',
      },
      {
        id: 's2',
        stageNumber: 2,
        title: { en: '2. General Relativity Equation', ta: '2. ஐன்ஸ்டீன் சமன்பாடு' },
        prompt: { en: 'Mass-energy equivalence equation proposed by Albert Einstein:', ta: 'ஆல்பர்ட் ஐன்ஸ்டீனின் நிறை-ஆற்றல் சமன்பாடு:' },
        hint: { en: 'E = mc².', ta: 'E = mc².' },
        options: [
          { id: 'opt-emc2', label: { en: 'E = mc²', ta: 'E = mc²' }, icon: '⚡' },
          { id: 'opt-fma', label: { en: 'F = ma', ta: 'F = ma' }, icon: '🍎' },
          { id: 'opt-pvnr', label: { en: 'PV = nRT', ta: 'PV = nRT' }, icon: '♨️' },
        ],
        correctOptionId: 'opt-emc2',
      },
      {
        id: 's3',
        stageNumber: 3,
        title: { en: '3. Master Vault Unlock Key', ta: '3. முதன்மை கதவு சாவி' },
        prompt: { en: 'Number of naturally occurring chemical elements on Earth:', ta: 'பூமியில் இயற்கையாகக் கிடைக்கும் தனிமங்களின் எண்ணிக்கை:' },
        hint: { en: '92 (from Hydrogen to Uranium).', ta: '92 தனிமங்கள் (ஹைட்ரஜன் முதல் யுரேனியம் வரை).' },
        options: [
          { id: 'opt-92', label: { en: '92 Elements', ta: '92 தனிமங்கள்' }, icon: '🏆' },
          { id: 'opt-118', label: { en: '118 Elements (Total)', ta: '118 தனிமங்கள்' }, icon: '⚛️' },
          { id: 'opt-50', label: { en: '50 Elements', ta: '50 தனிமங்கள்' }, icon: '🧪' },
        ],
        correctOptionId: 'opt-92',
      },
    ],
  },
];
