import { MoleculeLevel } from './molecule-builder.types';

export const MOLECULE_LEVELS: MoleculeLevel[] = [
  {
    id: 'mol-01',
    name: 'Level 1: Water',
    targetFormula: 'H₂O',
    targetName: { en: 'Water', ta: 'நீர்' },
    description: { en: 'Essential for all known forms of life on Earth.', ta: 'பூமியில் உள்ள அனைத்து உயிரினங்களுக்கும் இன்றியமையாதது.' },
    requiredAtoms: { H: 2, O: 1 },
    availableAtoms: [
      { id: 'h1', symbol: 'H', name: { en: 'Hydrogen', ta: 'ஹைட்ரஜன்' }, valence: 1, color: '#3B82F6' },
      { id: 'h2', symbol: 'H', name: { en: 'Hydrogen', ta: 'ஹைட்ரஜன்' }, valence: 1, color: '#3B82F6' },
      { id: 'o1', symbol: 'O', name: { en: 'Oxygen', ta: 'ஆக்சிஜன்' }, valence: 2, color: '#EF4444' },
      { id: 'c1', symbol: 'C', name: { en: 'Carbon', ta: 'கார்பன்' }, valence: 4, color: '#334155' },
    ],
  },
  {
    id: 'mol-02',
    name: 'Level 2: Carbon Dioxide',
    targetFormula: 'CO₂',
    targetName: { en: 'Carbon Dioxide', ta: 'கார்பன் டை ஆக்சைடு' },
    description: { en: 'Gas utilized by plants during photosynthesis.', ta: 'தாவரங்கள் ஒளிச்சேர்க்கைக்கு பயன்படுத்தும் வாயு.' },
    requiredAtoms: { C: 1, O: 2 },
    availableAtoms: [
      { id: 'c1', symbol: 'C', name: { en: 'Carbon', ta: 'கார்பன்' }, valence: 4, color: '#334155' },
      { id: 'o1', symbol: 'O', name: { en: 'Oxygen', ta: 'ஆக்சிஜன்' }, valence: 2, color: '#EF4444' },
      { id: 'o2', symbol: 'O', name: { en: 'Oxygen', ta: 'ஆக்சிஜன்' }, valence: 2, color: '#EF4444' },
      { id: 'n1', symbol: 'N', name: { en: 'Nitrogen', ta: 'நைட்ரஜன்' }, valence: 3, color: '#10B981' },
    ],
  },
  {
    id: 'mol-03',
    name: 'Level 3: Table Salt',
    targetFormula: 'NaCl',
    targetName: { en: 'Sodium Chloride', ta: 'சோடியம் குளோரைடு' },
    description: { en: 'Everyday salt that gives seawater its salinity.', ta: 'நாம் அன்றாடம் பயன்படுத்தும் சமையல் உப்பு.' },
    requiredAtoms: { Na: 1, Cl: 1 },
    availableAtoms: [
      { id: 'na1', symbol: 'Na', name: { en: 'Sodium', ta: 'சோடியம்' }, valence: 1, color: '#F97316' },
      { id: 'cl1', symbol: 'Cl', name: { en: 'Chlorine', ta: 'குளோரின்' }, valence: 1, color: '#84CC16' },
      { id: 'k1', symbol: 'K', name: { en: 'Potassium', ta: 'பொட்டாசியம்' }, valence: 1, color: '#A855F7' },
      { id: 'h1', symbol: 'H', name: { en: 'Hydrogen', ta: 'ஹைட்ரஜன்' }, valence: 1, color: '#3B82F6' },
    ],
  },
  {
    id: 'mol-04',
    name: 'Level 4: Methane',
    targetFormula: 'CH₄',
    targetName: { en: 'Methane', ta: 'மீத்தேன்' },
    description: { en: 'The simplest alkane and main component of natural gas.', ta: 'இயற்கை எரிவாயுவின் முதன்மை அங்கமான எளிய ஹைட்ரோகார்பன்.' },
    requiredAtoms: { C: 1, H: 4 },
    availableAtoms: [
      { id: 'c1', symbol: 'C', name: { en: 'Carbon', ta: 'கார்பன்' }, valence: 4, color: '#334155' },
      { id: 'h1', symbol: 'H', name: { en: 'Hydrogen', ta: 'ஹைட்ரஜன்' }, valence: 1, color: '#3B82F6' },
      { id: 'h2', symbol: 'H', name: { en: 'Hydrogen', ta: 'ஹைட்ரஜன்' }, valence: 1, color: '#3B82F6' },
      { id: 'h3', symbol: 'H', name: { en: 'Hydrogen', ta: 'ஹைட்ரஜன்' }, valence: 1, color: '#3B82F6' },
      { id: 'h4', symbol: 'H', name: { en: 'Hydrogen', ta: 'ஹைட்ரஜன்' }, valence: 1, color: '#3B82F6' },
      { id: 'o1', symbol: 'O', name: { en: 'Oxygen', ta: 'ஆக்சிஜன்' }, valence: 2, color: '#EF4444' },
    ],
  },
  {
    id: 'mol-05',
    name: 'Level 5: Ammonia',
    targetFormula: 'NH₃',
    targetName: { en: 'Ammonia', ta: 'அம்மோனியா' },
    description: { en: 'Pungent gas vital for fertilizers and biochemistry.', ta: 'உரங்கள் தயாரிப்பில் பயன்படுத்தப்படும் நெடியுடைய வாயு.' },
    requiredAtoms: { N: 1, H: 3 },
    availableAtoms: [
      { id: 'n1', symbol: 'N', name: { en: 'Nitrogen', ta: 'நைட்ரஜன்' }, valence: 3, color: '#10B981' },
      { id: 'h1', symbol: 'H', name: { en: 'Hydrogen', ta: 'ஹைட்ரஜன்' }, valence: 1, color: '#3B82F6' },
      { id: 'h2', symbol: 'H', name: { en: 'Hydrogen', ta: 'ஹைட்ரஜன்' }, valence: 1, color: '#3B82F6' },
      { id: 'h3', symbol: 'H', name: { en: 'Hydrogen', ta: 'ஹைட்ரஜன்' }, valence: 1, color: '#3B82F6' },
      { id: 'c1', symbol: 'C', name: { en: 'Carbon', ta: 'கார்பன்' }, valence: 4, color: '#334155' },
    ],
  },
  {
    id: 'mol-06',
    name: 'Level 6: Oxygen Gas',
    targetFormula: 'O₂',
    targetName: { en: 'Diatomic Oxygen', ta: 'ஆக்சிஜன் வாயு' },
    description: { en: 'The gas we breathe to power cellular respiration.', ta: 'மனிதர்கள் மற்றும் விலங்குகள் சுவாசிக்கும் உயிர் வாயு.' },
    requiredAtoms: { O: 2 },
    availableAtoms: [
      { id: 'o1', symbol: 'O', name: { en: 'Oxygen', ta: 'ஆக்சிஜன்' }, valence: 2, color: '#EF4444' },
      { id: 'o2', symbol: 'O', name: { en: 'Oxygen', ta: 'ஆக்சிஜன்' }, valence: 2, color: '#EF4444' },
      { id: 'n1', symbol: 'N', name: { en: 'Nitrogen', ta: 'நைட்ரஜன்' }, valence: 3, color: '#10B981' },
      { id: 'h1', symbol: 'H', name: { en: 'Hydrogen', ta: 'ஹைட்ரஜன்' }, valence: 1, color: '#3B82F6' },
    ],
  },
  {
    id: 'mol-07',
    name: 'Level 7: Hydrochloric Acid',
    targetFormula: 'HCl',
    targetName: { en: 'Hydrogen Chloride', ta: 'ஹைட்ரோகுளோரிக் அமிலம்' },
    description: { en: 'Strong acid found in gastric juice that aids digestion.', ta: 'வயிற்றில் உணவு செரிமானத்திற்கு உதவும் வலிமையான அமிலம்.' },
    requiredAtoms: { H: 1, Cl: 1 },
    availableAtoms: [
      { id: 'h1', symbol: 'H', name: { en: 'Hydrogen', ta: 'ஹைட்ரஜன்' }, valence: 1, color: '#3B82F6' },
      { id: 'cl1', symbol: 'Cl', name: { en: 'Chlorine', ta: 'குளோரின்' }, valence: 1, color: '#84CC16' },
      { id: 'na1', symbol: 'Na', name: { en: 'Sodium', ta: 'சோடியம்' }, valence: 1, color: '#F97316' },
      { id: 'f1', symbol: 'F', name: { en: 'Fluorine', ta: 'புளூரின்' }, valence: 1, color: '#10B981' },
    ],
  },
  {
    id: 'mol-08',
    name: 'Level 8: Hydrogen Peroxide',
    targetFormula: 'H₂O₂',
    targetName: { en: 'Hydrogen Peroxide', ta: 'ஹைட்ரஜன் பெராக்சைடு' },
    description: { en: 'Powerful disinfectant and bleaching agent.', ta: 'கிருமிநாசினியாகப் பயன்படும் வேதிப்பொருள்.' },
    requiredAtoms: { H: 2, O: 2 },
    availableAtoms: [
      { id: 'h1', symbol: 'H', name: { en: 'Hydrogen', ta: 'ஹைட்ரஜன்' }, valence: 1, color: '#3B82F6' },
      { id: 'h2', symbol: 'H', name: { en: 'Hydrogen', ta: 'ஹைட்ரஜன்' }, valence: 1, color: '#3B82F6' },
      { id: 'o1', symbol: 'O', name: { en: 'Oxygen', ta: 'ஆக்சிஜன்' }, valence: 2, color: '#EF4444' },
      { id: 'o2', symbol: 'O', name: { en: 'Oxygen', ta: 'ஆக்சிஜன்' }, valence: 2, color: '#EF4444' },
      { id: 'c1', symbol: 'C', name: { en: 'Carbon', ta: 'கார்பன்' }, valence: 4, color: '#334155' },
    ],
  },
  {
    id: 'mol-09',
    name: 'Level 9: Nitrogen Dioxide',
    targetFormula: 'NO₂',
    targetName: { en: 'Nitrogen Dioxide', ta: 'நைட்ரஜன் டை ஆக்சைடு' },
    description: { en: 'Reddish-brown gas formed during combustion.', ta: 'எரிபொருள் எரிதலின் போது வெளியாகும் சிவப்பு-பழுப்பு வாயு.' },
    requiredAtoms: { N: 1, O: 2 },
    availableAtoms: [
      { id: 'n1', symbol: 'N', name: { en: 'Nitrogen', ta: 'நைட்ரஜன்' }, valence: 3, color: '#10B981' },
      { id: 'o1', symbol: 'O', name: { en: 'Oxygen', ta: 'ஆக்சிஜன்' }, valence: 2, color: '#EF4444' },
      { id: 'o2', symbol: 'O', name: { en: 'Oxygen', ta: 'ஆக்சிஜன்' }, valence: 2, color: '#EF4444' },
      { id: 'c1', symbol: 'C', name: { en: 'Carbon', ta: 'கார்பன்' }, valence: 4, color: '#334155' },
    ],
  },
  {
    id: 'mol-10',
    name: 'Level 10: Ozone',
    targetFormula: 'O₃',
    targetName: { en: 'Ozone', ta: 'ஓசோன்' },
    description: { en: 'Stratospheric gas shield protecting Earth from UV rays.', ta: 'புற ஊதாக் கதிர்களிலிருந்து பூமியைப் பாதுகாக்கும் வாயு.' },
    requiredAtoms: { O: 3 },
    availableAtoms: [
      { id: 'o1', symbol: 'O', name: { en: 'Oxygen', ta: 'ஆக்சிஜன்' }, valence: 2, color: '#EF4444' },
      { id: 'o2', symbol: 'O', name: { en: 'Oxygen', ta: 'ஆக்சிஜன்' }, valence: 2, color: '#EF4444' },
      { id: 'o3', symbol: 'O', name: { en: 'Oxygen', ta: 'ஆக்சிஜன்' }, valence: 2, color: '#EF4444' },
      { id: 'h1', symbol: 'H', name: { en: 'Hydrogen', ta: 'ஹைட்ரஜன்' }, valence: 1, color: '#3B82F6' },
    ],
  },
];

export const MOLECULE_BUILDER_LEVELS = MOLECULE_LEVELS;

