import { TimeMachineLevel } from './time-machine.types';

export const TIME_MACHINE_LEVELS: TimeMachineLevel[] = [
  {
    id: 'time-01',
    name: 'Level 1: Classical Physics',
    era: { en: '17th to 20th Century', ta: '17 முதல் 20 ஆம் நூற்றாண்டு' },
    events: [
      {
        id: 'ev-gravity',
        year: 1687,
        yearDisplay: '1687 CE',
        title: { en: 'Universal Law of Gravitation', ta: 'புவியீர்ப்பு விதி' },
        scientist: { en: 'Isaac Newton', ta: 'ஐசக் நியூட்டன்' },
        description: { en: 'Published in Philosophiæ Naturalis Principia Mathematica.', ta: 'பிரின்சிபியா நூலில் வெளியிடப்பட்டது.' },
        icon: '🍎',
      },
      {
        id: 'ev-lightbulb',
        year: 1879,
        yearDisplay: '1879 CE',
        title: { en: 'Long-Lasting Incandescent Bulb', ta: 'மின்விளக்கு கண்டுபிடிப்பு' },
        scientist: { en: 'Thomas Edison', ta: 'தாமஸ் எடிசன்' },
        description: { en: 'Carbon filament light bulb demonstrated.', ta: 'மின்விளக்கு செயல்விளக்கம்.' },
        icon: '💡',
      },
      {
        id: 'ev-relativity',
        year: 1905,
        yearDisplay: '1905 CE',
        title: { en: 'Special Theory of Relativity', ta: 'சிறப்பு சார்பியல் கோட்பாடு' },
        scientist: { en: 'Albert Einstein', ta: 'ஆல்பர்ட் ஐன்ஸ்டீன்' },
        description: { en: 'Annus Mirabilis papers including E = mc².', ta: 'E = mc² சமன்பாடு அறிமுகம்.' },
        icon: '⚡',
      },
      {
        id: 'ev-moon',
        year: 1969,
        yearDisplay: '1969 CE',
        title: { en: 'Apollo 11 Moon Landing', ta: 'நிலவில் மனிதன் தடம்' },
        scientist: { en: 'Neil Armstrong (NASA)', ta: 'நீல் ஆம்ஸ்ட்ராங்' },
        description: { en: 'First humans land on lunar surface.', ta: 'மனிதன் முதல்முறையாக நிலவில் கால்வைத்தார்.' },
        icon: '🌕',
      },
    ],
  },
  {
    id: 'time-02',
    name: 'Level 2: Medical Discoveries',
    era: { en: 'History of Medicine', ta: 'மருத்துவ வரலாறு' },
    events: [
      {
        id: 'ev-circ',
        year: 1628,
        yearDisplay: '1628 CE',
        title: { en: 'Blood Circulation Discovered', ta: 'இரத்த ஓட்டம் கண்டறிதல்' },
        scientist: { en: 'William Harvey', ta: 'வில்லியம் ஹார்வி' },
        description: { en: 'Proved blood is pumped by the heart in a closed loop.', ta: 'இதயம் இரத்தத்தை செலுத்தும் முறை நிரூபணம்.' },
        icon: '❤️',
      },
      {
        id: 'ev-smallpox',
        year: 1796,
        yearDisplay: '1796 CE',
        title: { en: 'First Vaccine (Smallpox)', ta: 'முதல் பெரியம்மை தடுப்பூசி' },
        scientist: { en: 'Edward Jenner', ta: 'எட்வர்ட் ஜென்னர்' },
        description: { en: 'Used cowpox virus to inoculate against smallpox.', ta: 'தடுப்பூசி மருத்துவத்தின் தொடக்கம்.' },
        icon: '💉',
      },
      {
        id: 'ev-penicillin',
        year: 1928,
        yearDisplay: '1928 CE',
        title: { en: 'Discovery of Penicillin', ta: 'பென்சிலின் கண்டுபிடிப்பு' },
        scientist: { en: 'Alexander Fleming', ta: 'அலெக்சாண்டர் பிளெமிங்' },
        description: { en: 'First modern antibiotic from Penicillium mould.', ta: 'முதல் நவீன நுண்ணுயிர்க்கொல்லி மருந்து.' },
        icon: '🧫',
      },
      {
        id: 'ev-polio',
        year: 1953,
        yearDisplay: '1953 CE',
        title: { en: 'Polio Vaccine Developed', ta: 'போலியோ தடுப்பு மருந்து' },
        scientist: { en: 'Jonas Salk', ta: 'ஜோனாஸ் சால்க்' },
        description: { en: 'Inactivated polio vaccine saves millions of children.', ta: 'இளம்பிள்ளை வாத தடுப்பூசி.' },
        icon: '🧒',
      },
    ],
  },
  {
    id: 'time-03',
    name: 'Level 3: Space Exploration',
    era: { en: 'Space Age', ta: 'விண்வெளி யுகம்' },
    events: [
      {
        id: 'ev-sputnik',
        year: 1957,
        yearDisplay: '1957 CE',
        title: { en: 'Sputnik 1 Launch', ta: 'ஸ்புட்னிக் 1 விண்கலம்' },
        scientist: { en: 'Sergei Korolev (USSR)', ta: 'சோவியத் யூனியன்' },
        description: { en: 'First artificial satellite in Earth orbit.', ta: 'விண்ணில் செலுத்தப்பட்ட முதல் செயற்கைக்கோள்.' },
        icon: '🛰️',
      },
      {
        id: 'ev-gagarin',
        year: 1961,
        yearDisplay: '1961 CE',
        title: { en: 'First Human in Space', ta: 'விண்வெளி சென்ற முதல் மனிதர்' },
        scientist: { en: 'Yuri Gagarin', ta: 'யூரி ககாரின்' },
        description: { en: 'Completed one orbit aboard Vostok 1.', ta: 'வோஸ்டாக் 1 மூலம் பூமியை வலம் வந்தார்.' },
        icon: '👨‍🚀',
      },
      {
        id: 'ev-hubble',
        year: 1990,
        yearDisplay: '1990 CE',
        title: { en: 'Hubble Space Telescope', ta: 'ஹப்பிள் தொலைநோக்கி' },
        scientist: { en: 'NASA / ESA', ta: 'நாசா & ஐரோப்பிய விண்வெளி நிறுவனம்' },
        description: { en: 'Deployed into low Earth orbit by Space Shuttle.', ta: 'விண்ணில் நிலைநிறுத்தப்பட்ட தொலைநோக்கி.' },
        icon: '🔭',
      },
      {
        id: 'ev-mars-rover',
        year: 2021,
        yearDisplay: '2021 CE',
        title: { en: 'Perseverance Rover Lands on Mars', ta: 'பெர்சிவரன்ஸ் ரோவர் தரை இறக்கம்' },
        scientist: { en: 'NASA JPL', ta: 'நாசா ஜெட் உந்துவிசை ஆய்வகம்' },
        description: { en: 'Seeking signs of ancient microbial life in Jezero Crater.', ta: 'செவ்வாய் கிரகத்தில் பழங்கால நுண்ணுயிர் தேடல்.' },
        icon: '🤖',
      },
    ],
  },
  {
    id: 'time-04',
    name: 'Level 4: Chemistry Evolution',
    era: { en: 'Chemical Sciences', ta: 'வேதியியல் வளர்ச்சி' },
    events: [
      {
        id: 'ev-oxygen',
        year: 1774,
        yearDisplay: '1774 CE',
        title: { en: 'Isolation of Oxygen Gas', ta: 'ஆக்சிஜன் வாயு கண்டறிதல்' },
        scientist: { en: 'Joseph Priestley & Lavoisier', ta: 'ஜோசப் பிரீஸ்ட்லி' },
        description: { en: 'Named and identified as the gas essential for combustion.', ta: 'எரிதலுக்கு காரணமான வாயு என அடையாளம் காணப்பட்டது.' },
        icon: '🫧',
      },
      {
        id: 'ev-dalton',
        year: 1803,
        yearDisplay: '1803 CE',
        title: { en: 'Atomic Theory Proposed', ta: 'அணு கோட்பாடு' },
        scientist: { en: 'John Dalton', ta: 'ஜான் டால்டன்' },
        description: { en: 'Proposed all matter consists of indivisible atoms.', ta: 'பருப்பொருள் அணுக்களால் ஆனது என்ற கோட்பாடு.' },
        icon: '⚛️',
      },
      {
        id: 'ev-mendeleev',
        year: 1869,
        yearDisplay: '1869 CE',
        title: { en: 'Periodic Table of Elements', ta: 'தனிம வரிசை அட்டவணை' },
        scientist: { en: 'Dmitri Mendeleev', ta: 'டிமிட்ரி மெண்டலீவ்' },
        description: { en: 'Organized elements by atomic mass and predicted new ones.', ta: 'தனிமங்களின் பண்புகளை அட்டவணைப்படுத்தினார்.' },
        icon: '📊',
      },
      {
        id: 'ev-radium',
        year: 1898,
        yearDisplay: '1898 CE',
        title: { en: 'Discovery of Radium & Polonium', ta: 'ரேடியம் கண்டுபிடிப்பு' },
        scientist: { en: 'Marie & Pierre Curie', ta: 'மேரி கியூரி & பியர் கியூரி' },
        description: { en: 'Pioneered the study of radioactivity.', ta: 'கதிரியக்க தனிமங்களை பிரித்தெடுத்தனர்.' },
        icon: '✨',
      },
    ],
  },
  {
    id: 'time-05',
    name: 'Level 5: Computing Revolution',
    era: { en: 'Information Age', ta: 'தகவல் தொழில்நுட்ப யுகம்' },
    events: [
      {
        id: 'ev-analytical',
        year: 1837,
        yearDisplay: '1837 CE',
        title: { en: 'Analytical Engine Concept', ta: 'பகுப்பாய்வு பொறி வடிவமைப்பு' },
        scientist: { en: 'Charles Babbage & Ada Lovelace', ta: 'சார்லஸ் பாபேஜ் & அடா லவ்லேஸ்' },
        description: { en: 'First mechanical general-purpose computer design.', ta: 'முதல் மெக்கானிக்கல் கணினி கோட்பாடு.' },
        icon: '⚙️',
      },
      {
        id: 'ev-turing',
        year: 1936,
        yearDisplay: '1936 CE',
        title: { en: 'Universal Turing Machine', ta: 'டூரிங் கணினி மாதிரி' },
        scientist: { en: 'Alan Turing', ta: 'ஆலன் டூரிங்' },
        description: { en: 'Theoretical foundation of modern computer science.', ta: 'நவீன கணினி அறிவியலின் அடித்தளம்.' },
        icon: '🧮',
      },
      {
        id: 'ev-transistor',
        year: 1947,
        yearDisplay: '1947 CE',
        title: { en: 'Invention of the Transistor', ta: 'டிரான்சிஸ்டர் கண்டுபிடிப்பு' },
        scientist: { en: 'Bardeen, Brattain & Shockley', ta: 'பெல் லேப்ஸ்' },
        description: { en: 'Solid-state electronic amplifier replacing vacuum tubes.', ta: 'நவீன மின்னணுவியல் புரட்சி.' },
        icon: '🔌',
      },
      {
        id: 'ev-internet',
        year: 1989,
        yearDisplay: '1989 CE',
        title: { en: 'World Wide Web Invented', ta: 'இணைய வலைப்பின்னல் (WWW)' },
        scientist: { en: 'Tim Berners-Lee', ta: 'டிம் பெர்னர்ஸ்-லீ' },
        description: { en: 'Created HTML, HTTP and the global web at CERN.', ta: 'செர்ன் ஆய்வகத்தில் இணையதளம் உருவாக்கம்.' },
        icon: '🌐',
      },
    ],
  },
  {
    id: 'time-06',
    name: 'Level 6: Genetics & DNA',
    era: { en: 'Biological Revolution', ta: 'உயிரியல் புரட்சி' },
    events: [
      {
        id: 'ev-mendel',
        year: 1865,
        yearDisplay: '1865 CE',
        title: { en: 'Laws of Genetic Inheritance', ta: 'மரபியல் விதிகள்' },
        scientist: { en: 'Gregor Mendel', ta: 'கிரிகோர் மெண்டல்' },
        description: { en: 'Pea plant experiments establishing dominant and recessive traits.', ta: 'பட்டாணி செடி சோதனைகள் மூலம் மரபு விதிகள்.' },
        icon: '🌱',
      },
      {
        id: 'ev-dna-structure',
        year: 1953,
        yearDisplay: '1953 CE',
        title: { en: 'DNA Double Helix Structure', ta: 'டி.என்.ஏ இரட்டை சுருள் மாதிரி' },
        scientist: { en: 'Watson, Crick & Franklin', ta: 'வாட்சன் & கிரிக்' },
        description: { en: 'Discovered the molecular ladder carrying genetic code.', ta: 'மரபணு மூலக்கூறின் கட்டமைப்பு.' },
        icon: '🧬',
      },
      {
        id: 'ev-dolly',
        year: 1996,
        yearDisplay: '1996 CE',
        title: { en: 'Dolly the Sheep Cloned', ta: 'டாலி ஆடு குளோனிங்' },
        scientist: { en: 'Ian Wilmut (Roslin Institute)', ta: 'ரோஸ்லின் நிறுவனம்' },
        description: { en: 'First mammal cloned from an adult somatic cell.', ta: 'முழு உயிரணுவில் இருந்து உருவாக்கப்பட்ட முதல் விலங்கு.' },
        icon: '🐑',
      },
      {
        id: 'ev-crispr',
        year: 2012,
        yearDisplay: '2012 CE',
        title: { en: 'CRISPR-Cas9 Gene Editing', ta: 'CRISPR மரபணு மாற்ற முறை' },
        scientist: { en: 'Doudna & Charpentier', ta: 'டவுட்னா & சார்பெண்டியர்' },
        description: { en: 'Precision molecular scissors for editing genetic code.', ta: 'துல்லியமான மரபணு திருத்தும் தொழில்நுட்பம்.' },
        icon: '✂️',
      },
    ],
  },
  {
    id: 'time-07',
    name: 'Level 7: Electricity & Magnetism',
    era: { en: 'Electromagnetism', ta: 'மின்காந்தவியல்' },
    events: [
      {
        id: 'ev-volta',
        year: 1800,
        yearDisplay: '1800 CE',
        title: { en: 'Voltaic Pile (First Battery)', ta: 'முதல் மின்கலம்' },
        scientist: { en: 'Alessandro Volta', ta: 'அலெசாண்ட்ரோ வோல்டா' },
        description: { en: 'First chemical electrical battery providing continuous current.', ta: 'தொடர் மின்னோட்டத்தை தரும் முதல் சாதனம்.' },
        icon: '🔋',
      },
      {
        id: 'ev-oersted',
        year: 1820,
        yearDisplay: '1820 CE',
        title: { en: 'Electromagnetism Discovered', ta: 'மின்னோட்டத்தின் காந்த விளைவு' },
        scientist: { en: 'Hans Christian Ørsted', ta: 'ஹான்ஸ் கிறிஸ்டியன் ஆர்ஸ்டெட்' },
        description: { en: 'Observed electric currents deflect compass needles.', ta: 'மின்னோட்டம் காந்த ஊசியை நகர்த்துவதை கண்டறிந்தார்.' },
        icon: '🧭',
      },
      {
        id: 'ev-induction',
        year: 1831,
        yearDisplay: '1831 CE',
        title: { en: 'Electromagnetic Induction', ta: 'மின்காந்த தூண்டல்' },
        scientist: { en: 'Michael Faraday', ta: 'மைக்கேல் பாரடே' },
        description: { en: 'Moving magnets generate electric current in wires.', ta: 'இயங்கும் காந்தம் மின்னோட்டத்தை உருவாக்குகிறது.' },
        icon: '🧲',
      },
      {
        id: 'ev-maxwell',
        year: 1865,
        yearDisplay: '1865 CE',
        title: { en: 'Maxwell Equations of Light', ta: 'மேக்ஸ்வெல் சமன்பாடுகள்' },
        scientist: { en: 'James Clerk Maxwell', ta: 'ஜேம்ஸ் கிளார்க் மேக்ஸ்வெல்' },
        description: { en: 'Unified electricity, magnetism and light into one theory.', ta: 'மின்சாரம், காந்தம் மற்றும் ஒளியை ஒருங்கிணைத்தார்.' },
        icon: '🌈',
      },
    ],
  },
  {
    id: 'time-08',
    name: 'Level 8: Evolutionary Biology',
    era: { en: 'Natural Sciences', ta: 'இயற்கை அறிவியல்' },
    events: [
      {
        id: 'ev-linnaeus',
        year: 1735,
        yearDisplay: '1735 CE',
        title: { en: 'Binomial Nomenclature Taxonomy', ta: 'இருபெயர் பெயரிடும் முறை' },
        scientist: { en: 'Carl Linnaeus', ta: 'கார்ல் லின்னேயஸ்' },
        description: { en: 'Systema Naturae classifying species by Genus and Species.', ta: 'உயிரினங்களுக்கு இருபெயர் முறை அறிமுகம்.' },
        icon: '📖',
      },
      {
        id: 'ev-darwin',
        year: 1859,
        yearDisplay: '1859 CE',
        title: { en: 'On the Origin of Species', ta: 'உயிரினங்களின் தோற்றம்' },
        scientist: { en: 'Charles Darwin', ta: 'சார்லஸ் டார்வின்' },
        description: { en: 'Natural selection as the driving mechanism of evolution.', ta: 'இயற்கை தேர்வு மூலம் பரிணாம வளர்ச்சி.' },
        icon: '🐒',
      },
      {
        id: 'ev-lucy',
        year: 1974,
        yearDisplay: '1974 CE',
        title: { en: 'Lucy Fossil Discovered', ta: 'லூசி மனித புதைபடிவம்' },
        scientist: { en: 'Donald Johanson', ta: 'டொனால்ட் ஜோஹன்சன்' },
        description: { en: '3.2 million-year-old Australopithecus afarensis skeleton.', ta: '32 லட்சம் ஆண்டுகள் பழமையான மனித மூதாதையர் எலும்புக்கூடு.' },
        icon: '🦴',
      },
      {
        id: 'ev-human-genome',
        year: 2003,
        yearDisplay: '2003 CE',
        title: { en: 'Human Genome Project Complete', ta: 'மனித மரபணு வரைபடம் நிறைவு' },
        scientist: { en: 'International Consortium', ta: 'சர்வதேச விஞ்ஞானிகள்' },
        description: { en: 'Sequenced all 3 billion base pairs of human DNA.', ta: 'மனிதனின் 300 கோடி மரபணு கார இணைகள் வரிசைப்படுத்தப்பட்டன.' },
        icon: '🗺️',
      },
    ],
  },
  {
    id: 'time-09',
    name: 'Level 9: Atomic Age',
    era: { en: 'Nuclear Physics', ta: 'அணுக்கரு இயற்பியல்' },
    events: [
      {
        id: 'ev-electron',
        year: 1897,
        yearDisplay: '1897 CE',
        title: { en: 'Discovery of the Electron', ta: 'எலக்ட்ரான் கண்டுபிடிப்பு' },
        scientist: { en: 'J.J. Thomson', ta: 'ஜே.ஜே. தாம்சன்' },
        description: { en: 'Identified negatively charged subatomic particles.', ta: 'எதிர்மின்சுமை கொண்ட துகள் கண்டறிதல்.' },
        icon: '⚡',
      },
      {
        id: 'ev-nucleus',
        year: 1911,
        yearDisplay: '1911 CE',
        title: { en: 'Atomic Nucleus Discovered', ta: 'அணு உட்கரு கண்டறிதல்' },
        scientist: { en: 'Ernest Rutherford', ta: 'எர்னஸ்ட் ரூதர்போர்டு' },
        description: { en: 'Gold foil experiment revealed dense central positive core.', ta: 'தங்கத்தகடு சோதனையின் மூலம் உட்கரு நிரூபணம்.' },
        icon: '🎯',
      },
      {
        id: 'ev-neutron',
        year: 1932,
        yearDisplay: '1932 CE',
        title: { en: 'Discovery of the Neutron', ta: 'நியூட்ரானைக் கண்டறிதல்' },
        scientist: { en: 'James Chadwick', ta: 'ஜேம்ஸ் சாட்விக்' },
        description: { en: 'Uncharged nuclear particle with mass equal to a proton.', ta: 'மின்சுமையற்ற உட்கரு துகள்.' },
        icon: '⚪',
      },
      {
        id: 'ev-fission',
        year: 1938,
        yearDisplay: '1938 CE',
        title: { en: 'Nuclear Fission Discovered', ta: 'அணுக்கரு பிளவு கண்டுபிடிப்பு' },
        scientist: { en: 'Otto Hahn & Lise Meitner', ta: 'ஓட்டோ ஹான் & லிஸ் மைட்னர்' },
        description: { en: 'Splitting of Uranium nuclei releasing tremendous energy.', ta: 'யுரேனிய அணுவை பிளந்து அபரிமித ஆற்றல் பெறுதல்.' },
        icon: '💥',
      },
    ],
  },
  {
    id: 'time-10',
    name: 'Level 10: Indian Science Milestones',
    era: { en: 'Pioneers of India', ta: 'இந்திய அறிவியல் மைல்கற்கள்' },
    events: [
      {
        id: 'ev-bose',
        year: 1895,
        yearDisplay: '1895 CE',
        title: { en: 'Millimetre Microwave Radio', ta: 'மில்லிமீட்டர் மைக்ரோவேவ் ரேடியோ' },
        scientist: { en: 'Jagadish Chandra Bose', ta: 'ஜெ.சி. போஸ்' },
        description: { en: 'Pioneered wireless communications and crescograph.', ta: 'கம்பியில்லா தகவல் தொடர்பு முன்னோடி.' },
        icon: '📡',
      },
      {
        id: 'ev-raman',
        year: 1928,
        yearDisplay: '1928 CE',
        title: { en: 'Raman Effect Discovered', ta: 'ராமன் விளைவு கண்டுபிடிப்பு' },
        scientist: { en: 'Sir C.V. Raman', ta: 'சர் சி.வி. ராமன்' },
        description: { en: 'Inelastic scattering of photons earning Nobel Prize 1930.', ta: 'ஒளிச்சிதறல் ஆய்வுக்காக நோபல் பரிசு.' },
        icon: '💎',
      },
      {
        id: 'ev-aryabhata',
        year: 1975,
        yearDisplay: '1975 CE',
        title: { en: 'Aryabhata Satellite Launched', ta: 'ஆர்யபட்டா செயற்கைக்கோள்' },
        scientist: { en: 'ISRO (Prof. U.R. Rao)', ta: 'இஸ்ரோ' },
        description: { en: 'Indias first indigenous satellite launched into orbit.', ta: 'இந்தியாவின் முதல் செயற்கைக்கோள்.' },
        icon: '🛰️',
      },
      {
        id: 'ev-chandrayaan',
        year: 2023,
        yearDisplay: '2023 CE',
        title: { en: 'Chandrayaan-3 South Pole Landing', ta: 'சந்திரயான்-3 தென் துருவத்தில் தடம்' },
        scientist: { en: 'ISRO Team (S. Somanath)', ta: 'இஸ்ரோ குழு' },
        description: { en: 'First nation to softly land on the Moons south pole.', ta: 'நிலவின் தென் துருவத்தில் தரையிறங்கிய முதல் நாடு.' },
        icon: '🚀',
      },
    ],
  },
];
