/**
 * Settings Search Metadata & Filter Utility
 * Provides fast local search filtering across all setting options.
 */

import { SettingsSearchItem } from './settings.types';
import { SupportedLanguage } from '../../config/i18n';

export function getSearchItems(language: SupportedLanguage = 'en'): SettingsSearchItem[] {
  const isTamil = language === 'ta';

  return [
    {
      id: 'profile',
      section: isTamil ? 'கணக்கு' : 'Account',
      title: isTamil ? 'மாணவர் சுயவிவரம்' : 'Student Profile',
      subtitle: isTamil ? 'சுயவிவரத்தைக் காண்க மற்றும் திருத்துங்கள்' : 'View and edit your student profile',
      keywords: ['profile', 'name', 'school', 'grade', 'சுயவிவரம்', 'பெயர்', 'பள்ளி', 'வகுப்பு'],
      icon: '👤',
      actionType: 'navigate',
      targetRoute: '/profile',
    },
    {
      id: 'language',
      section: isTamil ? 'விருப்பத்தேர்வுகள்' : 'Preferences',
      title: isTamil ? 'பயன்பாட்டு மொழி' : 'Language',
      subtitle: isTamil ? 'தமிழ் / English' : 'English / தமிழ்',
      keywords: ['language', 'tamil', 'english', 'தமிழ்', 'ஆங்கிலம்', 'மொழி', 'மொழிபெயர்ப்பு'],
      icon: '🌐',
      actionType: 'navigate',
      targetRoute: '/language',
    },
    {
      id: 'theme',
      section: isTamil ? 'விருப்பத்தேர்வுகள்' : 'Preferences',
      title: isTamil ? 'தோற்றம் / தீம்' : 'Theme',
      subtitle: isTamil ? 'கணினி இயல்பு / வெளிர் / இருண்ட' : 'System / Light / Dark',
      keywords: ['theme', 'dark mode', 'light mode', 'appearance', 'தோற்றம்', 'தீம்', 'இருண்ட'],
      icon: '◐',
      actionType: 'modal',
      modalType: 'theme',
    },
    {
      id: 'textScale',
      section: isTamil ? 'விருப்பத்தேர்வுகள்' : 'Preferences',
      title: isTamil ? 'எழுத்து அளவு' : 'Text Size',
      subtitle: isTamil ? 'சிறிய / இயல்பு / பெரிய / மிக பெரிய' : 'Small / Default / Large / Extra Large',
      keywords: ['text', 'size', 'font', 'scale', 'typography', 'எழுத்து', 'அளவு', 'எழுத்துரு'],
      icon: '🔤',
      actionType: 'modal',
      modalType: 'textScale',
    },
    {
      id: 'reduceMotion',
      section: isTamil ? 'அணுகல்தன்மை' : 'Accessibility',
      title: isTamil ? 'இயக்கத்தைக் குறைத்தல்' : 'Reduce Motion',
      subtitle: isTamil ? 'அசைவூட்டங்களைக் குறைக்கிறது' : 'Reduces UI animations',
      keywords: ['motion', 'animation', 'accessibility', 'இயக்கம்', 'அசைவூட்டம்', 'அணுகல்தன்மை'],
      icon: '⚡',
      actionType: 'toggle',
      targetKey: 'reduceMotion',
    },
    {
      id: 'dailyChallengeNotif',
      section: isTamil ? 'அறிவிப்புகள்' : 'Notifications',
      title: isTamil ? 'தினசரி அறிவியல் சவால்' : 'Daily Science Challenge',
      subtitle: isTamil ? 'தினசரி சிந்தனை வினா நினைவூட்டல்' : 'Daily question reminder',
      keywords: ['notification', 'challenge', 'daily', 'science', 'அறிவிப்பு', 'சவால்', 'தினசரி'],
      icon: '🔔',
      actionType: 'toggle',
      targetKey: 'dailyChallengeNotifications',
    },
    {
      id: 'quizReminders',
      section: isTamil ? 'அறிவிப்புகள்' : 'Notifications',
      title: isTamil ? 'வினாடி வினா நினைவூட்டல்கள்' : 'Quiz Reminders',
      subtitle: isTamil ? 'வழக்கமான வினாடி வினா விழிப்பூட்டல்கள்' : 'Periodic quiz practice reminders',
      keywords: ['quiz', 'reminders', 'alerts', 'practice', 'வினாடி வினா', 'நினைவூட்டல்'],
      icon: '⏰',
      actionType: 'toggle',
      targetKey: 'quizReminders',
    },
    {
      id: 'streakReminders',
      section: isTamil ? 'அறிவிப்புகள்' : 'Notifications',
      title: isTamil ? 'தொடர் கற்றல் நினைவூட்டல்கள்' : 'Streak Reminders',
      subtitle: isTamil ? 'கற்றல் தொடரைத் தக்கவைக்கவும்' : 'Maintain your learning streak',
      keywords: ['streak', 'flame', 'streak reminders', 'தொடர்', 'தொடர்ச்சி'],
      icon: '🔥',
      actionType: 'toggle',
      targetKey: 'streakReminders',
    },
    {
      id: 'preferredSubject',
      section: isTamil ? 'கற்றல் விருப்பங்கள்' : 'Learning Preferences',
      title: isTamil ? 'விருப்பமான பாடம்' : 'Preferred Subject',
      subtitle: isTamil ? 'இயற்பியல் / வேதியியல் / உயிரியல்' : 'Physics / Chemistry / Biology',
      keywords: ['subject', 'physics', 'chemistry', 'biology', 'பாடம்', 'இயற்பியல்', 'வேதியியல்', 'உயிரியல்'],
      icon: '📚',
      actionType: 'modal',
      modalType: 'preferredSubject',
    },
    {
      id: 'dailyLearningGoal',
      section: isTamil ? 'கற்றல் விருப்பங்கள்' : 'Learning Preferences',
      title: isTamil ? 'தினசரி கற்றல் இலக்கு' : 'Daily Learning Goal',
      subtitle: isTamil ? '5 – 30 நிமிடங்கள்' : '5 – 30 minutes',
      keywords: ['goal', 'target', 'daily minutes', 'study time', 'இலக்கு', 'நேரம்', 'நிமிடம்'],
      icon: '🎯',
      actionType: 'modal',
      modalType: 'dailyLearningGoal',
    },
    {
      id: 'difficulty',
      section: isTamil ? 'கற்றல் விருப்பங்கள்' : 'Learning Preferences',
      title: isTamil ? 'கடினத்தன்மை நிலை' : 'Difficulty Level',
      subtitle: isTamil ? 'தொடக்க நிலை / இடைநிலை / உயர்நிலை' : 'Beginner / Intermediate / Advanced',
      keywords: ['difficulty', 'level', 'beginner', 'advanced', 'கடினத்தன்மை', 'நிலை'],
      icon: '📊',
      actionType: 'modal',
      modalType: 'difficulty',
    },
    {
      id: 'questionsPerQuiz',
      section: isTamil ? 'வினாடி வினா விருப்பங்கள்' : 'Quiz Preferences',
      title: isTamil ? 'வினாடி வினாவிற்கு கேள்விகள்' : 'Questions per Quiz',
      subtitle: isTamil ? '5, 10, 15, 20 அல்லது 30 கேள்விகள்' : '5, 10, 15, 20 or 30 questions',
      keywords: ['questions', 'count', 'quiz length', 'கேள்வி', 'எண்ணிக்கை'],
      icon: '❓',
      actionType: 'modal',
      modalType: 'questionsPerQuiz',
    },
    {
      id: 'quizTimer',
      section: isTamil ? 'வினாடி வினா விருப்பங்கள்' : 'Quiz Preferences',
      title: isTamil ? 'வினாடி வினா கடிகாரம்' : 'Quiz Timer',
      subtitle: isTamil ? 'கேள்விக்கு நேர வரம்பு' : 'Time limit per question',
      keywords: ['timer', 'clock', 'countdown', 'கடிகாரம்', 'நேரம்'],
      icon: '⏱️',
      actionType: 'toggle',
      targetKey: 'quizTimer',
    },
    {
      id: 'soundEffects',
      section: isTamil ? 'ஒலி & அதிர்வு' : 'Sound & Haptics',
      title: isTamil ? 'ஒலி விளைவுகள்' : 'Sound Effects',
      subtitle: isTamil ? 'வினாடி வினா மற்றும் இடைமுக ஒலிகள்' : 'Quiz interactions and feedback sounds',
      keywords: ['sound', 'audio', 'effects', 'volume', 'ஒலி', 'சப்தம்'],
      icon: '🔊',
      actionType: 'toggle',
      targetKey: 'soundEffects',
    },
    {
      id: 'haptics',
      section: isTamil ? 'ஒலி & அதிர்வு' : 'Sound & Haptics',
      title: isTamil ? 'தொடு அதிர்வு (Haptics)' : 'Haptic Feedback',
      subtitle: isTamil ? 'பொத்தான் மற்றும் தேர்வு அதிர்வுகள்' : 'Vibrations for buttons and selections',
      keywords: ['haptics', 'vibration', 'touch feedback', 'அதிர்வு', 'தொடுதல்'],
      icon: '📳',
      actionType: 'toggle',
      targetKey: 'haptics',
    },
    {
      id: 'storageCache',
      section: isTamil ? 'தரவு & சேமிப்பு' : 'Data & Storage',
      title: isTamil ? 'தற்காலிக சேமிப்பை நீக்கு' : 'Clear Cached Data',
      subtitle: isTamil ? 'உள்ளூர் தற்காலிக தரவை நீக்குகிறது' : 'Remove locally cached dashboard data',
      keywords: ['cache', 'storage', 'data', 'clean', 'சேமிப்பு', 'தற்காலிக தரவு', 'நீக்கு'],
      icon: '🗑️',
      actionType: 'modal',
      modalType: 'clearCache',
    },
    {
      id: 'helpCenter',
      section: isTamil ? 'ஆதரவு & உதவி' : 'Support',
      title: isTamil ? 'உதவி மையம்' : 'Help Center',
      subtitle: isTamil ? 'பயன்பாட்டு வழிகாட்டி & அடிக்கடி கேட்கப்படும் கேள்விகள்' : 'User guide and FAQs',
      keywords: ['help', 'faq', 'support', 'contact', 'உதவி', 'கேள்விகள்', 'ஆதரவு'],
      icon: '❓',
      actionType: 'navigate',
      targetRoute: '/help',
    },
    {
      id: 'aboutVigyaan',
      section: isTamil ? 'விவரம்' : 'About',
      title: isTamil ? 'விஞ்ஞான் பற்றி' : 'About Vigyaan',
      subtitle: isTamil ? 'ஆர்.எம்.கே பொறியியல் கல்லூரி' : 'R.M.K. Engineering College',
      keywords: ['about', 'college', 'rmk', 'version', 'பற்றி', 'கல்லூரி', 'விஞ்ஞான்'],
      icon: 'ℹ️',
      actionType: 'navigate',
      targetRoute: '/about',
    },
    {
      id: 'privacyPolicy',
      section: isTamil ? 'சட்டப்பூர்வ' : 'Legal',
      title: isTamil ? 'தனியுரிமைக் கொள்கை' : 'Privacy Policy',
      subtitle: isTamil ? 'மாணவர் தரவு பாதுகாப்பு' : 'Student data protection policy',
      keywords: ['privacy', 'policy', 'terms', 'legal', 'தனியுரிமை', 'கொள்கை', 'சட்டம்'],
      icon: '🔒',
      actionType: 'navigate',
      targetRoute: '/privacy',
    },
    {
      id: 'termsOfUse',
      section: isTamil ? 'சட்டப்பூர்வ' : 'Legal',
      title: isTamil ? 'பயன்பாட்டு விதிமுறைகள்' : 'Terms of Use',
      subtitle: isTamil ? 'பயன்பாட்டு நிபந்தனைகள்' : 'Application usage terms',
      keywords: ['terms', 'conditions', 'rules', 'விதிமுறைகள்', 'நிபந்தனைகள்'],
      icon: '📜',
      actionType: 'navigate',
      targetRoute: '/terms',
    },
    {
      id: 'resetPreferences',
      section: isTamil ? 'மீட்டமை' : 'Reset',
      title: isTamil ? 'விருப்பங்களை மீட்டமை' : 'Reset App Preferences',
      subtitle: isTamil ? 'அமைப்புகளை இயல்புநிலைக்கு மாற்றவும்' : 'Restore preferences to default',
      keywords: ['reset', 'defaults', 'restore', 'மீட்டமை', 'இயல்புநிலை'],
      icon: '🔄',
      actionType: 'modal',
      modalType: 'resetPreferences',
    },
    {
      id: 'deleteAccount',
      section: isTamil ? 'அபாய பகுதி' : 'Danger Zone',
      title: isTamil ? 'கணக்கை நீக்கு' : 'Delete Account',
      subtitle: isTamil ? 'கணக்கு நீக்க வழிகாட்டுதல்' : 'Institutional account removal guide',
      keywords: ['delete', 'remove', 'account', 'நீக்கு', 'கணக்கு நீக்கம்'],
      icon: '⚠️',
      actionType: 'navigate',
      targetRoute: '/delete-account',
    },
  ];
}
