/**
 * Explore 2.0 — Inventions Dataset
 * At least 30 inventions with bilingual EN/TA content.
 * Educational, age-appropriate for Grades 6–12.
 */

import { Invention, DiscoveryTopicId } from './explore.types';

export const INVENTIONS: Invention[] = [
  {
    id: 'electric_light',
    name: { en: 'Electric Light Bulb', ta: 'மின் விளக்கு' },
    inventor: { en: 'Thomas Edison', ta: 'தாமஸ் எடிசன்' },
    description: { en: 'A device that produces visible light from electricity, transforming how we live and work.', ta: 'மின்சாரத்திலிருந்து காணக்கூடிய ஒளியை உற்பத்தி செய்யும் சாதனம், நாம் வாழும் மற்றும் வேலை செய்யும் விதத்தை மாற்றியது.' },
    sciencePrinciple: { en: 'Incandescence: heating a filament until it glows with visible light.', ta: 'ஒளிர்வு: ஒளிரும் வெளிச்சத்துடன் ஒளிரும் வரை ஒரு இழையை சூடாக்குதல்.' },
    whyItMatters: { en: 'Enabled humans to extend productive hours beyond daylight.', ta: 'பகல் ஒளிக்கு அப்பால் உற்பத்தி நேரத்தை நீட்டிக்க மனிதர்களை அனுமதித்தது.' },
    field: 'physics',
    relatedTopics: ['physics', 'engineering'],
    icon: '💡',
    accentColor: '#D97706',
  },
  {
    id: 'telephone',
    name: { en: 'Telephone', ta: 'தொலைபேசி' },
    inventor: { en: 'Alexander Graham Bell', ta: 'அலெக்சாண்டர் கிரஹம் பெல்' },
    description: { en: 'A device that transmits voice over long distances using electrical signals.', ta: 'மின் சிக்னல்கள் மூலம் நீண்ட தூரத்தில் குரலை அனுப்பும் சாதனம்.' },
    sciencePrinciple: { en: 'Sound waves are converted to electrical signals, transmitted, and converted back to sound.', ta: 'ஒலி அலைகள் மின் சிக்னல்களாக மாற்றப்பட்டு, அனுப்பப்பட்டு, மீண்டும் ஒலியாக மாற்றப்படுகின்றன.' },
    whyItMatters: { en: 'Revolutionized personal and business communication worldwide.', ta: 'உலகளாவிய தனிப்பட்ட மற்றும் வணிக தகவல்தொடர்பை புரட்சிகரமாக்கியது.' },
    field: 'engineering',
    relatedTopics: ['engineering', 'physics'],
    icon: '📞',
    accentColor: '#2563EB',
  },
  {
    id: 'wheel',
    name: { en: 'Wheel', ta: 'சக்கரம்' },
    inventor: { en: 'Unknown (Mesopotamia, ~3500 BC)', ta: 'அறியப்படவில்லை (மெசபடோமியா, ~3500 கி.மு.)' },
    description: { en: 'A circular component that rotates around an axle, enabling efficient movement and transportation.', ta: 'ஒரு அச்சைச் சுற்றி சுழலும் வட்ட உறுப்பு, திறமையான இயக்கம் மற்றும் போக்குவரத்தை சாத்தியமாக்குகிறது.' },
    sciencePrinciple: { en: 'Rolling friction is much less than sliding friction, reducing energy needed to move objects.', ta: 'சுழற்று உராய்வு சறுக்கு உராய்வை விட மிகக் குறைவு, பொருட்களை நகர்த்த தேவையான ஆற்றலைக் குறைக்கிறது.' },
    whyItMatters: { en: 'Foundation of all transportation and mechanical systems.', ta: 'அனைத்து போக்குவரத்து மற்றும் இயந்திர அமைப்புகளின் அடிப்படை.' },
    field: 'engineering',
    relatedTopics: ['engineering', 'physics'],
    icon: '⚙️',
    accentColor: '#6B7280',
  },
  {
    id: 'printing_press',
    name: { en: 'Printing Press', ta: 'அச்சு இயந்திரம்' },
    inventor: { en: 'Johannes Gutenberg', ta: 'ஜோஹானஸ் குட்டன்பெர்க்' },
    description: { en: 'A machine for mass-producing printed text, making books and knowledge widely accessible.', ta: 'அச்சிடப்பட்ட உரையை வெகுவாக உற்பத்தி செய்யும் இயந்திரம், புத்தகங்கள் மற்றும் அறிவை பரவலாக கிடைக்கச் செய்தது.' },
    sciencePrinciple: { en: 'Movable type allows individual letters to be arranged, inked, and pressed onto paper.', ta: 'நகரும் எழுத்துக்கள் தனிப்பட்ட எழுத்துக்களை ஏற்பாடு செய்து, மை பூசி, காகிதத்தில் அழுத்த அனுமதிக்கிறது.' },
    whyItMatters: { en: 'Democratized knowledge and enabled the spread of science and education.', ta: 'அறிவை மக்களாட்சியாக்கியது மற்றும் அறிவியல் மற்றும் கல்வியின் பரவலை சாத்தியமாக்கியது.' },
    field: 'engineering',
    relatedTopics: ['engineering'],
    icon: '📚',
    accentColor: '#92400E',
  },
  {
    id: 'penicillin',
    name: { en: 'Penicillin (Antibiotic)', ta: 'பென்சிலின் (நுண்ணுயிர் எதிர்ப்பொருள்)' },
    inventor: { en: 'Alexander Fleming', ta: 'அலெக்சாண்டர் பிளெமிங்' },
    description: { en: 'The first true antibiotic, used to treat bacterial infections.', ta: 'பாக்டீரியா தொற்றுகளை சிகிச்சை செய்ய பயன்படுத்தப்படும் முதல் உண்மையான நுண்ணுயிர் எதிர்ப்பொருள்.' },
    sciencePrinciple: { en: 'Penicillin kills bacteria by preventing them from building their cell walls.', ta: 'பென்சிலின் பாக்டீரியாவின் செல் சுவர்களை உருவாக்குவதைத் தடுப்பதன் மூலம் அவற்றைக் கொல்கிறது.' },
    whyItMatters: { en: 'Has saved over 200 million lives since its discovery.', ta: 'அதன் கண்டுபிடிப்பிலிருந்து 200 மில்லியனுக்கும் அதிகமான உயிர்களைக் காப்பாற்றியுள்ளது.' },
    field: 'medicine',
    relatedTopics: ['medicine', 'biology'],
    icon: '💊',
    accentColor: '#16A34A',
  },
  {
    id: 'compass',
    name: { en: 'Compass', ta: 'திசைகாட்டி' },
    inventor: { en: 'Ancient China (~200 BC)', ta: 'பண்டைய சீனா (~200 கி.மு.)' },
    description: { en: 'A navigation instrument that shows the direction of magnetic north.', ta: 'காந்த வடக்கு திசையைக் காட்டும் வழிசெலுத்தல் கருவி.' },
    sciencePrinciple: { en: 'A magnetized needle aligns with Earth\'s magnetic field lines.', ta: 'ஒரு காந்தமயமாக்கப்பட்ட ஊசி பூமியின் காந்த புல கோடுகளுடன் சீரமைக்கிறது.' },
    whyItMatters: { en: 'Enabled global exploration and navigation.', ta: 'உலகளாவிய ஆராய்ச்சி மற்றும் வழிசெலுத்தலை சாத்தியமாக்கியது.' },
    field: 'physics',
    relatedTopics: ['physics', 'space'],
    icon: '🧭',
    accentColor: '#0369A1',
  },
  {
    id: 'steam_engine',
    name: { en: 'Steam Engine', ta: 'ஆவிப் பொறி' },
    inventor: { en: 'James Watt', ta: 'ஜேம்ஸ் வாட்' },
    description: { en: 'A heat engine that uses steam to produce mechanical work, powering the Industrial Revolution.', ta: 'இயந்திர வேலையை உற்பத்தி செய்ய ஆவியைப் பயன்படுத்தும் வெப்ப எஞ்சின், தொழில்துறை புரட்சியை இயக்கியது.' },
    sciencePrinciple: { en: 'Boiling water produces steam, which expands and pushes pistons to create mechanical motion.', ta: 'தண்ணீரை கொதிக்க வைப்பது ஆவியை உற்பத்தி செய்கிறது, அது விரிவடைந்து பிஸ்டன்களைத் தள்ளி இயந்திர இயக்கத்தை உருவாக்குகிறது.' },
    whyItMatters: { en: 'Powered factories, trains, and ships, transforming modern industry.', ta: 'தொழிற்சாலைகள், ரயில்கள் மற்றும் கப்பல்களை இயக்கியது, நவீன தொழில்துறையை மாற்றியது.' },
    field: 'engineering',
    relatedTopics: ['engineering', 'physics'],
    icon: '🚂',
    accentColor: '#374151',
  },
  {
    id: 'internet',
    name: { en: 'Internet', ta: 'இணையம்' },
    inventor: { en: 'Vint Cerf & Bob Kahn (TCP/IP)', ta: 'வின்ட் செர்ஃப் & பாப் கான் (TCP/IP)' },
    description: { en: 'A global network of computers that enables instant communication and information sharing.', ta: 'உடனடி தகவல்தொடர்பு மற்றும் தகவல் பகிர்வை சாத்தியமாக்கும் கணினிகளின் உலகளாவிய வலையமைப்பு.' },
    sciencePrinciple: { en: 'Data is broken into packets, routed across networks, and reassembled at the destination.', ta: 'தரவு பேக்கெட்டுகளாக உடைக்கப்பட்டு, வலையமைப்புகள் வழியாக வழிநடத்தப்பட்டு, இலக்கில் மீண்டும் ஒன்றிணைக்கப்படுகிறது.' },
    whyItMatters: { en: 'Transformed how humanity communicates, learns, and conducts business.', ta: 'மனிதகுலம் தகவல்தொடர்பு கொள்ளும், கற்றல் மற்றும் வணிகம் செய்யும் விதத்தை மாற்றியது.' },
    field: 'engineering',
    relatedTopics: ['engineering', 'physics'],
    icon: '🌐',
    accentColor: '#2563EB',
  },
  {
    id: 'telescope',
    name: { en: 'Telescope', ta: 'தொலைநோக்கி' },
    inventor: { en: 'Hans Lippershey (1608)', ta: 'ஹான்ஸ் லிப்பர்ஷே (1608)' },
    description: { en: 'An instrument that magnifies distant objects using lenses or mirrors.', ta: 'லென்ஸ்கள் அல்லது கண்ணாடிகள் பயன்படுத்தி தொலைவில் உள்ள பொருட்களை பெரிதாக்கும் கருவி.' },
    sciencePrinciple: { en: 'Lenses or mirrors bend light to magnify distant objects and focus them for observation.', ta: 'லென்ஸ்கள் அல்லது கண்ணாடிகள் ஒளியை வளைத்து தொலைவில் உள்ள பொருட்களை பெரிதாக்கி கவனிப்பதற்கு குவிக்கின்றன.' },
    whyItMatters: { en: 'Revealed the structure of the universe, from planets to galaxies.', ta: 'கிரகங்கள் முதல் விண்மீன் மண்டலங்கள் வரை பிரபஞ்சத்தின் அமைப்பை வெளிப்படுத்தியது.' },
    field: 'space',
    relatedTopics: ['space', 'physics'],
    icon: '🔭',
    accentColor: '#4F46E5',
  },
  {
    id: 'vaccine',
    name: { en: 'Vaccine', ta: 'தடுப்பூசி' },
    inventor: { en: 'Edward Jenner', ta: 'எட்வர்ட் ஜென்னர்' },
    description: { en: 'A biological preparation that provides active acquired immunity against infectious diseases.', ta: 'தொற்று நோய்களுக்கு எதிராக செயலில் உள்ள நோயெதிர்ப்புத்தன்மையை வழங்கும் உயிரியல் தயாரிப்பு.' },
    sciencePrinciple: { en: 'Vaccines introduce a weakened pathogen to train the immune system to fight future infections.', ta: 'எதிர்கால தொற்றுகளை எதிர்த்துப் போராட நோயெதிர்ப்பு மண்டலத்தைப் பயிற்றுவிக்க பலவீனமான நோய்க்கிருமியை அறிமுகப்படுத்துகின்றன.' },
    whyItMatters: { en: 'Has eradicated smallpox and saved hundreds of millions of lives.', ta: 'சின்னம்மையை ஒழித்து நூறு மில்லியன் கணக்கான உயிர்களைக் காப்பாற்றியுள்ளது.' },
    field: 'medicine',
    relatedTopics: ['medicine', 'biology'],
    icon: '💉',
    accentColor: '#059669',
  },
  {
    id: 'bicycle',
    name: { en: 'Bicycle', ta: 'மிதிவண்டி' },
    inventor: { en: 'Karl von Drais (1817)', ta: 'கார்ல் வோன் ட்ரைஸ் (1817)' },
    description: { en: 'A human-powered vehicle with two wheels, providing efficient personal transportation.', ta: 'இரண்டு சக்கரங்கள் கொண்ட மனித இயக்க வாகனம், திறமையான தனிப்பட்ட போக்குவரத்தை வழங்குகிறது.' },
    sciencePrinciple: { en: 'Angular momentum and gyroscopic effects provide stability while pedaling converts leg motion to rotation.', ta: 'கோண திருப்புமுனை மற்றும் ஜைரோஸ்கோபிக் விளைவுகள் நிலைத்தன்மையை வழங்குகின்றன, மிதிமாற்றம் கால் இயக்கத்தை சுழற்சியாக மாற்றுகிறது.' },
    whyItMatters: { en: 'One of the most energy-efficient forms of personal transportation ever created.', ta: 'உருவாக்கப்பட்ட மிகவும் ஆற்றல் திறமையான தனிப்பட்ட போக்குவரத்து வடிவங்களில் ஒன்று.' },
    field: 'engineering',
    relatedTopics: ['engineering', 'physics'],
    icon: '🚲',
    accentColor: '#DC2626',
  },
  {
    id: 'magnifying_glass',
    name: { en: 'Magnifying Glass', ta: 'பெரிதாக்கும் கண்ணாடி' },
    inventor: { en: 'Ancient (Roger Bacon, 13th century)', ta: 'பண்டைய (ரோஜர் பேகன், 13ஆம் நூற்றாண்டு)' },
    description: { en: 'A convex lens that magnifies objects viewed through it.', ta: 'அதன் வழியாகப் பார்க்கும் பொருட்களை பெரிதாக்கும் குவிந்த லென்ஸ்.' },
    sciencePrinciple: { en: 'A convex lens bends light rays inward, creating an enlarged virtual image of nearby objects.', ta: 'ஒரு குவிந்த லென்ஸ் ஒளி கதிர்களை உள்நோக்கி வளைத்து, அருகிலுள்ள பொருட்களின் பெரிதாக்கப்பட்ட மாயை படத்தை உருவாக்குகிறது.' },
    whyItMatters: { en: 'Foundation for microscopes, telescopes, and corrective lenses.', ta: 'மைக்ரோஸ்கோப்கள், தொலைநோக்கிகள் மற்றும் திருத்தும் லென்ஸ்களுக்கான அடிப்படை.' },
    field: 'physics',
    relatedTopics: ['physics'],
    icon: '🔍',
    accentColor: '#7C3AED',
  },
  {
    id: 'thermometer',
    name: { en: 'Thermometer', ta: 'வெப்பமானி' },
    inventor: { en: 'Galileo Galilei (1593)', ta: 'கலிலியோ கலிலீ (1593)' },
    description: { en: 'An instrument for measuring temperature.', ta: 'வெப்பநிலையை அளக்கும் கருவி.' },
    sciencePrinciple: { en: 'Liquids expand when heated and contract when cooled, allowing temperature measurement through volume change.', ta: 'திரவங்கள் சூடாகும்போது விரிவடைந்து, குளிரும்போது சுருங்குகின்றன, கன அளவு மாற்றம் மூலம் வெப்பநிலை அளவீட்டை அனுமதிக்கின்றன.' },
    whyItMatters: { en: 'Essential for weather forecasting, medicine, and scientific research.', ta: 'வானிலை முன்னறிவிப்பு, மருத்துவம் மற்றும் அறிவியல் ஆய்வுகளுக்கு அவசியம்.' },
    field: 'physics',
    relatedTopics: ['physics'],
    icon: '🌡️',
    accentColor: '#DC2626',
  },
  {
    id: 'solar_cell',
    name: { en: 'Solar Cell', ta: 'சூரிய செல்' },
    inventor: { en: 'Bell Labs (1954)', ta: 'பெல் ஆய்வகங்கள் (1954)' },
    description: { en: 'A device that converts sunlight directly into electricity.', ta: 'சூரிய ஒளியை நேரடியாக மின்சாரமாக மாற்றும் சாதனம்.' },
    sciencePrinciple: { en: 'The photovoltaic effect: photons knock electrons free in semiconductor materials, creating electric current.', ta: 'ஒளிமின் விளைவு: ஃபோட்டான்கள் குறைக்கடத்தி பொருட்களில் எலக்ட்ரான்களை விடுவித்து மின்னோட்டத்தை உருவாக்குகின்றன.' },
    whyItMatters: { en: 'Provides clean, renewable energy from sunlight.', ta: 'சூரிய ஒளியிலிருந்து சுத்தமான, புதுப்பிக்கத்தக்க ஆற்றலை வழங்குகிறது.' },
    field: 'physics',
    relatedTopics: ['physics', 'environment'],
    icon: '☀️',
    accentColor: '#EA580C',
  },
  {
    id: 'battery',
    name: { en: 'Battery', ta: 'மின்கலம்' },
    inventor: { en: 'Alessandro Volta (1800)', ta: 'அலெஸ்ஸாந்த்ரோ வோல்டா (1800)' },
    description: { en: 'A device that stores chemical energy and converts it to electrical energy.', ta: 'ரசாயன ஆற்றலை சேமித்து மின் ஆற்றலாக மாற்றும் சாதனம்.' },
    sciencePrinciple: { en: 'Chemical reactions between electrodes and electrolyte produce a flow of electrons.', ta: 'மின்வழிகள் மற்றும் மின்பகுப்பான் இடையே ரசாயன வினைகள் எலக்ட்ரான்கள் ஓட்டத்தை உற்பத்தி செய்கின்றன.' },
    whyItMatters: { en: 'Powers portable devices, electric vehicles, and backup systems.', ta: 'கைப்பேசி சாதனங்கள், மின்சார வாகனங்கள் மற்றும் மாற்று அமைப்புகளை இயக்குகிறது.' },
    field: 'physics',
    relatedTopics: ['physics', 'chemistry'],
    icon: '🔋',
    accentColor: '#16A34A',
  },
  {
    id: 'microscope',
    name: { en: 'Microscope', ta: 'நுண்ணோக்கி' },
    inventor: { en: 'Hans & Zacharias Janssen (1590)', ta: 'ஹான்ஸ் & சகாரியாஸ் ஜான்சன் (1590)' },
    description: { en: 'An instrument that makes tiny objects visible to the human eye.', ta: 'சிறிய பொருட்களை மனித கண்ணுக்கு தெரியச் செய்யும் கருவி.' },
    sciencePrinciple: { en: 'Multiple lenses magnify light reflected from tiny specimens, revealing invisible details.', ta: 'பல லென்ஸ்கள் சிறிய மாதிரிகளிலிருந்து பிரதிபலிக்கும் ஒளியை பெரிதாக்கி, கண்ணுக்குப் புலப்படாத விவரங்களை வெளிப்படுத்துகின்றன.' },
    whyItMatters: { en: 'Enabled discovery of cells, bacteria, and the microscopic world.', ta: 'செல்கள், பாக்டீரியா மற்றும் நுண்ணிய உலகின் கண்டுபிடிப்பை சாத்தியமாக்கியது.' },
    field: 'biology',
    relatedTopics: ['biology', 'medicine'],
    icon: '🔬',
    accentColor: '#7E22CE',
  },
  {
    id: 'airplane',
    name: { en: 'Airplane', ta: 'விமானம்' },
    inventor: { en: 'Wright Brothers (1903)', ta: 'ரைட் சகோதரர்கள் (1903)' },
    description: { en: 'A powered aircraft capable of sustained flight through the atmosphere.', ta: 'வளிமண்டலம் வழியாக நிலையான விமானத்திற்கு திறன் கொண்ட ஒரு மோட்டார் விமானம்.' },
    sciencePrinciple: { en: 'Bernoulli\'s principle: air moves faster over curved wing surfaces, creating lower pressure above and lift.', ta: 'பெர்னூலி கோட்பாடு: வளைந்த இறக்கை மேற்பரப்புகளில் காற்று வேகமாக நகர்கிறது, மேலே குறைந்த அழுத்தத்தையும் உயர்த்தும் விசையையும் உருவாக்குகிறது.' },
    whyItMatters: { en: 'Shrank the world by enabling fast long-distance travel.', ta: 'விரைவான நீண்ட தூர பயணத்தை சாத்தியமாக்கி உலகத்தை சுருக்கியது.' },
    field: 'engineering',
    relatedTopics: ['engineering', 'physics'],
    icon: '✈️',
    accentColor: '#2563EB',
  },
  {
    id: 'nuclear_reactor',
    name: { en: 'Nuclear Reactor', ta: 'அணு மின்நிலையம்' },
    inventor: { en: 'Enrico Fermi (1942)', ta: 'என்ரிகோ பெர்மி (1942)' },
    description: { en: 'A device that controls nuclear fission to generate heat and electricity.', ta: 'வெப்பம் மற்றும் மின்சாரம் உற்பத்தி செய்ய அணுக்கரு பிளவை கட்டுப்படுத்தும் சாதனம்.' },
    sciencePrinciple: { en: 'Nuclear fission splits heavy atoms (uranium) releasing enormous energy as heat.', ta: 'அணுக்கரு பிளவு கனமான அணுக்களை (யுரேனியம்) பிரித்து மிகப்பெரிய ஆற்றலை வெப்பமாக வெளியிடுகிறது.' },
    whyItMatters: { en: 'Provides large-scale carbon-free electricity but raises safety and waste concerns.', ta: 'கார்பன் இல்லாத மின்சாரத்தை பெரிய அளவில் வழங்குகிறது, ஆனால் பாதுகாப்பு மற்றும் கழிவு கவலைகளை எழுப்புகிறது.' },
    field: 'physics',
    relatedTopics: ['physics', 'environment'],
    icon: '⚛️',
    accentColor: '#6D28D9',
  },
  {
    id: 'refrigerator',
    name: { en: 'Refrigerator', ta: 'குளிர்சாதனம்' },
    inventor: { en: 'Jacob Perkins (1834)', ta: 'ஜேக்கப் பெர்கின்ஸ் (1834)' },
    description: { en: 'A device that maintains food at low temperatures to slow bacterial growth.', ta: 'பாக்டீரியா வளர்ச்சியை மெதுவாக்க உணவை குறைந்த வெப்பநிலையில் பராமரிக்கும் சாதனம்.' },
    sciencePrinciple: { en: 'A refrigerant cycles between gas and liquid, absorbing heat inside and releasing it outside.', ta: 'ஒரு குளிரூட்டி வாயு மற்றும் திரவத்திற்கு இடையில் சுழற்சி செய்கிறது, உள்ளே வெப்பத்தை உறிஞ்சி வெளியே வெளியிடுகிறது.' },
    whyItMatters: { en: 'Reduced food spoilage and enabled modern food supply chains.', ta: 'உணவு சிதைவைக் குறைத்து நவீன உணவு விநியோக சங்கிலிகளை சாத்தியமாக்கியது.' },
    field: 'physics',
    relatedTopics: ['physics', 'engineering'],
    icon: '🧊',
    accentColor: '#0284C7',
  },
  {
    id: 'calculator',
    name: { en: 'Calculator', ta: 'கால்குலேட்டர்' },
    inventor: { en: 'Blaise Pascal (1642)', ta: 'பிளைஸ் பாஸ்கல் (1642)' },
    description: { en: 'An electronic device for performing mathematical calculations.', ta: 'கணித கணக்கீடுகளைச் செய்ய ஒரு மின்னணு சாதனம்.' },
    sciencePrinciple: { en: 'Transistors and integrated circuits perform arithmetic operations using binary logic.', ta: 'டிரான்சிஸ்டர்கள் மற்றும் ஒருங்கிணைந்த சுற்றுகள் இரும தர்க்கம் பயன்படுத்தி கூட்டல் செயல்களை செய்கின்றன.' },
    whyItMatters: { en: 'Made complex calculations accessible to students and professionals.', ta: 'சிக்கலான கணக்கீடுகளை மாணவர்கள் மற்றும் தொழில் வல்லுநர்களுக்கு எளிதாக்கியது.' },
    field: 'mathematics',
    relatedTopics: ['mathematics', 'engineering'],
    icon: '🧮',
    accentColor: '#0369A1',
  },
  {
    id: 'transistor',
    name: { en: 'Transistor', ta: 'டிரான்சிஸ்டர்' },
    inventor: { en: 'Bell Labs (1947)', ta: 'பெல் ஆய்வகங்கள் (1947)' },
    description: { en: 'A semiconductor device used to amplify or switch electronic signals.', ta: 'மின்னணு சிக்னல்களை பெருக்கவோ மாற்றவோ பயன்படுத்தப்படும் குறைக்கடத்தி சாதனம்.' },
    sciencePrinciple: { en: 'Doped semiconductor materials control electron flow, enabling signal amplification and digital logic.', ta: 'சேர்க்கை குறைக்கடத்தி பொருட்கள் எலக்ட்ரான் ஓட்டத்தை கட்டுப்படுத்தி, சிக்னல் பெருக்கம் மற்றும் டிஜிட்டல் தர்க்கத்தை சாத்தியமாக்குகின்றன.' },
    whyItMatters: { en: 'Enabled all modern electronics — computers, phones, and virtually all digital devices.', ta: 'அனைத்து நவீன மின்னணுவியலை — கணினிகள், தொலைபேசிகள் மற்றும் கிட்டத்தட்ட அனைத்து டிஜிட்டல் சாதனங்களையும் சாத்தியமாக்கியது.' },
    field: 'physics',
    relatedTopics: ['physics', 'engineering'],
    icon: '🔌',
    accentColor: '#1E40AF',
  },
  {
    id: 'printer',
    name: { en: '3D Printer', ta: '3D பிரின்டர்' },
    inventor: { en: 'Chuck Hull (1984)', ta: 'சக் ஹல் (1984)' },
    description: { en: 'A machine that creates three-dimensional objects from digital designs.', ta: 'டிஜிட்டல் வடிவமைப்புகளிலிருந்து முப்பரிமாண பொருட்களை உருவாக்கும் இயந்திரம்.' },
    sciencePrinciple: { en: 'Additive manufacturing deposits material layer by layer, building objects from the bottom up.', ta: 'கூட்டு உற்பத்தி பொருளை அடுக்கு அடுக்காக வைத்து, கீழிருந்து மேல் பொருட்களை உருவாக்குகிறது.' },
    whyItMatters: { en: 'Enables rapid prototyping, custom manufacturing, and even bioprinting.', ta: 'விரைவான ஆரம்ப வடிவமைப்பு, தனிப்பயன் உற்பத்தி மற்றும் உயிரி பிரின்டிங் ஆகியவற்றை சாத்தியமாக்குகிறது.' },
    field: 'engineering',
    relatedTopics: ['engineering'],
    icon: '🖨️',
    accentColor: '#7C3AED',
  },
  {
    id: 'radio',
    name: { en: 'Radio', ta: 'வானொலி' },
    inventor: { en: 'Guglielmo Marconi', ta: 'குக்லியெல்மோ மார்கோனி' },
    description: { en: 'A device for transmitting and receiving radio waves for communication.', ta: 'தகவல்தொடர்புக்காக வானொலி அலைகளை அனுப்பவும் பெறவும் ஒரு சாதனம்.' },
    sciencePrinciple: { en: 'Electromagnetic waves are generated by oscillating electric currents and detected by antennas.', ta: 'மின்காந்த அலைகள் அதிர்வுறும் மின் ஓட்டங்களால் உருவாக்கப்பட்டு ஆண்டெனாக்களால் கண்டறியப்படுகின்றன.' },
    whyItMatters: { en: 'Pioneered wireless communication, paving the way for TV, WiFi, and mobile networks.', ta: 'கம்பியில்லா தகவல்தொடர்பின் முன்னோடி, டிவி, WiFi மற்றும் மொபைல் நெட்வொர்க்குகளுக்கு வழிவகுத்தது.' },
    field: 'physics',
    relatedTopics: ['physics', 'engineering'],
    icon: '📻',
    accentColor: '#B45309',
  },
  {
    id: 'internet_search',
    name: { en: 'Search Engine', ta: 'தேடுபொறி' },
    inventor: { en: 'Larry Page & Sergey Brin (Google, 1998)', ta: 'லேரி பேஜ் & செர்ஜி பிரின் (கூகிள், 1998)' },
    description: { en: 'A software system that searches the internet for information matching user queries.', ta: 'பயனர் வினவல்களுடன் பொருந்தும் தகவலை இணையத்தில் தேடும் மென்பொருள் அமைப்பு.' },
    sciencePrinciple: { en: 'Web crawlers index pages, and algorithms rank results by relevance using link analysis.', ta: 'வலை கிராலர்கள் பக்கங்களை வகைப்படுத்தி, விதிமுறைகள் இணைப்பு பகுப்பாய்வு மூலம் முடிவுகளை தொடர்புடையதன் அடிப்படையில் தரவரிசைப்படுத்துகின்றன.' },
    whyItMatters: { en: 'Made the world\'s information instantly accessible to anyone with internet access.', ta: 'இணைய அணுகல் உள்ள யாருக்கும் உலகின் தகவலை உடனடியாக எளிதாக்கியது.' },
    field: 'engineering',
    relatedTopics: ['engineering'],
    icon: '🔎',
    accentColor: '#2563EB',
  },
];

export function getInventionById(id: string): Invention | undefined {
  return INVENTIONS.find((i) => i.id === id);
}

export function getInventionsByField(field: DiscoveryTopicId): Invention[] {
  return INVENTIONS.filter((i) => i.field === field);
}
