/**
 * Explore 2.0 — Scientists Dataset
 * At least 30 scientists with bilingual EN/TA content.
 * All educational, age-appropriate for Grades 6–12.
 */

import { Scientist, DiscoveryTopicId } from './explore.types';

export const SCIENTISTS: Scientist[] = [
  {
    id: 'newton',
    name: { en: 'Isaac Newton', ta: 'ஐசாக் நியூட்டன்' },
    field: 'physics',
    keyContribution: { en: 'Laws of Motion and Universal Gravitation', ta: 'இயக்க விதிகள் மற்றும் பிரபஞ்ச ஈர்ப்பு விசை' },
    shortBio: { en: 'English mathematician and physicist who formulated the three laws of motion and the law of universal gravitation.', ta: 'இயக்க விதிகள் மூன்றையும் பிரபஞ்ச ஈர்ப்பு விசை விதியையும் உருவாக்கிய ஆங்கிலேய கணிதவியலாளரும் இயற்பியலாளரும்.' },
    interestingFacts: [
      { en: 'Newton was also a famous alchemist and theologian.', ta: 'நியூட்டன் ஒரு பிரபலமான ரசவாதியும் இறையியலாளரும் கூட.' },
      { en: 'He invented the reflecting telescope.', ta: 'அவர் பிரதிபலிப்பு தொலைநோக்கியை கண்டுபிடித்தார்.' },
      { en: 'The Principia Mathematica is one of the most important books in science.', ta: 'பிரின்சிபியா மாத்தமாட்டிகா அறிவியலில் மிக முக்கியமான புத்தகங்களில் ஒன்று.' },
    ],
    relatedTopics: ['physics', 'mathematics'],
    icon: '🍎',
    accentColor: '#2563EB',
  },
  {
    id: 'einstein',
    name: { en: 'Albert Einstein', ta: 'ஆல்பர்ட் ஐன்ஸ்டைன்' },
    field: 'physics',
    keyContribution: { en: 'Theory of Relativity', ta: 'சார்புக் கோட்பாடு' },
    shortBio: { en: 'German-born physicist who developed the theory of special and general relativity, revolutionizing our understanding of space and time.', ta: 'சிறப்பு மற்றும் பொது சார்புக் கோட்பாட்டை உருவாக்கிய, விண்வெளி மற்றும் நேரம் பற்றிய புரிதலை மாற்றிய ஜெர்மன் பிறப்பு இயற்பியலாளர்.' },
    interestingFacts: [
      { en: 'E = mc² shows that mass and energy are equivalent.', ta: 'E = mc² என்பது நிறை மற்றும் ஆற்றல் சமம் என்பதைக் காட்டுகிறது.' },
      { en: 'He won the Nobel Prize in Physics in 1921.', ta: 'அவர் 1921 இல் இயற்பியலுக்கான நோபல் பரிசு பெற்றார்.' },
      { en: 'He developed the photoelectric effect theory.', ta: 'அவர் ஒளிமின் விளைவு கோட்பாட்டை உருவாக்கினார்.' },
    ],
    relatedTopics: ['physics', 'space'],
    icon: '⚛️',
    accentColor: '#7E22CE',
  },
  {
    id: 'curie',
    name: { en: 'Marie Curie', ta: 'மேரி கியூரி' },
    field: 'chemistry',
    keyContribution: { en: 'Research on radioactivity, discovery of polonium and radium', ta: 'கதிரியக்கத் தன்மை பற்றிய ஆய்வு, போலோனியம் மற்றும் ரேடியம் கண்டுபிடிப்பு' },
    shortBio: { en: 'Polish-born French physicist and chemist, the first woman to win a Nobel Prize and the only person to win Nobel Prizes in two different sciences.', ta: 'போலிஷ் பிறப்பு பிரெஞ்சு இயற்பியலாளரும் வேதியியலாளரும், நோபல் பரிசு பெற்ற முதல் பெண் மற்றும் இரண்டு வெவ்வேறு அறிவியல் துறைகளில் நோபல் பரிசு பெற்ற ஒரே நபர்.' },
    interestingFacts: [
      { en: 'Her notebooks are still radioactive today.', ta: 'அவரது நோட்புக்குகள் இன்றும் கதிரியக்கம் உடையவை.' },
      { en: 'She coined the term "radioactivity".', ta: 'அவர் "கதிரியக்கம்" என்ற சொல்லை உருவாக்கினார்.' },
      { en: 'Her daughter Irène also won a Nobel Prize.', ta: 'அவரது மகள் இரேனும் நோபல் பரிசு பெற்றார்.' },
    ],
    relatedTopics: ['chemistry', 'physics'],
    icon: '☢️',
    accentColor: '#DC2626',
  },
  {
    id: 'darwin',
    name: { en: 'Charles Darwin', ta: 'சார்லஸ் டார்வின்' },
    field: 'biology',
    keyContribution: { en: 'Theory of Evolution by Natural Selection', ta: 'இயற்கை தேர்வு மூலம் பரிணாம வளர்ச்சிக் கோட்பாடு' },
    shortBio: { en: 'English naturalist who developed the theory of evolution, fundamentally changing our understanding of life on Earth.', ta: 'உயிரின பரிணாம வளர்ச்சிக் கோட்பாட்டை உருவாக்கிய, பூமியில் உயிர் பற்றிய புரிதலை அடிப்படையாக மாற்றிய ஆங்கிலேய இயற்கை ஆய்வாளர்.' },
    interestingFacts: [
      { en: 'The voyage of HMS Beagle took 5 years.', ta: 'HMS பீகிள் கப்பலின் பயணம் 5 ஆண்டுகள் நீடித்தது.' },
      { en: 'He spent over 20 years developing his theory before publishing.', ta: 'தனது கோட்பாட்டை வெளியிடுவதற்கு முன் 20 ஆண்டுகளுக்கும் மேலாக உருவாக்கினார்.' },
      { en: 'On the Origin of Species is one of the most influential books ever written.', ta: 'ஆன் தி ஆரிஜின் ஆஃப் ஸ்பீசிஸ் என்ற புத்தகம் எழுதப்பட்ட மிகவும் செல்வாக்குமிக்க புத்தகங்களில் ஒன்று.' },
    ],
    relatedTopics: ['biology', 'animals_plants'],
    icon: '🧬',
    accentColor: '#16A34A',
  },
  {
    id: 'tesla',
    name: { en: 'Nikola Tesla', ta: 'நிக்கோலா டெஸ்லா' },
    field: 'physics',
    keyContribution: { en: 'Alternating current (AC) electrical system', ta: 'மாறுதிசை மின்சார அமைப்பு (AC)' },
    shortBio: { en: 'Serbian-American inventor and electrical engineer who designed the modern alternating current electricity supply system.', ta: 'நவீன மாறுதிசை மின்சார விநியோக அமைப்பை வடிவமைத்த செர்பிய-அமெரிக்க கண்டுபிடிப்பாளரும் மின்பொறியியலாளரும்.' },
    interestingFacts: [
      { en: 'Tesla could visualize inventions completely in his mind before building them.', ta: 'டெஸ்லா தனது மனதில் கண்டுபிடிப்புகளை முழுமையாக கற்பனை செய்ய முடியும்.' },
      { en: 'He held around 300 patents.', ta: 'அவர் சுமார் 300 காப்புரிமைகளை வைத்திருந்தார்.' },
      { en: 'The unit of magnetic flux density is named after him.', ta: 'காந்த ஓட்ட அடர்த்தியின் அலகு அவரது பெயரால் அழைக்கப்படுகிறது.' },
    ],
    relatedTopics: ['physics', 'engineering'],
    icon: '⚡',
    accentColor: '#D97706',
  },
  {
    id: 'galileo',
    name: { en: 'Galileo Galilei', ta: 'கலிலியோ கலிலீ' },
    field: 'space',
    keyContribution: { en: 'Improvements to the telescope and astronomical observations', ta: 'தொலைநோக்கியில் மேம்பாடுகள் மற்றும் வானியல் அவதானிப்புகள்' },
    shortBio: { en: 'Italian astronomer and physicist, often called the father of modern observational astronomy and modern science.', ta: 'இத்தாலிய வானியலாளரும் இயற்பியலாளரும், நவீன கண்காணிப்பு வானியல் மற்றும் நவீன அறிவியலின் தந்தை என்று அழைக்கப்படுகிறார்.' },
    interestingFacts: [
      { en: 'He was the first to use a telescope to observe the heavens.', ta: 'வானத்தை அவதானிக்க தொலைநோக்கியை பயன்படுத்திய முதல் நபர் அவர்.' },
      { en: 'He discovered four moons of Jupiter.', ta: 'அவர் வியாழனின் நான்கு நிலவுகளைக் கண்டுபிடித்தார்.' },
      { en: 'He supported the heliocentric model of the solar system.', ta: 'சூரிய மைய மாதிரியை ஆதரித்தார்.' },
    ],
    relatedTopics: ['space', 'physics'],
    icon: '🔭',
    accentColor: '#1E40AF',
  },
  {
    id: 'mendeleev',
    name: { en: 'Dmitri Mendeleev', ta: 'டிமித்ரி மெண்டலீவ்' },
    field: 'chemistry',
    keyContribution: { en: 'Periodic Table of Elements', ta: 'உறுப்புகளின் ஆவர்த்தன அட்டவணை' },
    shortBio: { en: 'Russian chemist who formulated the Periodic Law and created a farsighted version of the periodic table.', ta: 'ஆவர்த்தன விதியை வடிவமைத்து ஆவர்த்தன அட்டவணையின் நோக்குமிக்க பதிப்பை உருவாக்கிய ரஷ்ய வேதியியலாளர்.' },
    interestingFacts: [
      { en: 'He predicted the existence of undiscovered elements.', ta: 'கண்டுபிடிக்கப்படாத உறுப்புகளின் இருப்பை அவர் கணித்தார்.' },
      { en: 'The periodic table has 118 confirmed elements today.', ta: 'ஆவர்த்தன அட்டவணையில் இன்று 118 உறுப்புகள் உள்ளன.' },
      { en: 'He reportedly saw the table in a dream.', ta: 'அவர் கனவில் அட்டவணையை கண்டதாகக் கூறப்படுகிறது.' },
    ],
    relatedTopics: ['chemistry'],
    icon: '🧪',
    accentColor: '#7E22CE',
  },
  {
    id: 'hypatia',
    name: { en: 'Hypatia', ta: 'ஹைப்பாட்டியா' },
    field: 'mathematics',
    keyContribution: { en: 'Mathematics and astronomy teaching, editing key texts', ta: 'கணிதம் மற்றும் வானியல் கற்பித்தல், முக்கிய நூல்களை திருத்துதல்' },
    shortBio: { en: 'Ancient Egyptian mathematician, astronomer, and philosopher, one of the earliest female mathematicians recorded in history.', ta: 'பண்டைய எகிப்திய கணிதவியலாளர், வானியலாளர் மற்றும் தத்துவவாதி, வரலாற்றில் பதிவு செய்யப்பட்ட முதல் பெண் கணிதவியலாளர்களில் ஒருவர்.' },
    interestingFacts: [
      { en: 'She led the Neoplatonic school in Alexandria.', ta: 'அலெக்சாண்டிரியாவில் நியோபிளாட்டோனிக் பள்ளியை வழிநடத்தினார்.' },
      { en: 'She improved methods for calculating pi.', ta: 'pai யை கணக்கிடும் முறைகளை மேம்படுத்தினார்.' },
      { en: 'Her father Theon was a famous mathematician at the Museum of Alexandria.', ta: 'அவரது தந்தை தியோன் அலெக்சாண்டிரியா அருங்காட்சியகத்தின் பிரபலமான கணிதவியலாளர்.' },
    ],
    relatedTopics: ['mathematics', 'space'],
    icon: '📐',
    accentColor: '#2563EB',
  },
  {
    id: 'boyle',
    name: { en: 'Robert Boyle', ta: 'ராபர்ட் பாய்ல்' },
    field: 'chemistry',
    keyContribution: { en: "Boyle's Law (gas pressure-volume relationship)", ta: 'பாய்ல் விதி (வாயு அழுத்தம்-கன அளவு தொடர்பு)' },
    shortBio: { en: 'Anglo-Irish natural philosopher and chemist, known as the father of modern chemistry for his work on gases.', ta: 'வாயுக்கள் மீதான பணிக்காக நவீன வேதியியலின் தந்தை என்று அறியப்படும் ஆங்கிலோ-ஐரிஷ் இயற்கை தத்துவவாதி மற்றும் வேதியியலாளர்.' },
    interestingFacts: [
      { en: "Boyle's Law states that pressure × volume is constant for a gas at fixed temperature.", ta: 'பாய்ல் விதி நிலையான வெப்பநிலையில் வாயுவின் அழுத்தம் × கன அளவு மாறிலி என்பதைக் கூறுகிறது.' },
      { en: 'He invented the vacuum pump.', ta: 'அவர் வெற்றிட பம்பை கண்டுபிடித்தார்.' },
      { en: 'He wrote The Sceptical Chymist, a foundational chemistry text.', ta: 'அவர் வேதியியலின் அடிப்படை நூலான தி செப்டிகல் கேமிஸ்ட் என்ற புத்தகத்தை எழுதினார்.' },
    ],
    relatedTopics: ['chemistry', 'physics'],
    icon: '🫧',
    accentColor: '#059669',
  },
  {
    id: 'pasteur',
    name: { en: 'Louis Pasteur', ta: 'லூயிஸ் பாஸ்தூர்' },
    field: 'biology',
    keyContribution: { en: 'Germ theory of disease, pasteurization, vaccines', ta: 'நோயின் கிருமிக் கோட்பாடு, பாஸ்தூராக்கம், தடுப்பூசிகள்' },
    shortBio: { en: 'French chemist and microbiologist who created the first vaccines for rabies and anthrax.', ta: 'தொட்டுப் பரவும் நோய்களின் கிருமிக் கோட்பாட்டை நிறுவிய, காசநோய் மற்றும் நாய்க்கடி நோய்க்கான முதல் தடுப்பூசிகளை உருவாக்கிய பிரெஞ்சு வேதியியலாளர் மற்றும் நுண்ணுயிரியலாளர்.' },
    interestingFacts: [
      { en: 'Pasteurization is named after him.', ta: 'பாஸ்தூராக்கம் அவரது பெயரால் அழைக்கப்படுகிறது.' },
      { en: 'He disproved spontaneous generation.', ta: 'தன்னிச்சையான தோற்றத்தை அவர் மறுத்தார்.' },
      { en: 'His work saved millions of lives through safe food and vaccines.', ta: 'அவரது பணி பாதுகாப்பான உணவு மற்றும் தடுப்பூசிகள் மூலம் மில்லியன் கணக்கான உயிர்களைக் காப்பாற்றியது.' },
    ],
    relatedTopics: ['biology', 'medicine'],
    icon: '🧫',
    accentColor: '#16A34A',
  },
  {
    id: 'turing',
    name: { en: 'Alan Turing', ta: 'அலன் டூரிங்' },
    field: 'mathematics',
    keyContribution: { en: 'Theoretical computer science and artificial intelligence', ta: 'கோட்பாட்டு கணினி அறிவியல் மற்றும் செயற்கை நுண்ணறிவு' },
    shortBio: { en: 'English mathematician and logician who is considered the father of theoretical computer science and artificial intelligence.', ta: 'கோட்பாட்டு கணினி அறிவியல் மற்றும் செயற்கை நுண்ணறிவின் தந்தை என்று கருதப்படும் ஆங்கிலேய கணிதவியலாளர் மற்றும் லாஜிசியன்.' },
    interestingFacts: [
      { en: 'The Turing Test is a measure of machine intelligence.', ta: 'டூரிங் சோதனை இயந்திர நுண்ணறிவின் அளவுகோல்.' },
      { en: 'He helped crack the Enigma code during World War II.', ta: 'இரண்டாம் உலகப் போரின் போது எனிக்மா குறியீட்டை உடைக்க உதவினார்.' },
      { en: 'The Turing machine is a fundamental concept in computer science.', ta: 'டூரிங் இயந்திரம் கணினி அறிவியலில் ஒரு அடிப்படை கருத்துரு.' },
    ],
    relatedTopics: ['mathematics', 'engineering'],
    icon: '🖥️',
    accentColor: '#6366F1',
  },
  {
    id: 'cavendish',
    name: { en: 'Henry Cavendish', ta: 'ஹென்றி கேவெண்டிஷ்' },
    field: 'physics',
    keyContribution: { en: 'Discovery of hydrogen and measurement of gravitational constant', ta: 'ஹைட்ரஜன் கண்டுபிடிப்பு மற்றும் ஈர்ப்பு மாறிலியின் அளவீடு' },
    shortBio: { en: 'British natural philosopher and chemist who discovered hydrogen and made precise measurements of Earth\'s density.', ta: 'ஹைட்ரஜனை கண்டுபிடித்து, பூமியின் அடர்த்தியை துல்லியமாக அளந்த பிரிட்டிஷ் இயற்கை தத்துவவாதி மற்றும் வேதியியலாளர்.' },
    interestingFacts: [
      { en: 'Hydrogen was called "inflammable air" before Cavendish.', ta: 'கேவெண்டிஷ்க்கு முன் ஹைட்ரஜன் "எரியும் காற்று" என்று அழைக்கப்பட்டது.' },
      { en: 'He was famously shy and rarely left his home.', ta: 'அவர் மிகவும் கூச்ச சுபாவம் உடையவர், அரிதாகவே வீட்டை விட்டு வெளியேறினார்.' },
      { en: 'The Cavendish experiment measured the gravitational constant G.', ta: 'கேவெண்டிஷ் முயற்சி ஈர்ப்பு மாறிலி G யை அளந்தது.' },
    ],
    relatedTopics: ['physics', 'chemistry'],
    icon: '💨',
    accentColor: '#0891B2',
  },
  {
    id: 'chandrasekhar',
    name: { en: 'Subrahmanyan Chandrasekhar', ta: 'சுப்பிரமணியன் சந்திரசேகர்' },
    field: 'space',
    keyContribution: { en: 'Chandrasekhar Limit for stellar evolution', ta: 'நட்சத்திர பரிணாமத்திற்கான சந்திரசேகர் வரம்பு' },
    shortBio: { en: 'Indian-American astrophysicist who calculated the maximum mass of a stable white dwarf star.', ta: 'நிலையான வெள்ளை குள்ள நட்சத்திரத்தின் அதிகபட்ச நிறையை கணக்கிட்ட இந்திய-அமெரிக்க வானியற்பியலாளர்.' },
    interestingFacts: [
      { en: 'The Chandra X-ray Observatory is named after him.', ta: 'சந்திரா எக்ஸ்-ரே வானியல் ஆய்வகம் அவரது பெயரால் அழைக்கப்படுகிறது.' },
      { en: 'He won the Nobel Prize in Physics in 1983.', ta: 'அவர் 1983 இல் இயற்பியலுக்கான நோபல் பரிசு பெற்றார்.' },
      { en: 'He was the nephew of physicist C.V. Raman.', ta: 'இயற்பியலாளர் C.V. ராமனின் மருமகன் அவர்.' },
    ],
    relatedTopics: ['space', 'physics'],
    icon: '🌟',
    accentColor: '#4F46E5',
  },
  {
    id: 'hubble',
    name: { en: 'Edwin Hubble', ta: 'எட்வின் ஹபிள்' },
    field: 'space',
    keyContribution: { en: 'Evidence that the universe is expanding', ta: 'பிரபஞ்சம் விரிவடைகிறது என்ற ஆதாரம்' },
    shortBio: { en: 'American astronomer who proved that galaxies exist beyond the Milky Way and that the universe is expanding.', ta: 'பால்வெளிக்கு அப்பால் விண்மீன் மண்டலங்கள் இருப்பதையும் பிரபஞ்சம் விரிவடைகிறது என்பதையும் நிரூபித்த அமெரிக்க வானியலாளர்.' },
    interestingFacts: [
      { en: 'The Hubble Space Telescope is named in his honor.', ta: 'ஹபிள் விண்வெளி தொலைநோக்கி அவரது நினைவாக பெயரிடப்பட்டது.' },
      { en: 'He was also a talented basketball player.', ta: 'அவர் ஒரு திறமையான கூடைப்பந்து வீரரும் கூட.' },
      { en: 'Hubble\'s Law describes the rate of expansion of the universe.', ta: 'ஹபிள் விதி பிரபஞ்சத்தின் விரிவாக்க வேகத்தை விவரிக்கிறது.' },
    ],
    relatedTopics: ['space'],
    icon: '🌌',
    accentColor: '#7C3AED',
  },
  {
    id: 'fleming',
    name: { en: 'Alexander Fleming', ta: 'அலெக்சாண்டர் பிளெமிங்' },
    field: 'medicine',
    keyContribution: { en: 'Discovery of penicillin', ta: 'பென்சிலின் கண்டுபிடிப்பு' },
    shortBio: { en: 'Scottish physician and microbiologist who discovered penicillin, the first true antibiotic.', ta: 'முதல் உண்மையான நுண்ணுயிர் எதிர்ப்பொருளான பென்சிலினை கண்டுபிடித்த ஸ்காட்டிஷ் மருத்துவர் மற்றும் நுண்ணுயிரியலாளர்.' },
    interestingFacts: [
      { en: 'Penicillin was discovered by accident in 1928.', ta: 'பென்சிலின் 1228 இல் தற்செயலாக கண்டுபிடிக்கப்பட்டது.' },
      { en: 'It has saved an estimated 200 million lives.', ta: 'இது சுமார் 200 மில்லியன் உயிர்களைக் காப்பாற்றியுள்ளது.' },
      { en: 'He shared the Nobel Prize in Physiology or Medicine in 1945.', ta: 'அவர் 1945 இல் உடலியல் அல்லது மருத்துவத்திற்கான நோபல் பரிசை பகிர்ந்து கொண்டார்.' },
    ],
    relatedTopics: ['medicine', 'biology'],
    icon: '💊',
    accentColor: '#059669',
  },
  {
    id: 'raman',
    name: { en: 'C.V. Raman', ta: 'சி.வி. ராமன்' },
    field: 'physics',
    keyContribution: { en: 'Raman Effect (light scattering)', ta: 'ராமன் விளைவு (ஒளி சிதறல்)' },
    shortBio: { en: 'Indian physicist who discovered the Raman Effect, earning the first Nobel Prize for an Asian scientist.', ta: 'ராமன் விளைவை கண்டுபிடித்த, ஆசிய விஞ்ஞானிக்கு முதல் நோபல் பரிசைப் பெற்றுத்தந்த இந்திய இயற்பியலாளர்.' },
    interestingFacts: [
      { en: 'February 28 is celebrated as National Science Day in India in his honor.', ta: 'பிப்ரவரி 28 அவரது நினைவாக இந்தியாவில் தேசிய அறிவியல் தினமாக கொண்டாடப்படுகிறது.' },
      { en: 'The Raman Effect explains why the sea appears blue.', ta: 'ராமன் விளைவு கடல் நீலமாக ஏன் தோன்றுகிறது என்பதை விளக்குகிறது.' },
      { en: 'He was knighted in 1929.', ta: 'அவர் 1929 இல் நைட் பட்டம் பெற்றார்.' },
    ],
    relatedTopics: ['physics'],
    icon: '🌈',
    accentColor: '#EA580C',
  },
  {
    id: 'borr',
    name: { en: 'Niels Bohr', ta: 'நீல்ஸ் போர்' },
    field: 'physics',
    keyContribution: { en: 'Atomic model and quantum mechanics', ta: 'அணு மாதிரி மற்றும் குவாண்டம் இயக்கவியல்' },
    shortBio: { en: 'Danish physicist who made foundational contributions to understanding atomic structure and quantum theory.', ta: 'அணு அமைப்பு மற்றும் குவாண்டம் கோட்பாடு புரிதலுக்கு அடிப்படையான பங்களிப்புகளைச் செய்த டேனிஷ் இயற்பியலாளர்.' },
    interestingFacts: [
      { en: 'Bohr\'s model shows electrons orbit the nucleus in specific energy levels.', ta: 'போர் மாதிரி எலக்ட்ரான்கள் குறிப்பிட்ட ஆற்றல் நிலைகளில் கருவை சுற்றி வருவதைக் காட்டுகிறது.' },
      { en: 'The element bohrium (Bh) is named after him.', ta: 'போரியம் (Bh) என்ற உறுப்பு அவரது பெயரால் அழைக்கப்படுகிறது.' },
      { en: 'He helped refugees escape during World War II.', ta: 'இரண்டாம் உலகப் போரின் போது அகதிகள் தப்பிக்க உதவினார்.' },
    ],
    relatedTopics: ['physics', 'chemistry'],
    icon: '⚛️',
    accentColor: '#1D4ED8',
  },
  {
    id: 'noether',
    name: { en: 'Emmy Noether', ta: 'எம்மி நோதர்' },
    field: 'mathematics',
    keyContribution: { en: "Noether's Theorem (symmetry and conservation laws)", ta: 'நோதர் தேற்றம் (சமச்சீர் மற்றும் பாதுகாப்பு விதிகள்)' },
    shortBio: { en: 'German mathematician whose work fundamentally changed abstract algebra and theoretical physics.', ta: 'அமூர்த கணிதம் மற்றும் கோட்பாட்டு இயற்பியலை அடிப்படையாக மாற்றிய ஜெர்மன் கணிதவியலாளர்.' },
    interestingFacts: [
      { en: "Einstein called her the most important woman in the history of mathematics.", ta: 'ஐன்ஸ்டைன் அவரை கணித வரலாற்றில் மிக முக்கியமான பெண் என்று அழைத்தார்.' },
      { en: "Noether's Theorem connects symmetry in physics to conservation laws.", ta: 'நோதர் தேற்றம் இயற்பியலில் சமச்சீரை பாதுகாப்பு விதிகளுடன் இணைக்கிறது.' },
      { en: 'Despite her contributions, she was initially denied a paid position.', ta: 'அவரது பங்களிப்புகள் இருந்தபோதிலும், அவருக்கு ஆரம்பத்தில் ஊதியம் பெறும் பதவி மறுக்கப்பட்டது.' },
    ],
    relatedTopics: ['mathematics', 'physics'],
    icon: '🔢',
    accentColor: '#9333EA',
  },
  {
    id: 'hawking',
    name: { en: 'Stephen Hawking', ta: 'ஸ்டீபன் ஹாக்கிங்' },
    field: 'space',
    keyContribution: { en: 'Hawking radiation and black hole thermodynamics', ta: 'ஹாக்கிங் கதிர்வீச்சு மற்றும் கருங்குழி வெப்ப இயக்கவியல்' },
    shortBio: { en: 'British theoretical physicist who made groundbreaking contributions to our understanding of black holes and cosmology.', ta: 'கருங்குழிகள் மற்றும் அண்டவியல் பற்றிய புரிதலுக்கு முன்னோடி பங்களிப்புகளைச் செய்த பிரிட்டிஷ் கோட்பாட்டு இயற்பியலாளர்.' },
    interestingFacts: [
      { en: 'Hawking radiation suggests black holes can emit particles.', ta: 'ஹாக்கிங் கதிர்வீச்சு கருங்குழிகள் துகள்களை வெளியிட முடியும் என்று தெரிவிக்கிறது.' },
      { en: 'He wrote A Brief History of Time, a bestselling popular science book.', ta: 'அவர் சுருக்கமான வரலாறு என்ற மிகவும் பிரபலமான அறிவியல் புத்தகத்தை எழுதினார்.' },
      { en: 'He communicated using a speech-generating device for decades.', ta: 'பல தசாப்தங்களாக பேச்சு உருவாக்கும் சாதனத்தை பயன்படுத்தி தொடர்பு கொண்டார்.' },
    ],
    relatedTopics: ['space', 'physics'],
    icon: '🕳️',
    accentColor: '#6D28D9',
  },
  {
    id: 'goodall',
    name: { en: 'Jane Goodall', ta: 'ஜேன் குடால்' },
    field: 'biology',
    keyContribution: { en: 'Pioneering chimpanzee research and conservation', ta: 'சிம்பன்சி ஆய்வு மற்றும் பாதுகாப்பில் முன்னோடி' },
    shortBio: { en: 'British primatologist and anthropologist known for her extraordinary 60-year study of wild chimpanzees in Tanzania.', ta: 'தான்சானியாவில் காட்டு சிம்பன்சிகளின் அசாதாரண 60 ஆண்டு ஆய்வுக்காக அறியப்பட்ட பிரிட்டிஷ் பிரைமேட்டாலஜிஸ்ட் மற்றும் மானுடவியலாளர்.' },
    interestingFacts: [
      { en: 'She was the first to observe chimpanzees using tools.', ta: 'கருவிகளைப் பயன்படுத்தும் சிம்பன்சிகளை முதலில் அவதானித்தவர் அவர்.' },
      { en: 'Gombe Stream National Park was created to protect her research site.', ta: 'அவரது ஆய்வு தளத்தைப் பாதுகாக்க கோம்பே ஸ்ட்ரீம் தேசிய பூங்கா உருவாக்கப்பட்டது.' },
      { en: 'She founded the Jane Goodall Institute for conservation.', ta: 'அவர் பாதுகாப்பிற்காக ஜேன் குடால் நிறுவனத்தை நிறுவினார்.' },
    ],
    relatedTopics: ['biology', 'animals_plants'],
    icon: '🦧',
    accentColor: '#16A34A',
  },
  {
    id: 'tyson',
    name: { en: 'C.T. Velu Thampi Dalawa', ta: 'டி.கே. வேலு தம்பி தலவா' },
    field: 'engineering',
    keyContribution: { en: 'One of India\'s earliest freedom fighters and innovators', ta: 'இந்தியாவின் முதல் சுதந்திர போராட்ட வீரர்கள் மற்றும் கண்டுபிடிப்பாளர்களில் ஒருவர்' },
    shortBio: { en: 'An important figure in Kerala\'s history who introduced several administrative and technological reforms.', ta: 'கேரளாவின் வரலாற்றில் பல நிர்வாக மற்றும் தொழில்நுட்ப சீர்திருத்தங்களை அறிமுகப்படுத்திய முக்கிய நபர்.' },
    interestingFacts: [
      { en: 'He modernized Kerala\'s administrative systems.', ta: 'அவர் கேரளாவின் நிர்வாக அமைப்புகளை நவீனமயமாக்கினார்.' },
      { en: 'He introduced several educational reforms.', ta: 'அவர் பல கல்வி சீர்திருத்தங்களை அறிமுகப்படுத்தினார்.' },
      { en: 'His legacy lives on in Kerala\'s progressive traditions.', ta: 'அவரது பாரம்பரியம் கேரளாவின் முற்போக்கு மரபுகளில் வாழ்கிறது.' },
    ],
    relatedTopics: ['engineering'],
    icon: '🏗️',
    accentColor: '#B45309',
  },
  {
    id: 'patti',
    name: { en: '屠呦呦 (Tu Youyou)', ta: 'டு யூயூ' },
    field: 'medicine',
    keyContribution: { en: 'Discovery of artemisinin (malaria treatment)', ta: 'ஆர்ட்டிமிசினின் கண்டுபிடிப்பு (மலேரியா சிகிச்சை)' },
    shortBio: { en: 'Chinese pharmaceutical chemist who discovered artemisinin, a treatment for malaria that has saved millions of lives.', ta: 'மில்லியன் கணக்கான உயிர்களைக் காப்பாற்றிய மலேரியா சிகிச்சையான ஆர்ட்டிமிசினினை கண்டுபிடித்த சீன மருந்து வேதியியலாளர்.' },
    interestingFacts: [
      { en: 'Artemisinin comes from sweet wormwood, used in traditional Chinese medicine.', ta: 'ஆர்ட்டிமிசினின் சீன மருத்துவத்தில் பயன்படுத்தப்படும் இனிப்பு வர்ம்வுட் இலிருந்து வருகிறது.' },
      { en: 'She won the Nobel Prize in Physiology or Medicine in 2015.', ta: 'அவர் 2015 இல் உடலியல் அல்லது மருத்துவத்திற்கான நோபல் பரிசு பெற்றார்.' },
      { en: 'She saved hundreds of millions of lives worldwide.', ta: 'அவர் உலகளவில் நூறு மில்லியன் கணக்கான உயிர்களைக் காப்பாற்றினார்.' },
    ],
    relatedTopics: ['medicine', 'biology'],
    icon: '🌿',
    accentColor: '#059669',
  },
  {
    id: 'tesla_woman',
    name: { en: 'Hedy Lamarr', ta: 'ஹெடி லமார்' },
    field: 'engineering',
    keyContribution: { en: 'Co-invented frequency-hopping spread spectrum technology', ta: 'அதிர்வெண்-துள்ளல் பரவல் ஸ்பெக்ட்ரம் தொழில்நுட்பத்தை இணைந்து கண்டுபிடித்தார்' },
    shortBio: { en: 'Austrian-American actress and inventor who co-invented technology that became the basis for WiFi, GPS, and Bluetooth.', ta: 'WiFi, GPS மற்றும் Bluetooth இன் அடிப்படையாக மாறிய தொழில்நுட்பத்தை இணைந்து கண்டுபிடித்த ஆஸ்திரிய-அமெரிக்க நடிகை மற்றும் கண்டுபிடிப்பாளர்.' },
    interestingFacts: [
      { en: 'Her frequency-hopping patent was filed in 1942.', ta: 'அவரது அதிர்வெண்-துள்ளல் காப்புரிமை 1942 இல் தாக்கல் செய்யப்பட்டது.' },
      { en: 'She was inducted into the National Inventors Hall of Fame in 2014.', ta: 'அவர் 2014 இல் தேசிய கண்டுபிடிப்பாளர்கள் புகழ் மண்டலத்தில் சேர்க்கப்பட்டார்.' },
      { en: 'She started as a Hollywood glamour actress but was also a brilliant engineer.', ta: 'அவர் ஹாலிவுட் கவர்ச்சி நடிகையாக தொடங்கினார், ஆனால் ஒரு புகழ்பெற்ற பொறியியலாளரும் கூட.' },
    ],
    relatedTopics: ['engineering', 'physics'],
    icon: '📡',
    accentColor: '#BE185D',
  },
  {
    id: 'vinci',
    name: { en: 'Leonardo da Vinci', ta: 'லியொனார்டோ டா வின்சி' },
    field: 'engineering',
    keyContribution: { en: 'Pioneering designs in engineering, anatomy, and art', ta: 'பொறியியல், உடற்கூறு மற்றும் கலையில் முன்னோடி வடிவமைப்புகள்' },
    shortBio: { en: 'Italian polymath of the Renaissance who excelled in painting, engineering, science, and anatomy.', ta: 'ஓவியம், பொறியியல், அறிவியல் மற்றும் உடற்கூறுவியலில் சிறந்து விளங்கிய ரெனெசான்ஸ் கால இத்தாலிய பல்திறன் கொண்டவர்.' },
    interestingFacts: [
      { en: 'He drew detailed anatomical sketches centuries ahead of their time.', ta: 'அவர் நூற்றாண்டுகளுக்கு முன்னரே விரிவான உடற்கூறு வரைபடங்களை வரைந்தார்.' },
      { en: 'He designed flying machines long before powered flight existed.', ta: 'பலசாலி விமானம் தோன்றுவதற்கு முன்பே பறக்கும் இயந்திரங்களை வடிவமைத்தார்.' },
      { en: 'The Mona Lisa is one of his most famous paintings.', ta: 'மோனா லிசா அவரது மிகவும் பிரசித்தமான ஓவியங்களில் ஒன்று.' },
    ],
    relatedTopics: ['engineering', 'physics'],
    icon: '🎨',
    accentColor: '#92400E',
  },
  {
    id: 'mclintock',
    name: { en: 'Barbara McClintock', ta: 'பார்பரா மெக்லிண்டாக்' },
    field: 'biology',
    keyContribution: { en: 'Discovery of genetic transposition ("jumping genes")', ta: 'மரபு பெயர்வு ("துள்ளும் மரபன்கள்") கண்டுபிடிப்பு' },
    shortBio: { en: 'American scientist who discovered that genes can change position on chromosomes, winning the Nobel Prize in 1983.', ta: 'மரபன்கள் நிறமிகளில் நிலையை மாற்ற முடியும் என்பதை கண்டுபிடித்து 1983 இல் நோபல் பரிசு பெற்ற அமெரிக்க விஞ்ஞானி.' },
    interestingFacts: [
      { en: 'Her work was initially dismissed by other scientists.', ta: 'அவரது பணி ஆரம்பத்தில் மற்ற விஞ்ஞானிகளால் நிராகரிக்கப்பட்டது.' },
      { en: 'She studied corn (maize) genetics for decades.', ta: 'அவர் பல தசாப்தங்களாக சோள மரபியலை ஆராய்ந்தார்.' },
      { en: 'She was the first woman to win an unshared Nobel Prize in Physiology or Medicine.', ta: 'உடலியல் அல்லது மருத்துவத்தில் பகிரப்படாத நோபல் பரிசு பெற்ற முதல் பெண் அவர்.' },
    ],
    relatedTopics: ['biology'],
    icon: '🌽',
    accentColor: '#65A30D',
  },
  {
    id: 'bayern',
    name: { en: 'Archimedes', ta: 'ஆர்க்கிமிடீஸ்' },
    field: 'physics',
    keyContribution: { en: 'Principles of buoyancy, levers, and early calculus concepts', ta: 'மிதப்பு கோட்பாடுகள், கொக்கிகள் மற்றும் ஆரம்பகால கால்குலஸ் கருத்துக்கள்' },
    shortBio: { en: 'Ancient Greek mathematician, physicist, and engineer, considered one of the greatest mathematicians of all time.', ta: 'எல்லா காலத்திலும் மிகச்சிறந்த கணிதவியலாளர்களில் ஒருவராகக் கருதப்படும் பண்டைய கிரேக்க கணிதவியலாளர், இயற்பியலாளர் மற்றும் பொறியியலாளர்.' },
    interestingFacts: [
      { en: '"Eureka!" is attributed to Archimedes discovering the principle of buoyancy.', ta: '"யூரேகா!" என்பது மிதப்பு கோட்பாட்டை கண்டுபிடித்த ஆர்க்கிமிடீஸுக்கு கூறப்படுகிறது.' },
      { en: 'He designed war machines to defend Syracuse.', ta: 'சிரகுஸை பாதுகாக்க போர் இயந்திரங்களை வடிவமைத்தார்.' },
      { en: 'He estimated the number of grains of sand to fill the universe.', ta: 'பிரபஞ்சத்தை நிரப்ப தேவையான மணல் துகள்களின் எண்ணிக்கையை மதிப்பிட்டார்.' },
    ],
    relatedTopics: ['physics', 'mathematics'],
    icon: '⚖️',
    accentColor: '#B45309',
  },
  {
    id: 'beriberi',
    name: { en: 'Christiaan Eijkman', ta: 'கிறிஸ்டியான் ஐக்மன்' },
    field: 'medicine',
    keyContribution: { en: 'Discovery of vitamins (beriberi research)', ta: 'வைட்டமின்கள் கண்டுபிடிப்பு (பெரிபெரி ஆய்வு)' },
    shortBio: { en: 'Dutch physician and professor who discovered that beriberi is caused by a dietary deficiency, leading to the concept of vitamins.', ta: 'பெரிபெரி உணவுக் குறைபாடு காரணமாக ஏற்படுகிறது என்பதை கண்டுபிடித்து, வைட்டமின் கருத்துக்கு வழிவகுத்த டச்சு மருத்துவர் மற்றும் பேராசிரியர்.' },
    interestingFacts: [
      { en: 'Beriberi means "I can\'t, I can\'t" in Sinhalese.', ta: 'பெரிபெரி சிங்கள மொழியில் "என்னால் முடியாது, என்னால் முடியாது" என்று பொருள்படும்.' },
      { en: 'He proved that food processing removes essential nutrients.', ta: 'உணவு செயலாக்கம் அத்தியாவசிய ஊட்டச்சத்துக்களை அகற்றுகிறது என்பதை நிரூபித்தார்.' },
      { en: 'He won the Nobel Prize in Physiology or Medicine in 1929.', ta: 'அவர் 1929 இல் உடலியல் அல்லது மருத்துவத்திற்கான நோபல் பரிசு பெற்றார்.' },
    ],
    relatedTopics: ['medicine', 'biology'],
    icon: '🍎',
    accentColor: '#DC2626',
  },
  {
    id: 'faraday',
    name: { en: 'Michael Faraday', ta: 'மைக்கேல் ஃபாரடே' },
    field: 'physics',
    keyContribution: { en: 'Electromagnetic induction and laws of electrolysis', ta: 'மின்காந்த தூண்டல் மற்றும் மின்பகுப்பு விதிகள்' },
    shortBio: { en: 'English scientist who made significant contributions to the study of electromagnetism and electrochemistry.', ta: 'மின்காந்தவியல் மற்றும் மின்வேதியியல் ஆய்வுகளில் குறிப்பிடத்தக்க பங்களிப்புகளைச் செய்த ஆங்கிலேய விஞ்ஞானி.' },
    interestingFacts: [
      { en: 'Faraday had no formal education beyond elementary school.', ta: 'ஃபாரடேக்கு ஆரம்பப் பள்ளிக்கு அப்பால் முறையான கல்வி இல்லை.' },
      { en: 'He discovered that a changing magnetic field produces an electric current.', ta: 'மாறும் காந்தப் புலம் மின் ஓட்டத்தை உருவாக்குகிறது என்பதை அவர் கண்டுபிடித்தார்.' },
      { en: 'The farad unit of capacitance is named after him.', ta: 'மின்திறன் அலகு ஃபாரட் அவரது பெயரால் அழைக்கப்படுகிறது.' },
    ],
    relatedTopics: ['physics', 'chemistry'],
    icon: '⚡',
    accentColor: '#B45309',
  },
  {
    id: 'rosalind',
    name: { en: 'Rosalind Franklin', ta: 'ரோசலின் ஃபிராங்க்ளின்' },
    field: 'biology',
    keyContribution: { en: 'X-ray crystallography of DNA (Photo 51)', ta: 'DNA இன் எக்ஸ்-ரே படிகவியல் (ஃபோட்டோ 51)' },
    shortBio: { en: 'English chemist and X-ray crystallographer whose work was central to understanding the structure of DNA.', ta: 'DNA இன் அமைப்பைப் புரிந்துகொள்வதில் மையமான பணியைச் செய்த ஆங்கிலேய வேதியியலாளர் மற்றும் எக்ஸ்-ரே படிகவியலாளர்.' },
    interestingFacts: [
      { en: 'Photo 51 was the key image that revealed DNA\'s double helix structure.', ta: 'ஃபோட்டோ 51 DNA இன் இரட்டை துடுப்பு அமைப்பை வெளிப்படுத்திய முக்கிய படம்.' },
      { en: 'She also made important contributions to understanding coal and graphite.', ta: 'நிலக்கரி மற்றும் கிராஃபைட் புரிதலிலும் முக்கிய பங்களிப்புகள் செய்தார்.' },
      { en: 'Her work was used by Watson and Crick without her knowledge.', ta: 'அவரது பணி வாட்சன் மற்றும் கிரிக்கால் அவரது அறிவின்றி பயன்படுத்தப்பட்டது.' },
    ],
    relatedTopics: ['biology', 'chemistry'],
    icon: '🧬',
    accentColor: '#BE185D',
  },
  {
    id: 'maxwell',
    name: { en: 'James Clerk Maxwell', ta: 'ஜேம்ஸ் கிளார்க் மெக்ஸ்வெல்' },
    field: 'physics',
    keyContribution: { en: 'Classical theory of electromagnetic radiation', ta: 'மின்காந்த கதிர்வீச்சின் மரபுவழி கோட்பாடு' },
    shortBio: { en: 'Scottish physicist who formulated the classical theory of electromagnetic radiation, unifying electricity, magnetism, and light.', ta: 'மின்சாரம், காந்தம் மற்றும் ஒளியை ஒன்றிணைத்த, மின்காந்த கதிர்வீச்சின் மரபுவழி கோட்பாட்டை வடிவமைத்த ஸ்காட்டிஷ் இயற்பியலாளர்.' },
    interestingFacts: [
      { en: 'Maxwell\'s equations are the foundation of all modern electromagnetic technology.', ta: 'மெக்ஸ்வெல் சமன்பாடுகள் அனைத்து நவீன மின்காந்த தொழில்நுட்பத்தின் அடிப்படை.' },
      { en: 'He showed that light is an electromagnetic wave.', ta: 'ஒளி ஒரு மின்காந்த அலை என்பதை அவர் காட்டினார்.' },
      { en: 'Einstein kept a photo of Maxwell on his study wall.', ta: 'ஐன்ஸ்டைன் தனது ஆய்வு சுவரில் மெக்ஸ்வெல்லின் புகைப்படத்தை வைத்திருந்தார்.' },
    ],
    relatedTopics: ['physics'],
    icon: '🌊',
    accentColor: '#1E40AF',
  },
];

export function getScientistById(id: string): Scientist | undefined {
  return SCIENTISTS.find((s) => s.id === id);
}

export function getScientistsByField(field: DiscoveryTopicId): Scientist[] {
  return SCIENTISTS.filter((s) => s.field === field);
}
