/**
 * Explore 2.0 — Everyday Science Dataset
 * 20+ everyday science discoveries for the Explore 2.0 layer.
 * Educational, age-appropriate for Grades 6–12.
 */

import { EverydayScienceItem } from './explore.types';

export const EVERYDAY_SCIENCE: EverydayScienceItem[] = [
  {
    id: 'es_rainbow',
    title: { en: 'Rainbows', ta: 'வானவில்' },
    description: { en: 'Rainbows form when sunlight passes through water droplets in the air.', ta: 'சூரிய ஒளி காற்றில் உள்ள நீர் துளிகள் வழியாக செல்லும்போது வானவில் உருவாகிறது.' },
    sciencePrinciple: { en: 'Light refracts, reflects inside droplets, and separates into its component colors (dispersion).', ta: 'ஒளி முறிவடைந்து, துளிகளுக்குள் பிரதிபலித்து, அதன் கூறு நிறங்களாக பிரிகிறது (விலகல்).' },
    field: 'physics',
    icon: '🌈',
    tags: ['optics', 'light', 'weather'],
  },
  {
    id: 'es_mirror',
    title: { en: 'Mirrors & Reflection', ta: 'கண்ணாடிகள் & பிரதிபலிப்பு' },
    description: { en: 'Mirrors show a reversed image because light bounces off at the same angle it arrives.', ta: 'கண்ணாடிகள் எதிர்மறை படத்தைக் காட்டுகின்றன, ஏனெனில் ஒளி அதே கோணத்தில் திரும்புகிறது.' },
    sciencePrinciple: { en: 'The law of reflection states that the angle of incidence equals the angle of reflection.', ta: 'பிரதிபலிப்பு விதி வருகை கோணம் பிரதிபலிப்பு கோணத்திற்கு சமம் என்று கூறுகிறது.' },
    field: 'physics',
    icon: '🪞',
    tags: ['optics', 'light', 'reflection'],
  },
  {
    id: 'es_magnet',
    title: { en: 'Magnets', ta: 'காந்தங்கள்' },
    description: { en: 'Magnets attract iron, nickel, and cobalt, and can push or pull without touching.', ta: 'காந்தங்கள் இரும்பு, நிக்கல் மற்றும் கோபால்ட்டை ஈர்க்கின்றன, தொடாமலேயே தள்ளவோ இழுக்கவோ செய்யலாம்.' },
    sciencePrinciple: { en: 'Moving electric charges create magnetic fields; Earth itself is a giant magnet.', ta: 'நகரும் மின் கட்டணங்கள் காந்த புலங்களை உருவாக்குகின்றன; பூமி தானே ஒரு பெரிய காந்தம்.' },
    field: 'physics',
    icon: '🧲',
    tags: ['magnetism', 'forces', 'electricity'],
  },
  {
    id: 'es_battery',
    title: { en: 'Batteries', ta: 'மின்கலங்கள்' },
    description: { en: 'Batteries store chemical energy and release it as electricity to power your devices.', ta: 'மின்கலங்கள் ரசாயன ஆற்றலை சேமித்து உங்கள் சாதனங்களை இயக்க மின்சாரமாக வெளியிடுகின்றன.' },
    sciencePrinciple: { en: 'Chemical reactions between metals and electrolytes produce a flow of electrons.', ta: 'உலோகங்கள் மற்றும் மின்பகுப்பான்கள் இடையே ரசாயன வினைகள் எலக்ட்ரான்கள் ஓட்டத்தை உற்பத்தி செய்கின்றன.' },
    field: 'physics',
    icon: '🔋',
    tags: ['electricity', 'chemistry', 'energy'],
  },
  {
    id: 'es_cooking',
    title: { en: 'Cooking & Heat Transfer', ta: 'சமைத்தல் & வெப்ப பரிமாற்றம்' },
    description: { en: 'Cooking uses three types of heat transfer: conduction, convection, and radiation.', ta: 'சமைத்தல் மூன்று வகையான வெப்ப பரிமாற்றத்தைப் பயன்படுத்துகிறது: கடத்தல், மாற்றம் மற்றும் கதிர்வீச்சு.' },
    sciencePrinciple: { en: 'Conduction transfers heat through direct contact, convection through moving fluids, radiation through electromagnetic waves.', ta: 'கடத்தல் நேரடி தொடர்பு மூலம் வெப்பத்தை கடத்துகிறது, மாற்றம் நகரும் திரவங்கள் மூலம், கதிர்வீச்சு மின்காந்த அலைகள் மூலம்.' },
    field: 'physics',
    icon: '🍳',
    tags: ['heat', 'cooking', 'thermodynamics'],
  },
  {
    id: 'es_shadow',
    title: { en: 'Shadows', ta: 'நிழல்கள்' },
    description: { en: 'Shadows form when an object blocks light from reaching a surface.', ta: 'ஒரு பொருள் ஒளியை ஒரு மேற்பரப்பை அடைவதைத் தடுக்கும்போது நிழல்கள் உருவாகின்றன.' },
    sciencePrinciple: { en: 'Light travels in straight lines; when blocked, a dark area (shadow) forms behind the object.', ta: 'ஒளி நேர் கோடுகளில் பயணிக்கிறது; தடுக்கப்படும்போது, பொருளுக்குப் பின்னால் ஒரு இருண்ட பகுதி (நிழல்) உருவாகிறது.' },
    field: 'physics',
    icon: '🌑',
    tags: ['optics', 'light', 'shadows'],
  },
  {
    id: 'es_soap',
    title: { en: 'Soap & Cleaning', ta: 'சோப்பு & சுத்தம் செய்தல்' },
    description: { en: 'Soap removes grease by surrounding oil molecules with water-loving and oil-loving ends.', ta: 'சோப்பு நீரை நேசிக்கும் மற்றும் எண்ணெயை நேசிக்கும் முனைகளால் எண்ணெய் மூலக்கூறுகளை சூழ்ந்து கொழுப்பை அகற்றுகிறது.' },
    sciencePrinciple: { en: 'Soap molecules are amphiphilic: one end attracts water, the other attracts oil, allowing emulsification.', ta: 'சோப்பு மூலக்கூறுகள் இருகாந்த இயல்புடையவை: ஒரு முனை நீரை ஈர்க்கிறது, மற்றொன்று எண்ணெயை ஈர்க்கிறது, எமல்சிஃபிகேஷனை அனுமதிக்கிறது.' },
    field: 'chemistry',
    icon: '🧼',
    tags: ['chemistry', 'cleaning', 'molecules'],
  },
  {
    id: 'es_pressure_cooker',
    title: { en: 'Pressure Cooker', ta: 'அழுத்த சமையல் பாத்திரம்' },
    description: { en: 'Pressure cookers cook food faster by trapping steam and increasing pressure inside.', ta: 'அழுத்த சமையல் பாத்திரங்கள் ஆவியை சிக்க வைத்து உள்ளே அழுத்தத்தை அதிகரிப்பதன் மூலம் உணவை வேகமாக சமைக்கின்றன.' },
    sciencePrinciple: { en: 'Higher pressure raises the boiling point of water, allowing food to cook at higher temperatures.', ta: 'அதிக அழுத்தம் நீரின் கொதிநிலையை உயர்த்தி, உணவை அதிக வெப்பநிலையில் சமைக்க அனுமதிக்கிறது.' },
    field: 'physics',
    icon: '🍲',
    tags: ['pressure', 'cooking', 'boiling'],
  },
  {
    id: 'es_fan',
    title: { en: 'Electric Fan', ta: 'மின் விசிறி' },
    description: { en: 'Fans cool us by moving air, which helps evaporate sweat from our skin.', ta: 'விசிறிகள் காற்றை நகர்த்தி நம்மை குளிர்விக்கின்றன, இது நம் தோலில் இருந்து வியர்வையை ஆவியாக்க உதவுகிறது.' },
    sciencePrinciple: { en: 'Moving air increases the rate of evaporation, which absorbs heat from the skin.', ta: 'நகரும் காற்று ஆவியாதல் வேகத்தை அதிகரிக்கிறது, இது தோலிலிருந்து வெப்பத்தை உறிஞ்சுகிறது.' },
    field: 'physics',
    icon: '🌀',
    tags: ['evaporation', 'cooling', 'electricity'],
  },
  {
    id: 'es_smartphone',
    title: { en: 'Smartphone Sensors', ta: 'ஸ்மார்ட்போன் சென்சார்கள்' },
    description: { en: 'Your phone contains sensors for GPS, accelerometer, gyroscope, light, proximity, and magnetometer.', ta: 'உங்கள் தொலைபேசியில் GPS, முடுக்கமானி, வளைவு மானி, ஒளி, அருகாமை மற்றும் காந்தமானி சென்சார்கள் உள்ளன.' },
    sciencePrinciple: { en: 'MEMS sensors use microscopic mechanical structures to detect motion, orientation, and environmental changes.', ta: 'MEMS சென்சார்கள் இயக்கம், நிலை மற்றும் சுற்றுப்புற மாற்றங்களைக் கண்டறிய நுண்ணிய இயந்திர அமைப்புகளைப் பயன்படுத்துகின்றன.' },
    field: 'engineering',
    icon: '📱',
    tags: ['technology', 'sensors', 'engineering'],
  },
  {
    id: 'es_bicycle_physics',
    title: { en: 'Bicycle Physics', ta: 'மிதிவண்டி இயற்பியல்' },
    description: { en: 'Bicycles stay upright through a combination of gyroscopic effects and rider balance.', ta: 'மிதிவண்டிகள் ஜைரோஸ்கோபிக் விளைவுகள் மற்றும் சவாரி செய்பவர் சமநிலை ஆகியவற்றின் கலவையின் மூலம் நேராக நிற்கின்றன.' },
    sciencePrinciple: { en: 'Angular momentum from spinning wheels and trail geometry provide self-righting torque.', ta: 'சுழலும் சக்கரங்களின் கோண திருப்புமுனை மற்றும் ட்ரெயில் வடிவியல் சுய-வலது திருப்புமுனையை வழங்குகின்றன.' },
    field: 'physics',
    icon: '🚲',
    tags: ['motion', 'balance', 'forces'],
  },
  {
    id: 'es_sugar_dissolve',
    title: { en: 'Sugar Dissolving in Tea', ta: 'தேநீரில் சர்க்கரை கரைதல்' },
    description: { en: 'When you stir sugar into tea, the sugar molecules spread evenly throughout the liquid.', ta: 'தேநீரில் சர்க்கரையை கிளறும்போது, சர்க்கரை மூலக்கூறுகள் திரவம் முழுவதும் சீராக பரவுகின்றன.' },
    sciencePrinciple: { en: 'Dissolving is a physical change where solute particles disperse between solvent molecules.', ta: 'கரைதல் என்பது கரைப்பான் மூலக்கூறுகளுக்கு இடையில் கரைப்பான் துகள்கள் பரவும் ஒரு இயற்பியல் மாற்றமாகும்.' },
    field: 'chemistry',
    icon: '☕',
    tags: ['solutions', 'chemistry', 'mixtures'],
  },
  {
    id: 'es_bending_light',
    title: { en: 'Bending Light (Refraction)', ta: 'ஒளியை வளைத்தல் (ஒளிவிலகல்)' },
    description: { en: 'A straw in water looks bent because light changes speed when entering a different medium.', ta: 'தண்ணீரில் உள்ள குச்சி வளைந்தது போல் தோன்றும், ஏனெனில் ஒளி வேறு ஊடகத்தில் நுழையும்போது வேகத்தை மாற்றுகிறது.' },
    sciencePrinciple: { en: 'Refraction occurs because light travels at different speeds in different media, bending at the interface.', ta: 'ஒளிவிலகல் ஏற்படுகிறது, ஏனெனில் ஒளி வெவ்வேற� ஊடகங்களில் வெவ்வேறு வேகங்களில் பயணிக்கிறது, இடைமுகத்தில் வளைகிறது.' },
    field: 'physics',
    icon: '🥤',
    tags: ['optics', 'refraction', 'light'],
  },
  {
    id: 'es_sound_vibration',
    title: { en: 'Sound & Vibrations', ta: 'ஒலி & அதிர்வுகள்' },
    description: { en: 'All sounds are vibrations traveling through air (or water/solids) to our ears.', ta: 'அனைத்து ஒலிகளும் காற்று (அல்லது நீர்/திடப்பொருட்கள்) வழியாக நம் காதுகளுக்கு பயணிக்கும் அதிர்வுகள்.' },
    sciencePrinciple: { en: 'Sound waves are longitudinal waves — compressions and rarefactions of air molecules.', ta: 'ஒலி அலைகள் நெட்டு அலைகள் — காற்று மூலக்கூறுகளின் சுருக்கங்கள் மற்றும் விரிவாக்கங்கள்.' },
    field: 'physics',
    icon: '🔊',
    tags: ['sound', 'waves', 'vibration'],
  },
  {
    id: 'es_ice_floating',
    title: { en: 'Ice Floats on Water', ta: 'பனி நீரில் மிதக்கிறது' },
    description: { en: 'Unlike most substances, water expands when it freezes, making ice less dense than liquid water.', ta: 'பெரும்பாலான பொருட்களைப் போலல்லாமல், நீர் உறையும்போது விரிவடைகிறது, இதனால் பனி திரவ நீரை விட குறைந்த அடர்த்தி கொண்டது.' },
    sciencePrinciple: { en: 'Water molecules form a crystalline lattice when frozen, creating more space between molecules.', ta: 'நீர் மூலக்கூறுகள் உறையும்போது ஒரு படிக வலையமைப்பை உருவாக்கி, மூலக்கூறுகளுக்கு இடையே அதிக இடத்தை உருவாக்குகின்றன.' },
    field: 'chemistry',
    icon: '🧊',
    tags: ['density', 'states', 'water'],
  },
  {
    id: 'es_rain',
    title: { en: 'How Rain Forms', ta: 'மழை எவ்வாறு உருவாகிறது' },
    description: { en: 'Rain forms when water vapor in clouds condenses into droplets heavy enough to fall.', ta: 'மேகங்களில் உள்ள நீராவி போதுமான அளவு கனமான துளிகளாக ஒடுக்கமடையும்போது மழை உருவாகிறது.' },
    sciencePrinciple: { en: 'Evaporation, condensation, and precipitation form the water cycle driven by solar energy.', ta: 'ஆவியாதல், ஒடுக்கம் மற்றும் மழைப்பொழிவு சூரிய ஆற்றலால் இயக்கப்படும் நீர் சுழற்சியை உருவாக்குகின்றன.' },
    field: 'environment',
    icon: '🌧️',
    tags: ['water cycle', 'weather', 'environment'],
  },
  {
    id: 'es_moon_phases',
    title: { en: 'Moon Phases', ta: 'நிலவு நிலைகள்' },
    description: { en: 'The Moon appears to change shape because we see different portions of its sunlit side.', ta: 'நிலவு மாறுவது போல் தோன்றுகிறது, ஏனெனில் அதன் சூரிய ஒளியில் பக்கத்தின் வெவ்வேறு பகுதிகளை நாம் பார்க்கிறோம்.' },
    sciencePrinciple: { en: 'As the Moon orbits Earth, the angle between Sun, Earth, and Moon changes, altering the visible illuminated portion.', ta: 'நிலவு பூமியை சுற்றும்போது, சூரியன், பூமி மற்றும் நிலவு இடையேயான கோணம் மாறுகிறது, புலப்படும் ஒளிரும் பகுதியை மாற்றுகிறது.' },
    field: 'space',
    icon: '🌙',
    tags: ['astronomy', 'space', 'light'],
  },
  {
    id: 'es_fingerprint',
    title: { en: 'Fingerprints', ta: 'விரல் ரேகைகள்' },
    description: { en: 'Every person has unique fingerprints formed by ridges on their fingertips.', ta: 'ஒவ்வொரு நபரும் விரல் நுனியில் உள்ள தடங்களால் உருவாக்கப்பட்ட தனித்துவமான விரல் ரேகைகளைக் கொண்டுள்ளனர்.' },
    sciencePrinciple: { en: 'Friction ridges form during fetal development and remain unchanged throughout life.', ta: 'உராய்வு தடங்கள் கரு வளர்ச்சியின் போது உருவாகி, வாழ்நாள் முழுவதும் மாறாமல் இருக்கும்.' },
    field: 'biology',
    icon: '👆',
    tags: ['biology', 'identification', 'body'],
  },
  {
    id: 'es_solar_panel',
    title: { en: 'Solar Panels', ta: 'சோலார் பேனல்கள்' },
    description: { en: 'Solar panels convert sunlight directly into electricity using semiconductor materials.', ta: 'சோலார் பேனல்கள் குறைக்கடத்தி பொருட்கள் பயன்படுத்தி சூரிய ஒளியை நேரடியாக மின்சாரமாக மாற்றுகின்றன.' },
    sciencePrinciple: { en: 'Photovoltaic cells use the photoelectric effect to convert photons into electric current.', ta: 'ஒளிமின் செல்கள் ஃபோட்டான்களை மின்னோட்டமாக மாற்ற ஒளிமின் விளைவைப் பயன்படுத்துகின்றன.' },
    field: 'physics',
    icon: '☀️',
    tags: ['renewable energy', 'solar', 'electricity'],
  },
  {
    id: 'es_decomposition',
    title: { en: 'Composting & Decomposition', ta: 'உரம் தயாரித்தல் & சிதைவு' },
    description: { en: 'Food scraps decompose into nutrient-rich compost through bacterial and fungal action.', ta: 'உணவு கழிவுகள் பாக்டீரியா மற்றும் பூஞ்சை செயல்கள் மூலம் ஊட்டச்சத்து நிறைந்த கம்போஸ்டாக சிதைகின்றன.' },
    sciencePrinciple: { en: 'Decomposers break down organic matter through enzymatic reactions, returning nutrients to soil.', ta: 'சிதைவு நிலைகள் நொதிய வினைகள் மூலம் கரிமப் பொருளை உடைத்து, ஊட்டச்சத்துக்களை மண்ணுக்குத் திரும்பச் செய்கின்றன.' },
    field: 'environment',
    icon: '🌱',
    tags: ['decomposition', 'environment', 'biology'],
  },
  {
    id: 'es_pollution',
    title: { en: 'Air Pollution & Health', ta: 'காற்று மாசுபாடு & ஆரோக்கியம்' },
    description: { en: 'Air pollution from vehicles and factories contains harmful particles that affect lung health.', ta: 'வாகனங்கள் மற்றும் தொழிற்சாலைகளிலிருந்து வரும் காற்று மாசுபாடு நுரையீரல் ஆரோக்கியத்தை பாதிக்கும் தீங்கு விளைவிக்கும் துகள்களைக் கொண்டுள்ளது.' },
    sciencePrinciple: { en: 'Particulate matter (PM2.5) penetrates deep into lungs, causing inflammation and respiratory issues.', ta: 'துகள் பொருள் (PM2.5) நுரையீரலுக்குள் ஆழமாக ஊடுருவி, அழற்சி மற்றும் சுவாச பிரச்சினைகளை ஏற்படுத்துகிறது.' },
    field: 'environment',
    icon: '🏭',
    tags: ['pollution', 'health', 'environment'],
  },
];
