import { ScienceWordGridLevel } from './science-word-grid.types';

export const SCIENCE_WORD_GRID_LEVELS: ScienceWordGridLevel[] = [
  {
    id: 'grid-01',
    name: 'Level 1: Physics Basics',
    category: { en: 'Physics', ta: 'இயற்பியல்' },
    grid: [
      ['A', 'T', 'O', 'M'],
      ['W', 'A', 'V', 'E'],
      ['M', 'A', 'S', 'S'],
      ['X', 'Y', 'Z', 'K'],
    ],
    taGrid: [
      ['அ', 'ணு', 'க', 'ள'],
      ['அ', 'லை', 'ம', 'ர'],
      ['நி', 'றை', 'வி', 'ல்'],
      ['ப', 'ட', 'ம்', 'க'],
    ],
    words: [
      {
        id: 'w1',
        word: { en: 'ATOM', ta: 'அணு' },
        hint: { en: 'Basic unit of matter', ta: 'பருப்பொருளின் அடிப்படை அலகு' },
        path: [{ row: 0, col: 0 }, { row: 0, col: 1 }, { row: 0, col: 2 }, { row: 0, col: 3 }],
      },
      {
        id: 'w2',
        word: { en: 'WAVE', ta: 'அலை' },
        hint: { en: 'Energy oscillation', ta: 'ஆற்றல் பரவும் அதிர்வு' },
        path: [{ row: 1, col: 0 }, { row: 1, col: 1 }, { row: 1, col: 2 }, { row: 1, col: 3 }],
      },
      {
        id: 'w3',
        word: { en: 'MASS', ta: 'நிறை' },
        hint: { en: 'Amount of matter in a body', ta: 'பொருளின் அளவு' },
        path: [{ row: 2, col: 0 }, { row: 2, col: 1 }, { row: 2, col: 2 }, { row: 2, col: 3 }],
      },
    ],
  },
  {
    id: 'grid-02',
    name: 'Level 2: Living Cell',
    category: { en: 'Biology', ta: 'உயிரியல்' },
    grid: [
      ['C', 'E', 'L', 'L'],
      ['G', 'E', 'N', 'E'],
      ['R', 'O', 'O', 'T'],
      ['L', 'E', 'A', 'F'],
    ],
    taGrid: [
      ['செ', 'ல்', 'ம', 'ர'],
      ['ம', 'ர', 'ப', 'ணு'],
      ['வே', 'ர்', 'க', 'ள'],
      ['இ', 'லை', 'பூ', 'க்'],
    ],
    words: [
      {
        id: 'w1',
        word: { en: 'CELL', ta: 'செல்' },
        hint: { en: 'Smallest unit of life', ta: 'உயிரின் அடிப்படை அலகு' },
        path: [{ row: 0, col: 0 }, { row: 0, col: 1 }, { row: 0, col: 2 }, { row: 0, col: 3 }],
      },
      {
        id: 'w2',
        word: { en: 'GENE', ta: 'மரபணு' },
        hint: { en: 'Hereditary unit', ta: 'பரம்பரை அலகு' },
        path: [{ row: 1, col: 0 }, { row: 1, col: 1 }, { row: 1, col: 2 }, { row: 1, col: 3 }],
      },
      {
        id: 'w3',
        word: { en: 'ROOT', ta: 'வேர்' },
        hint: { en: 'Underground plant anchor', ta: 'நீரை உறிஞ்சும் தாவர உறுப்பு' },
        path: [{ row: 2, col: 0 }, { row: 2, col: 1 }, { row: 2, col: 2 }, { row: 2, col: 3 }],
      },
      {
        id: 'w4',
        word: { en: 'LEAF', ta: 'இலை' },
        hint: { en: 'Photosynthetic organ', ta: 'உணவு தயாரிக்கும் உறுப்பு' },
        path: [{ row: 3, col: 0 }, { row: 3, col: 1 }, { row: 3, col: 2 }, { row: 3, col: 3 }],
      },
    ],
  },
  {
    id: 'grid-03',
    name: 'Level 3: Chemistry Lab',
    category: { en: 'Chemistry', ta: 'வேதியியல்' },
    grid: [
      ['A', 'C', 'I', 'D'],
      ['B', 'A', 'S', 'E'],
      ['S', 'A', 'L', 'T'],
      ['I', 'O', 'N', 'S'],
    ],
    taGrid: [
      ['அ', 'மி', 'ல', 'ம்'],
      ['கா', 'ர', 'ம்', 'க'],
      ['உ', 'ப்', 'பு', 'ம'],
      ['அ', 'ய', 'னி', 'க'],
    ],
    words: [
      {
        id: 'w1',
        word: { en: 'ACID', ta: 'அமிலம்' },
        hint: { en: 'pH less than 7', ta: 'pH 7-க்கு கீழ் உள்ள பொருள்' },
        path: [{ row: 0, col: 0 }, { row: 0, col: 1 }, { row: 0, col: 2 }, { row: 0, col: 3 }],
      },
      {
        id: 'w2',
        word: { en: 'BASE', ta: 'காரம்' },
        hint: { en: 'pH greater than 7', ta: 'pH 7-க்கு மேல் உள்ள பொருள்' },
        path: [{ row: 1, col: 0 }, { row: 1, col: 1 }, { row: 1, col: 2 }, { row: 1, col: 3 }],
      },
      {
        id: 'w3',
        word: { en: 'SALT', ta: 'உப்பு' },
        hint: { en: 'Neutral product of acid+base', ta: 'அமிலமும் காரமும் இணைந்த விளைபொருள்' },
        path: [{ row: 2, col: 0 }, { row: 2, col: 1 }, { row: 2, col: 2 }, { row: 2, col: 3 }],
      },
      {
        id: 'w4',
        word: { en: 'IONS', ta: 'அயனி' },
        hint: { en: 'Charged atoms', ta: 'மின்சுமை பெற்ற துகள்' },
        path: [{ row: 3, col: 0 }, { row: 3, col: 1 }, { row: 3, col: 2 }, { row: 3, col: 3 }],
      },
    ],
  },
  {
    id: 'grid-04',
    name: 'Level 4: Cosmos & Space',
    category: { en: 'Space', ta: 'விண்வெளி' },
    grid: [
      ['S', 'T', 'A', 'R'],
      ['M', 'O', 'O', 'N'],
      ['M', 'A', 'R', 'S'],
      ['N', 'O', 'V', 'A'],
    ],
    taGrid: [
      ['வி', 'ண்', 'மீ', 'ன்'],
      ['நி', 'ல', 'வு', 'க'],
      ['செ', 'வ்', 'வா', 'ய்'],
      ['வி', 'ண்', 'வெ', 'ளி'],
    ],
    words: [
      {
        id: 'w1',
        word: { en: 'STAR', ta: 'விண்மீன்' },
        hint: { en: 'Luminous sphere of plasma', ta: 'ஒளிரும் விண்பொருள்' },
        path: [{ row: 0, col: 0 }, { row: 0, col: 1 }, { row: 0, col: 2 }, { row: 0, col: 3 }],
      },
      {
        id: 'w2',
        word: { en: 'MOON', ta: 'நிலவு' },
        hint: { en: 'Earth satellite', ta: 'பூமியின் துணைக்கோள்' },
        path: [{ row: 1, col: 0 }, { row: 1, col: 1 }, { row: 1, col: 2 }, { row: 1, col: 3 }],
      },
      {
        id: 'w3',
        word: { en: 'MARS', ta: 'செவ்வாய்' },
        hint: { en: 'The red planet', ta: 'சிவப்புக் கோள்' },
        path: [{ row: 2, col: 0 }, { row: 2, col: 1 }, { row: 2, col: 2 }, { row: 2, col: 3 }],
      },
      {
        id: 'w4',
        word: { en: 'NOVA', ta: 'விண்வெளி' },
        hint: { en: 'Exploding star explosion', ta: 'விண்மீன் வெடிப்பு' },
        path: [{ row: 3, col: 0 }, { row: 3, col: 1 }, { row: 3, col: 2 }, { row: 3, col: 3 }],
      },
    ],
  },
  {
    id: 'grid-05',
    name: 'Level 5: Energy & Heat',
    category: { en: 'Energy', ta: 'ஆற்றல்' },
    grid: [
      ['H', 'E', 'A', 'T'],
      ['W', 'O', 'R', 'K'],
      ['J', 'O', 'U', 'L'],
      ['V', 'O', 'L', 'T'],
    ],
    taGrid: [
      ['வெ', 'ப்ப', 'ம்', 'க'],
      ['வே', 'லை', 'செ', 'ய்'],
      ['ஆ', 'ற்', 'ற', 'ல்'],
      ['மின்', 'ன', 'ழு', 'த்தம்'],
    ],
    words: [
      {
        id: 'w1',
        word: { en: 'HEAT', ta: 'வெப்பம்' },
        hint: { en: 'Thermal energy flow', ta: 'வெப்ப ஆற்றல்' },
        path: [{ row: 0, col: 0 }, { row: 0, col: 1 }, { row: 0, col: 2 }, { row: 0, col: 3 }],
      },
      {
        id: 'w2',
        word: { en: 'WORK', ta: 'வேலை' },
        hint: { en: 'Force times distance', ta: 'விசை நகர்த்தும் தொலைவு' },
        path: [{ row: 1, col: 0 }, { row: 1, col: 1 }, { row: 1, col: 2 }, { row: 1, col: 3 }],
      },
      {
        id: 'w3',
        word: { en: 'JOUL', ta: 'ஆற்றல்' },
        hint: { en: 'Unit of energy', ta: 'ஆற்றலின் அலகு' },
        path: [{ row: 2, col: 0 }, { row: 2, col: 1 }, { row: 2, col: 2 }, { row: 2, col: 3 }],
      },
      {
        id: 'w4',
        word: { en: 'VOLT', ta: 'மின்னழுத்தம்' },
        hint: { en: 'Electric potential unit', ta: 'மின்னழுத்த அலகு' },
        path: [{ row: 3, col: 0 }, { row: 3, col: 1 }, { row: 3, col: 2 }, { row: 3, col: 3 }],
      },
    ],
  },
  {
    id: 'grid-06',
    name: 'Level 6: Human Anatomy',
    category: { en: 'Human Body', ta: 'மனித உடல்' },
    grid: [
      ['B', 'O', 'N', 'E'],
      ['L', 'U', 'N', 'G'],
      ['S', 'K', 'I', 'N'],
      ['V', 'E', 'I', 'N'],
    ],
    taGrid: [
      ['எ', 'லு', 'ம்', 'பு'],
      ['நு', 'ரை', 'யீ', 'ரல்'],
      ['தோ', 'ல்', 'ம', 'ர'],
      ['ந', 'ரம்', 'பு', 'க'],
    ],
    words: [
      {
        id: 'w1',
        word: { en: 'BONE', ta: 'எலும்பு' },
        hint: { en: 'Skeletal framework', ta: 'உடலின் எலும்புக்கூடு' },
        path: [{ row: 0, col: 0 }, { row: 0, col: 1 }, { row: 0, col: 2 }, { row: 0, col: 3 }],
      },
      {
        id: 'w2',
        word: { en: 'LUNG', ta: 'நுரையீரல்' },
        hint: { en: 'Respiratory organ', ta: 'சுவாச உறுப்பு' },
        path: [{ row: 1, col: 0 }, { row: 1, col: 1 }, { row: 1, col: 2 }, { row: 1, col: 3 }],
      },
      {
        id: 'w3',
        word: { en: 'SKIN', ta: 'தோல்' },
        hint: { en: 'Largest human organ', ta: 'மிகப்பெரிய உணர் உறுப்பு' },
        path: [{ row: 2, col: 0 }, { row: 2, col: 1 }, { row: 2, col: 2 }, { row: 2, col: 3 }],
      },
      {
        id: 'w4',
        word: { en: 'VEIN', ta: 'நரம்பு' },
        hint: { en: 'Blood carrying vessel', ta: 'இரத்தக் குழாய்' },
        path: [{ row: 3, col: 0 }, { row: 3, col: 1 }, { row: 3, col: 2 }, { row: 3, col: 3 }],
      },
    ],
  },
  {
    id: 'grid-07',
    name: 'Level 7: Optics & Waves',
    category: { en: 'Optics', ta: 'ஒளியியல்' },
    grid: [
      ['L', 'E', 'N', 'S'],
      ['R', 'A', 'Y', 'S'],
      ['B', 'E', 'A', 'M'],
      ['F', 'O', 'C', 'I'],
    ],
    taGrid: [
      ['லெ', 'ன்', 'சு', 'க'],
      ['க', 'தி', 'ர்', 'க'],
      ['ஒ', 'ளிக்', 'க', 'ற்றை'],
      ['கு', 'வி', 'யம்', 'ம'],
    ],
    words: [
      {
        id: 'w1',
        word: { en: 'LENS', ta: 'லென்சு' },
        hint: { en: 'Curved optical glass', ta: 'வளைந்த கண்ணாடி' },
        path: [{ row: 0, col: 0 }, { row: 0, col: 1 }, { row: 0, col: 2 }, { row: 0, col: 3 }],
      },
      {
        id: 'w2',
        word: { en: 'RAYS', ta: 'கதிர்' },
        hint: { en: 'Straight light paths', ta: 'நேர்கோட்டு ஒளிக்கற்றை' },
        path: [{ row: 1, col: 0 }, { row: 1, col: 1 }, { row: 1, col: 2 }, { row: 1, col: 3 }],
      },
      {
        id: 'w3',
        word: { en: 'BEAM', ta: 'ஒளிக்கற்றை' },
        hint: { en: 'Collection of light rays', ta: 'ஒளிக் கதிர்களின் தொகுப்பு' },
        path: [{ row: 2, col: 0 }, { row: 2, col: 1 }, { row: 2, col: 2 }, { row: 2, col: 3 }],
      },
      {
        id: 'w4',
        word: { en: 'FOCI', ta: 'குவியம்' },
        hint: { en: 'Focal convergence points', ta: 'ஒளிக் குவியப் புள்ளிகள்' },
        path: [{ row: 3, col: 0 }, { row: 3, col: 1 }, { row: 3, col: 2 }, { row: 3, col: 3 }],
      },
    ],
  },
  {
    id: 'grid-08',
    name: 'Level 8: Ecology & Biosphere',
    category: { en: 'Ecology', ta: 'சூழலியல்' },
    grid: [
      ['S', 'O', 'I', 'L'],
      ['R', 'A', 'I', 'N'],
      ['F', 'O', 'O', 'D'],
      ['P', 'E', 'S', 'T'],
    ],
    taGrid: [
      ['ம', 'ண்', 'வ', 'ளம்'],
      ['ம', 'ழை', 'நீ', 'ர்'],
      ['உ', 'ண', 'வு', 'ம'],
      ['பூ', 'ச்சி', 'க', 'ள'],
    ],
    words: [
      {
        id: 'w1',
        word: { en: 'SOIL', ta: 'மண்' },
        hint: { en: 'Top layer of Earth crust', ta: 'பூமியின் மேல் அடுக்கு' },
        path: [{ row: 0, col: 0 }, { row: 0, col: 1 }, { row: 0, col: 2 }, { row: 0, col: 3 }],
      },
      {
        id: 'w2',
        word: { en: 'RAIN', ta: 'மழை' },
        hint: { en: 'Liquid precipitation', ta: 'வானிலிருந்து பொழியும் நீர்' },
        path: [{ row: 1, col: 0 }, { row: 1, col: 1 }, { row: 1, col: 2 }, { row: 1, col: 3 }],
      },
      {
        id: 'w3',
        word: { en: 'FOOD', ta: 'உணவு' },
        hint: { en: 'Nutritional energy', ta: 'உயிரினங்களின் ஊட்டம்' },
        path: [{ row: 2, col: 0 }, { row: 2, col: 1 }, { row: 2, col: 2 }, { row: 2, col: 3 }],
      },
      {
        id: 'w4',
        word: { en: 'PEST', ta: 'பூச்சி' },
        hint: { en: 'Crop damaging organism', ta: 'பயிர்களை தாக்கும் பூச்சி' },
        path: [{ row: 3, col: 0 }, { row: 3, col: 1 }, { row: 3, col: 2 }, { row: 3, col: 3 }],
      },
    ],
  },
  {
    id: 'grid-09',
    name: 'Level 9: Microscopic World',
    category: { en: 'Microbiology', ta: 'நுண்ணுயிரியல்' },
    grid: [
      ['G', 'E', 'R', 'M'],
      ['D', 'N', 'A', 'S'],
      ['V', 'I', 'R', 'U'],
      ['C', 'O', 'D', 'E'],
    ],
    taGrid: [
      ['நு', 'ண்', 'ணு', 'யிர்'],
      ['ம', 'ர', 'ப', 'ணு'],
      ['வை', 'ர', 'ஸ்', 'க'],
      ['கு', 'றி', 'யீ', 'டு'],
    ],
    words: [
      {
        id: 'w1',
        word: { en: 'GERM', ta: 'நுண்ணுயிர்' },
        hint: { en: 'Microorganism', ta: 'கண்ணுக்குத் தெரியாத நுண்ணுயிர்' },
        path: [{ row: 0, col: 0 }, { row: 0, col: 1 }, { row: 0, col: 2 }, { row: 0, col: 3 }],
      },
      {
        id: 'w2',
        word: { en: 'DNAS', ta: 'மரபணு' },
        hint: { en: 'Genetic blueprint molecules', ta: 'மரபியல் மூலக்கூறு' },
        path: [{ row: 1, col: 0 }, { row: 1, col: 1 }, { row: 1, col: 2 }, { row: 1, col: 3 }],
      },
      {
        id: 'w3',
        word: { en: 'VIRU', ta: 'வைரஸ்' },
        hint: { en: 'Submicroscopic infectious agent', ta: 'நோயுண்டாக்கும் நுண்துகள்' },
        path: [{ row: 2, col: 0 }, { row: 2, col: 1 }, { row: 2, col: 2 }, { row: 2, col: 3 }],
      },
      {
        id: 'w4',
        word: { en: 'CODE', ta: 'குறியீடு' },
        hint: { en: 'Genetic triple sequence', ta: 'மரபியல் மொழி' },
        path: [{ row: 3, col: 0 }, { row: 3, col: 1 }, { row: 3, col: 2 }, { row: 3, col: 3 }],
      },
    ],
  },
  {
    id: 'grid-10',
    name: 'Level 10: Master Science Lexicon',
    category: { en: 'Science Master', ta: 'அறிவியல் களஞ்சியம்' },
    grid: [
      ['F', 'A', 'C', 'T'],
      ['L', 'A', 'W', 'S'],
      ['T', 'E', 'S', 'T'],
      ['D', 'A', 'T', 'A'],
    ],
    taGrid: [
      ['உ', 'ண்', 'மை', 'க'],
      ['வி', 'தி', 'க', 'ள'],
      ['ஆ', 'ய்', 'வு', 'ம'],
      ['த', 'ர', 'வு', 'க'],
    ],
    words: [
      {
        id: 'w1',
        word: { en: 'FACT', ta: 'உண்மை' },
        hint: { en: 'Proven scientific reality', ta: 'நிரூபிக்கப்பட்ட உண்மை' },
        path: [{ row: 0, col: 0 }, { row: 0, col: 1 }, { row: 0, col: 2 }, { row: 0, col: 3 }],
      },
      {
        id: 'w2',
        word: { en: 'LAWS', ta: 'விதிகள்' },
        hint: { en: 'Universal scientific principles', ta: 'இயற்கை விதிகள்' },
        path: [{ row: 1, col: 0 }, { row: 1, col: 1 }, { row: 1, col: 2 }, { row: 1, col: 3 }],
      },
      {
        id: 'w3',
        word: { en: 'TEST', ta: 'ஆய்வு' },
        hint: { en: 'Experiment validation', ta: 'பரிசோதனை முறை' },
        path: [{ row: 2, col: 0 }, { row: 2, col: 1 }, { row: 2, col: 2 }, { row: 2, col: 3 }],
      },
      {
        id: 'w4',
        word: { en: 'DATA', ta: 'தரவு' },
        hint: { en: 'Collected observations', ta: 'சேகரிக்கப்பட்ட விவரங்கள்' },
        path: [{ row: 3, col: 0 }, { row: 3, col: 1 }, { row: 3, col: 2 }, { row: 3, col: 3 }],
      },
    ],
  },
];
