import { MemoryMatrixLevel } from './memory-matrix.types';

export const MEMORY_MATRIX_LEVELS: MemoryMatrixLevel[] = [
  {
    id: 'mem-01',
    name: 'Level 1: Great Pioneers (4 pairs)',
    gridSize: { rows: 2, cols: 4 },
    category: 'Scientists & Inventions',
    cards: [
      { id: 'c1', pairId: 'p1', content: { en: 'Newton', ta: 'நியூட்டன்' }, type: 'scientist', icon: '🍎' },
      { id: 'c2', pairId: 'p1', content: { en: 'Gravity', ta: 'ஈர்ப்பு விசை' }, type: 'discovery', icon: '🌌' },
      { id: 'c3', pairId: 'p2', content: { en: 'Einstein', ta: 'ஐன்ஸ்டீன்' }, type: 'scientist', icon: '⚡' },
      { id: 'c4', pairId: 'p2', content: { en: 'Relativity', ta: 'சார்பியல் கோட்பாடு' }, type: 'discovery', icon: '⏳' },
      { id: 'c5', pairId: 'p3', content: { en: 'Curie', ta: 'கியூரி' }, type: 'scientist', icon: '🧪' },
      { id: 'c6', pairId: 'p3', content: { en: 'Radium', ta: 'ரேடியம்' }, type: 'discovery', icon: '✨' },
      { id: 'c7', pairId: 'p4', content: { en: 'Galileo', ta: 'கலீலியோ' }, type: 'scientist', icon: '🔭' },
      { id: 'c8', pairId: 'p4', content: { en: 'Telescope', ta: 'தொலைநோக்கி' }, type: 'discovery', icon: '🪐' },
    ],
  },
  {
    id: 'mem-02',
    name: 'Level 2: Human Body (4 pairs)',
    gridSize: { rows: 2, cols: 4 },
    category: 'Organs & Functions',
    cards: [
      { id: 'c1', pairId: 'p1', content: { en: 'Heart', ta: 'இதயம்' }, type: 'organ', icon: '❤️' },
      { id: 'c2', pairId: 'p1', content: { en: 'Pumps Blood', ta: 'இரத்தம் பாய்ச்சுதல்' }, type: 'discovery', icon: '🩸' },
      { id: 'c3', pairId: 'p2', content: { en: 'Lungs', ta: 'நுரையீரல்' }, type: 'organ', icon: '🫁' },
      { id: 'c4', pairId: 'p2', content: { en: 'Oxygen Gas', ta: 'ஆக்சிஜன் பரிமாற்றம்' }, type: 'discovery', icon: '💨' },
      { id: 'c5', pairId: 'p3', content: { en: 'Brain', ta: 'மூளை' }, type: 'organ', icon: '🧠' },
      { id: 'c6', pairId: 'p3', content: { en: 'Nerves & Thought', ta: 'நரம்பு & சிந்தனை' }, type: 'discovery', icon: '⚡' },
      { id: 'c7', pairId: 'p4', content: { en: 'Kidney', ta: 'சிறுநீரகம்' }, type: 'organ', icon: '🫘' },
      { id: 'c8', pairId: 'p4', content: { en: 'Filters Waste', ta: 'கழிவு வடிகட்டுதல்' }, type: 'discovery', icon: '💧' },
    ],
  },
  {
    id: 'mem-03',
    name: 'Level 3: Chemical Symbols (4 pairs)',
    gridSize: { rows: 2, cols: 4 },
    category: 'Elements & Symbols',
    cards: [
      { id: 'c1', pairId: 'p1', content: { en: 'Gold', ta: 'தங்கம்' }, type: 'element', icon: '🪙' },
      { id: 'c2', pairId: 'p1', content: { en: 'Au (79)', ta: 'Au (79)' }, type: 'symbol', icon: '👑' },
      { id: 'c3', pairId: 'p2', content: { en: 'Silver', ta: 'வெள்ளி' }, type: 'element', icon: '🥈' },
      { id: 'c4', pairId: 'p2', content: { en: 'Ag (47)', ta: 'Ag (47)' }, type: 'symbol', icon: '💎' },
      { id: 'c5', pairId: 'p3', content: { en: 'Iron', ta: 'இரும்பு' }, type: 'element', icon: '🧲' },
      { id: 'c6', pairId: 'p3', content: { en: 'Fe (26)', ta: 'Fe (26)' }, type: 'symbol', icon: '⚙️' },
      { id: 'c7', pairId: 'p4', content: { en: 'Copper', ta: 'செம்பு' }, type: 'element', icon: '🥉' },
      { id: 'c8', pairId: 'p4', content: { en: 'Cu (29)', ta: 'Cu (29)' }, type: 'symbol', icon: '🔌' },
    ],
  },
  {
    id: 'mem-04',
    name: 'Level 4: Physics Concepts (6 pairs)',
    gridSize: { rows: 3, cols: 4 },
    category: 'Physics & Units',
    cards: [
      { id: 'c1', pairId: 'p1', content: { en: 'Force', ta: 'விசை' }, type: 'element', icon: '💪' },
      { id: 'c2', pairId: 'p1', content: { en: 'Newton (N)', ta: 'நியூட்டன் (N)' }, type: 'symbol', icon: '⚖️' },
      { id: 'c3', pairId: 'p2', content: { en: 'Energy', ta: 'ஆற்றல்' }, type: 'element', icon: '⚡' },
      { id: 'c4', pairId: 'p2', content: { en: 'Joule (J)', ta: 'ஜூல் (J)' }, type: 'symbol', icon: '🔋' },
      { id: 'c5', pairId: 'p3', content: { en: 'Power', ta: 'திறன்' }, type: 'element', icon: '💡' },
      { id: 'c6', pairId: 'p3', content: { en: 'Watt (W)', ta: 'வாட் (W)' }, type: 'symbol', icon: '⚙️' },
      { id: 'c7', pairId: 'p4', content: { en: 'Pressure', ta: 'அழுத்தம்' }, type: 'element', icon: '⏱️' },
      { id: 'c8', pairId: 'p4', content: { en: 'Pascal (Pa)', ta: 'பாஸ்கல் (Pa)' }, type: 'symbol', icon: '🌊' },
      { id: 'c9', pairId: 'p5', content: { en: 'Frequency', ta: 'அதிர்வெண்' }, type: 'element', icon: '〰️' },
      { id: 'c10', pairId: 'p5', content: { en: 'Hertz (Hz)', ta: 'ஹெர்ட்ஸ் (Hz)' }, type: 'symbol', icon: '📻' },
      { id: 'c11', pairId: 'p6', content: { en: 'Current', ta: 'மின்னோட்டம்' }, type: 'element', icon: '🔌' },
      { id: 'c12', pairId: 'p6', content: { en: 'Ampere (A)', ta: 'ஆம்பியர் (A)' }, type: 'symbol', icon: '⚡' },
    ],
  },
  {
    id: 'mem-05',
    name: 'Level 5: Astronomy Discoveries (6 pairs)',
    gridSize: { rows: 3, cols: 4 },
    category: 'Space Exploration',
    cards: [
      { id: 'c1', pairId: 'p1', content: { en: 'Sun', ta: 'சூரியன்' }, type: 'element', icon: '☀️' },
      { id: 'c2', pairId: 'p1', content: { en: 'Solar Core', ta: 'சூரிய மையம்' }, type: 'discovery', icon: '🔥' },
      { id: 'c3', pairId: 'p2', content: { en: 'Jupiter', ta: 'வியாழன்' }, type: 'element', icon: '🪐' },
      { id: 'c4', pairId: 'p2', content: { en: 'Great Red Spot', ta: 'பெருஞ் சிவப்பு புள்ளி' }, type: 'discovery', icon: '🌀' },
      { id: 'c5', pairId: 'p3', content: { en: 'Saturn', ta: 'சனி' }, type: 'element', icon: '🪐' },
      { id: 'c6', pairId: 'p3', content: { en: 'Ice Rings', ta: 'பனி வளையங்கள்' }, type: 'discovery', icon: '❄️' },
      { id: 'c7', pairId: 'p4', content: { en: 'Mars', ta: 'செவ்வாய்' }, type: 'element', icon: '🔴' },
      { id: 'c8', pairId: 'p4', content: { en: 'Red Planet', ta: 'சிவப்புக் கோள்' }, type: 'discovery', icon: '🏜️' },
      { id: 'c9', pairId: 'p5', content: { en: 'Moon', ta: 'சந்திரன்' }, type: 'element', icon: '🌙' },
      { id: 'c10', pairId: 'p5', content: { en: 'Tides', ta: 'கடல் அலைகள்' }, type: 'discovery', icon: '🌊' },
      { id: 'c11', pairId: 'p6', content: { en: 'Venus', ta: 'வெள்ளி' }, type: 'element', icon: '✨' },
      { id: 'c12', pairId: 'p6', content: { en: 'Hottest Planet', ta: 'வெப்பமான கோள்' }, type: 'discovery', icon: '🌡️' },
    ],
  },
  {
    id: 'mem-06',
    name: 'Level 6: Cells & Genetics (6 pairs)',
    gridSize: { rows: 3, cols: 4 },
    category: 'Cell Biology',
    cards: [
      { id: 'c1', pairId: 'p1', content: { en: 'Mitochondria', ta: 'மைட்டோகாண்ட்ரியா' }, type: 'organ', icon: '⚡' },
      { id: 'c2', pairId: 'p1', content: { en: 'Powerhouse', ta: 'ஆற்றல் மையம்' }, type: 'discovery', icon: '🔋' },
      { id: 'c3', pairId: 'p2', content: { en: 'Chloroplast', ta: 'பசுங்கணிகம்' }, type: 'organ', icon: '🍃' },
      { id: 'c4', pairId: 'p2', content: { en: 'Photosynthesis', ta: 'ஒளிச்சேர்க்கை' }, type: 'discovery', icon: '☀️' },
      { id: 'c5', pairId: 'p3', content: { en: 'Nucleus', ta: 'உட்கரு' }, type: 'organ', icon: '🧬' },
      { id: 'c6', pairId: 'p3', content: { en: 'DNA Control', ta: 'மரபணு மையம்' }, type: 'discovery', icon: '📜' },
      { id: 'c7', pairId: 'p4', content: { en: 'Ribosome', ta: 'ரைபோசோம்' }, type: 'organ', icon: '⚙️' },
      { id: 'c8', pairId: 'p4', content: { en: 'Protein Factory', ta: 'புரதத் தொழிற்சாலை' }, type: 'discovery', icon: '🏗️' },
      { id: 'c9', pairId: 'p5', content: { en: 'Cell Membrane', ta: 'செல் சவ்வு' }, type: 'organ', icon: '🛡️' },
      { id: 'c10', pairId: 'p5', content: { en: 'Gatekeeper', ta: 'பாதுகாப்பு எல்லை' }, type: 'discovery', icon: '🚪' },
      { id: 'c11', pairId: 'p6', content: { en: 'Vacuole', ta: 'நுண்குமிழ்' }, type: 'organ', icon: '💧' },
      { id: 'c12', pairId: 'p6', content: { en: 'Water Storage', ta: 'நீர் சேமிப்பு' }, type: 'discovery', icon: '🏺' },
    ],
  },
  {
    id: 'mem-07',
    name: 'Level 7: Famous Inventions (6 pairs)',
    gridSize: { rows: 3, cols: 4 },
    category: 'Innovations',
    cards: [
      { id: 'c1', pairId: 'p1', content: { en: 'Edison', ta: 'எடிசன்' }, type: 'scientist', icon: '💡' },
      { id: 'c2', pairId: 'p1', content: { en: 'Light Bulb', ta: 'மின்விளக்கு' }, type: 'discovery', icon: '✨' },
      { id: 'c3', pairId: 'p2', content: { en: 'Bell', ta: 'பெல்' }, type: 'scientist', icon: '☎️' },
      { id: 'c4', pairId: 'p2', content: { en: 'Telephone', ta: 'தொலைபேசி' }, type: 'discovery', icon: '📞' },
      { id: 'c5', pairId: 'p3', content: { en: 'Fleming', ta: 'பிளெமிங்' }, type: 'scientist', icon: '💊' },
      { id: 'c6', pairId: 'p3', content: { en: 'Penicillin', ta: 'பென்சிலின்' }, type: 'discovery', icon: '🧫' },
      { id: 'c7', pairId: 'p4', content: { en: 'Pasteur', ta: 'பாஸ்டர்' }, type: 'scientist', icon: '🥛' },
      { id: 'c8', pairId: 'p4', content: { en: 'Vaccines', ta: 'தடுப்பூசி' }, type: 'discovery', icon: '💉' },
      { id: 'c9', pairId: 'p5', content: { en: 'Wright Brothers', ta: 'ரைட் சகோதரர்கள்' }, type: 'scientist', icon: '✈️' },
      { id: 'c10', pairId: 'p5', content: { en: 'Aeroplane', ta: 'விமானம்' }, type: 'discovery', icon: '🛩️' },
      { id: 'c11', pairId: 'p6', content: { en: 'Raman', ta: 'சி.வி. ராமன்' }, type: 'scientist', icon: '🌈' },
      { id: 'c12', pairId: 'p6', content: { en: 'Raman Effect', ta: 'ராமன் விளைவு' }, type: 'discovery', icon: '💎' },
    ],
  },
  {
    id: 'mem-08',
    name: 'Level 8: Ecology & Nature (6 pairs)',
    gridSize: { rows: 3, cols: 4 },
    category: 'Environment',
    cards: [
      { id: 'c1', pairId: 'p1', content: { en: 'Producer', ta: 'உற்பத்தியாளர்' }, type: 'element', icon: '🌱' },
      { id: 'c2', pairId: 'p1', content: { en: 'Green Plants', ta: 'பசுமைத் தாவரம்' }, type: 'discovery', icon: '🌿' },
      { id: 'c3', pairId: 'p2', content: { en: 'Herbivore', ta: 'தாவர உண்ணி' }, type: 'element', icon: '🦌' },
      { id: 'c4', pairId: 'p2', content: { en: 'Deer & Rabbit', ta: 'மான் & முயல்' }, type: 'discovery', icon: '🐇' },
      { id: 'c5', pairId: 'p3', content: { en: 'Carnivore', ta: 'ஊன் உண்ணி' }, type: 'element', icon: '🦁' },
      { id: 'c6', pairId: 'p3', content: { en: 'Lion & Tiger', ta: 'சிங்கம் & புலி' }, type: 'discovery', icon: '🐅' },
      { id: 'c7', pairId: 'p4', content: { en: 'Decomposer', ta: 'சிதைப்பவை' }, type: 'element', icon: '🍄' },
      { id: 'c8', pairId: 'p4', content: { en: 'Fungi & Bacteria', ta: 'பூஞ்சை & பாக்டீரியா' }, type: 'discovery', icon: '🦠' },
      { id: 'c9', pairId: 'p5', content: { en: 'Atmosphere', ta: 'வளிமண்டலம்' }, type: 'element', icon: '☁️' },
      { id: 'c10', pairId: 'p5', content: { en: 'Air Envelope', ta: 'காற்று மண்டலம்' }, type: 'discovery', icon: '💨' },
      { id: 'c11', pairId: 'p6', content: { en: 'Hydrosphere', ta: 'நீர்க்கோளம்' }, type: 'element', icon: '🌊' },
      { id: 'c12', pairId: 'p6', content: { en: 'Oceans & Rivers', ta: 'கடல் & ஆறுகள்' }, type: 'discovery', icon: '💧' },
    ],
  },
  {
    id: 'mem-09',
    name: 'Level 9: States of Matter (6 pairs)',
    gridSize: { rows: 3, cols: 4 },
    category: 'Chemistry Phases',
    cards: [
      { id: 'c1', pairId: 'p1', content: { en: 'Melting', ta: 'உருகுதல்' }, type: 'element', icon: '🧊' },
      { id: 'c2', pairId: 'p1', content: { en: 'Solid → Liquid', ta: 'திண்மம் → திரவம்' }, type: 'discovery', icon: '💧' },
      { id: 'c3', pairId: 'p2', content: { en: 'Evaporation', ta: 'ஆவியாதல்' }, type: 'element', icon: '♨️' },
      { id: 'c4', pairId: 'p2', content: { en: 'Liquid → Gas', ta: 'திரவம் → வாயு' }, type: 'discovery', icon: '💨' },
      { id: 'c5', pairId: 'p3', content: { en: 'Condensation', ta: 'சுருங்குதல்' }, type: 'element', icon: '🌧️' },
      { id: 'c6', pairId: 'p3', content: { en: 'Gas → Liquid', ta: 'வாயு → திரவம்' }, type: 'discovery', icon: '🌦️' },
      { id: 'c7', pairId: 'p4', content: { en: 'Freezing', ta: 'உறைதல்' }, type: 'element', icon: '❄️' },
      { id: 'c8', pairId: 'p4', content: { en: 'Liquid → Solid', ta: 'திரவம் → திண்மம்' }, type: 'discovery', icon: '🧊' },
      { id: 'c9', pairId: 'p5', content: { en: 'Sublimation', ta: 'பதங்கமாதல்' }, type: 'element', icon: '🌫️' },
      { id: 'c10', pairId: 'p5', content: { en: 'Solid → Gas', ta: 'திண்மம் → வாயு' }, type: 'discovery', icon: '✨' },
      { id: 'c11', pairId: 'p6', content: { en: 'Plasma', ta: 'பிளாஸ்மா' }, type: 'element', icon: '⚡' },
      { id: 'c12', pairId: 'p6', content: { en: 'Ionized Gas', ta: 'அயனியாக்கப்பட்ட வாயு' }, type: 'discovery', icon: '🌟' },
    ],
  },
  {
    id: 'mem-10',
    name: 'Level 10: Grand Matrix (8 pairs)',
    gridSize: { rows: 4, cols: 4 },
    category: 'Grand Science Master',
    cards: [
      { id: 'c1', pairId: 'p1', content: { en: 'Tesla', ta: 'டெஸ்லா' }, type: 'scientist', icon: '⚡' },
      { id: 'c2', pairId: 'p1', content: { en: 'AC Power', ta: 'மாறுதிசை மின்னோட்டம்' }, type: 'discovery', icon: '🔌' },
      { id: 'c3', pairId: 'p2', content: { en: 'Darwin', ta: 'டார்வின்' }, type: 'scientist', icon: '🐒' },
      { id: 'c4', pairId: 'p2', content: { en: 'Evolution', ta: 'பரிணாம வளர்ச்சி' }, type: 'discovery', icon: '🌳' },
      { id: 'c5', pairId: 'p3', content: { en: 'Mendel', ta: 'மெண்டல்' }, type: 'scientist', icon: '🌱' },
      { id: 'c6', pairId: 'p3', content: { en: 'Genetics', ta: 'மரபியல் விதிகள்' }, type: 'discovery', icon: '🧬' },
      { id: 'c7', pairId: 'p4', content: { en: 'Bohr', ta: 'போர்' }, type: 'scientist', icon: '⚛️' },
      { id: 'c8', pairId: 'p4', content: { en: 'Atomic Model', ta: 'அணு மாதிரி' }, type: 'discovery', icon: '💫' },
      { id: 'c9', pairId: 'p5', content: { en: 'Hubble', ta: 'ஹப்பிள்' }, type: 'scientist', icon: '🌌' },
      { id: 'c10', pairId: 'p5', content: { en: 'Expanding Space', ta: 'விரியும் பேரண்டம்' }, type: 'discovery', icon: '🔭' },
      { id: 'c11', pairId: 'p6', content: { en: 'Archimedes', ta: 'ஆர்க்கிமிடீஸ்' }, type: 'scientist', icon: '🛁' },
      { id: 'c12', pairId: 'p6', content: { en: 'Buoyancy', ta: 'மிதப்பு விசை' }, type: 'discovery', icon: '🚢' },
      { id: 'c13', pairId: 'p7', content: { en: 'Faraday', ta: 'பாரடே' }, type: 'scientist', icon: '🧲' },
      { id: 'c14', pairId: 'p7', content: { en: 'Induction', ta: 'மின்காந்தத் தூண்டல்' }, type: 'discovery', icon: '⚡' },
      { id: 'c15', pairId: 'p8', content: { en: 'Lavoisier', ta: 'லவாசியர்' }, type: 'scientist', icon: '🧪' },
      { id: 'c16', pairId: 'p8', content: { en: 'Mass Conservation', ta: 'பொருண்மை அழியா விதி' }, type: 'discovery', icon: '⚖️' },
    ],
  },
];
